aws/jsii

- packages/codemaker/package-lock.json
- packages/codemaker/package.json
> Upgrade to decamelize 2.0.0

- packages/jsii-calc/test/assembly.jsii
- packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
- packages/jsii-runtime/package-lock.json
- packages/jsii/lib/compiler.ts
> fix: Report closest ancestor in overrides, not farthest, matching documentation

- packages/jsii-pacmak/test/expected.jsii-calc-base/sphinx/_scope_jsii-calc-base.rst
- packages/jsii-pacmak/test/expected.jsii-calc-lib/sphinx/_scope_jsii-calc-lib.rst
- packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst
> Fix diff failure caused by version update.

- packages/jsii/.npmignore
- packages/jsii/bin/jsii-fix-peers
> fix(jsii): jsii-fix-peers missing in npm tarball

- .github/CODEOWNERS
Related to awslabs/cdk-ops#193
> chore: Specify code owners

- .github/CODEOWNERS
> Relax codeowners

- packages/jsii-python-runtime/package.json
> Use python3 to work around pipeline dropping the +x on /bin/generate

- packages/jsii-python-runtime/setup.py
- packages/jsii-python-runtime/src/jsii/_kernel/__init__.py
- packages/jsii-python-runtime/src/jsii/_kernel/providers/process.py
- packages/jsii-python-runtime/src/jsii/_kernel/types.py
> Remove workaround for attrs namespace clash with property

- packages/jsii/package.json
> chore: remove jsii-fix-peers from package.json

- packages/jsii/lib/assembler.ts
> chore: Re-flow assembler.ts with 2-space indents.

- packages/jsii-python-runtime/src/jsii/_kernel/providers/process.py
> Need to turn the WindowsPath object into a str

- packages/jsii-spec/lib/validate-assembly.ts
> fix(jsii-spec): show deep validation errors

- packages/codemaker/package-lock.json
- packages/jsii-build-tools/package-lock.json
- packages/jsii-diff/package-lock.json
- packages/jsii-dotnet-jsonmodel/package-lock.json
- packages/jsii-dotnet-runtime-test/package-lock.json
- packages/jsii-dotnet-runtime/package-lock.json
- packages/jsii-java-runtime/package-lock.json
- packages/jsii-kernel/package-lock.json
- packages/jsii-pacmak/lib/targets/java.ts
- packages/jsii-pacmak/package-lock.json
- packages/jsii-pacmak/test/expected.jsii-calc-base/java/pom.xml
- packages/jsii-pacmak/test/expected.jsii-calc-base/python/setup.py
- packages/jsii-pacmak/test/expected.jsii-calc-lib/java/pom.xml
- packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py
- packages/jsii-pacmak/test/expected.jsii-calc/java/pom.xml
- packages/jsii-pacmak/test/expected.jsii-calc/python/setup.py
- packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
- packages/jsii-reflect/package-lock.json
- packages/jsii-ruby-runtime/package-lock.json
- packages/jsii-runtime/package-lock.json
- packages/jsii-spec/package-lock.json
- packages/jsii/package-lock.json
- packages/oo-ascii-tree/package-lock.json
> fix(java): fix illegal arguments passed to JavaDoc generator

- package-lock.json
- package.json
- packages/codemaker/package-lock.json
- packages/codemaker/package.json
- packages/jsii-diff/package-lock.json
- packages/jsii-diff/package.json
- packages/jsii-dotnet-jsonmodel/package-lock.json
- packages/jsii-dotnet-jsonmodel/package.json
- packages/jsii-dotnet-runtime-test/package-lock.json
- packages/jsii-dotnet-runtime-test/package.json
- packages/jsii-dotnet-runtime/package-lock.json
- packages/jsii-dotnet-runtime/package.json
- packages/jsii-java-runtime/package-lock.json
- packages/jsii-java-runtime/package.json
- packages/jsii-kernel/package-lock.json
- packages/jsii-kernel/package.json
- packages/jsii-pacmak/package-lock.json
- packages/jsii-pacmak/package.json
- packages/jsii-reflect/package-lock.json
- packages/jsii-reflect/package.json
- packages/jsii-ruby-runtime/package-lock.json
- packages/jsii-ruby-runtime/package.json
- packages/jsii-runtime/package-lock.json
- packages/jsii-runtime/package.json
- packages/jsii-spec/package-lock.json
- packages/jsii-spec/package.json
- packages/jsii/package-lock.json
- packages/jsii/package.json
- packages/oo-ascii-tree/package-lock.json
- packages/oo-ascii-tree/package.json
> chore: Upgrade to latest typescript

- packages/jsii-python-runtime/src/jsii/_kernel/providers/base.py
> fix(build): fix python runtime BaseProvider signatures

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/1-bug.md
- .github/ISSUE_TEMPLATE/2-feature-request.md
- .github/ISSUE_TEMPLATE/3-question.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Add new issue templates for :bug: bugs, :rocket: feature requests, and
:question: questions. Edit PR template to express desire to track issues
and provide some hints as to how to properly document a PR's purpose.
Some updates to the `CONTRIBUTING.md` file as well, but this is only
a first step as this needs quite a bit more work (in a subsequent step).
---
> chore: update issue & PR templates

- .github/ISSUE_TEMPLATE/1-bug.md
- .github/ISSUE_TEMPLATE/2-feature-request.md
- .github/ISSUE_TEMPLATE/3-question.md
> chore: correct issue templates front matters

- .travis.yml
- CONTRIBUTING.md
- install.sh
- packages/jsii-java-runtime-test/package.json
- packages/jsii-java-runtime/package.json
- packages/jsii-ruby-runtime/project/Gemfile
- packages/jsii-ruby-runtime/project/Gemfile.lock
- packages/jsii-ruby-runtime/project/jsii_runtime.gemspec
- packages/jsii-ruby-runtime/project/test/jsii_runtime_test.rb
- packages/jsii-ruby-runtime/project/test/suite.rb
- packages/jsii-runtime/package-lock.json
- packages/jsii-spec/package-lock.json
- packages/jsii/package-lock.json
- superchain/Dockerfile
- superchain/README.md
- superchain/dockerd-entrypoint.sh
- superchain/m2-settings.xml
- superchain/ssh_config
Also make sure that jsii itself can be built within the jsii/superchain image,
which implies some updates to how the ruby runtime is configured and tested.
---
> chore: add jsii/superchain image definition

- packages/jsii-ruby-runtime/project/jsii_runtime.gemspec
> chore: simplify gemspec and add data

- .travis.yml
- buildspec.yaml
- packages/jsii-diff/package-lock.json
- packages/jsii-pacmak/package-lock.json
- packages/jsii-reflect/package-lock.json
- packages/jsii/package-lock.json
- packages/oo-ascii-tree/package-lock.json
This protects against validating builds that modify the source tree, as
is generally an indication that something was missed out when the PR
was produced.
---
> chore(ci): make TravisCI check for unexpected source changes

- .github/ISSUE_TEMPLATE/3-question.md
> docs: replace "question" with "guidance"

- .github/ISSUE_TEMPLATE/3-guidance.md
> chore: fix search URL in guidance tempalte

- .github/CODEOWNERS
- README.md
- docs/assembly.md
- docs/configuration.md
- packages/jsii/lib/project-info.ts
- packages/jsii/lib/utils.ts
- packages/jsii/test/test.utils.ts
Running through the `README.md` file to dust if off and try to improve
it ever so slightly.
---
> docs: improvements to the README.md

- superchain/Dockerfile
By grouping all the LABEL instructions in a single one.
---
> chore: reduce layer count in superchain image

- .gitignore
- package-lock.json
- packages/codemaker/package-lock.json
- packages/jsii-build-tools/package-lock.json
- packages/jsii-diff/package-lock.json
- packages/jsii-dotnet-jsonmodel/package-lock.json
- packages/jsii-dotnet-runtime-test/package-lock.json
- packages/jsii-dotnet-runtime/package-lock.json
- packages/jsii-java-runtime/package-lock.json
- packages/jsii-kernel/package-lock.json
- packages/jsii-pacmak/package-lock.json
- packages/jsii-reflect/package-lock.json
- packages/jsii-ruby-runtime/package-lock.json
- packages/jsii-runtime/package-lock.json
- packages/jsii-spec/package-lock.json
- packages/jsii/package-lock.json
- packages/oo-ascii-tree/package-lock.json
Windows installation test has been failing with an odd error since the
shrinkwrap commit was introduced. Attempting to un-do this as a way to
confirm this is indeed what was causing problems.
---
> chore: revert shrinkwrap, as it seems to break Windows

- .mergify.yml
Do not operate on pull requests that were created by `dependabot`, and
try to make sure friendly messaging is emitted only once.
---
> chore: tweak Mergify configuration

- .mergify.yml
> chore(mergify): de-duplicate merge action

- superchain/Dockerfile
> feat(superchain): bundle which in the Docker image

- .mergify.yml
> chore: stop the mergify label dance

- .mergify.yml
> chore: stop mergify from discarding dependabot reviews

- .mergify.yml
> chore: fix CodeBuild project name in mergify configuration

- .mergify.yml
> chore: do not discard approvals on PRs authored by team members

- README.md
- docs/typescript-restrictions.md
- packages/jsii/lib/reserved-words.ts
- scripts/list-reserved-words.ts
> chore(doc): start documenting restrictions over vanilla TypeScript

- README.md
> docs: spelling correction in README.md

- packages/codemaker/package-lock.json
- packages/jsii-build-tools/package-lock.json
- packages/jsii-calc-base-of-base/package-lock.json
- packages/jsii-calc-base/package-lock.json
- packages/jsii-calc-bundled/package-lock.json
- packages/jsii-calc-lib/package-lock.json
- packages/jsii-calc/package-lock.json
- packages/jsii-diff/package-lock.json
- packages/jsii-dotnet-analyzers/package-lock.json
- packages/jsii-dotnet-jsonmodel/package-lock.json
- packages/jsii-dotnet-runtime-test/package-lock.json
- packages/jsii-dotnet-runtime/package-lock.json
- packages/jsii-java-runtime-test/package-lock.json
- packages/jsii-java-runtime/package-lock.json
- packages/jsii-kernel/package-lock.json
- packages/jsii-pacmak/package-lock.json
- packages/jsii-python-runtime/package-lock.json
- packages/jsii-reflect/package-lock.json
- packages/jsii-ruby-runtime/package-lock.json
- packages/jsii-runtime/package-lock.json
- packages/jsii-spec/package-lock.json
- packages/jsii/package-lock.json
- packages/oo-ascii-tree/package-lock.json
> chore: update package-lock.json files with new version

- packages/jsii-calc-base-of-base/package-lock.json
- packages/jsii-calc-base/package-lock.json
- packages/jsii-calc-lib/package-lock.json
- packages/jsii-calc/package-lock.json
- packages/jsii-diff/package-lock.json
- packages/jsii-dotnet-runtime-test/package-lock.json
- packages/jsii-dotnet-runtime/package-lock.json
- packages/jsii-java-runtime-test/package-lock.json
- packages/jsii-java-runtime/package-lock.json
- packages/jsii-kernel/package-lock.json
- packages/jsii-pacmak/package-lock.json
- packages/jsii-reflect/package-lock.json
- packages/jsii-ruby-runtime/package-lock.json
- packages/jsii-runtime/package-lock.json
- packages/jsii-sampiler/package-lock.json
- packages/jsii-spec/package-lock.json
- packages/jsii/package-lock.json
- packages/oo-ascii-tree/package-lock.json
> chore: clean up lock files

- .yarnrc
- yarn.lock
- Make `yarn install` check integrity of installed files
- Add audit information to output of `yarn install`
---
> chore: make yarn configuration safer

- packages/jsii-calc/lib/calculator.ts
- packages/jsii-calc/test/assembly.jsii
- packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
- packages/jsii-pacmak/lib/targets/java.ts
- packages/jsii-pacmak/lib/targets/python.ts
- packages/jsii-pacmak/lib/util.ts
- packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/IFriendly.java
- packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/IThreeLevelsInterface.java
- packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
- packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Calculator.cs
- packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ClassWithDocs.cs
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/AllTypes.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/AsyncVirtualMethods.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Calculator.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ClassWithDocs.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConsumerCanRingBell.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Demonstrate982.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DisappointingCollectionSource.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DocumentedClass.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/EraseUndefinedHashValues.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/LoadBalancedFargateServiceProps.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/RootStruct.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SingleInstanceTwoTypes.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SingletonInt.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SingletonString.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/StaticContext.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SupportsNiceJavaBuilderProps.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/VoidCallback.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/package-info.java
- packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
Fix minor formatting issues.
---
> chore: add missing translation disclaimers for Java and C#

- .dependabot/config.yml
- packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
- packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
> chore(deps): update Microsoft.Extensions.Logging.* dependencies

- packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
> chore(deps): update Microsoft.Extensions.DependencyInjection to 3.0.1

- .dependabot/config.yml
This reverts commit a9477e8da4a731346a015cd670ee98c2eb8adfae.
---
> Revert "chore: further simplify dependabot configuration"

- packages/@jsii/java-runtime-test/pom.xml.t.js
- packages/@jsii/java-runtime/pom.xml.t.js
- packages/jsii-pacmak/lib/targets/java.ts
- packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/java/pom.xml
- packages/jsii-pacmak/test/expected.jsii-calc-base/java/pom.xml
- packages/jsii-pacmak/test/expected.jsii-calc-lib/java/pom.xml
- packages/jsii-pacmak/test/expected.jsii-calc/java/pom.xml
> chore(java): upgrade dependencies of generated code

- packages/jsii/lib/assembler.ts
> fix: edit typo in diagnostic message.

- CONTRIBUTING.md
> docs: add information about jsii/superchain releasing

- .mergify.yml
If a PR is labeled with "no-squash" this will perform a merge without squashing.
---
> chore(mergify): no-squash label

- .github/workflows/dependabot.yml
> chore: add auto-approver for Depndabot PRs

- packages/jsii/lib/compiler.ts
> chore: fix comment typo

- .dependabot/config.yml
- .yarnrc
- package.json
- packages/@jsii/integ-test/test/build-cdk.test.ts
- yarn.lock
> chore: ran 'yarn upgrade'

- CHANGELOG.md
- lerna.json
- packages/jsii-pacmak/lib/targets/version-utils.ts
- packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId.csproj
- packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId.csproj
- packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon.JSII.Tests.CalculatorPackageId.csproj
- packages/jsii-pacmak/test/targets/version-utils.test.ts
> chore(release): 1.3.1

- .gitignore
- docs/assembly.md
- docs/configuration.md
- docs/handbooks/language-implementation.md
- docs/runtime-architecture.md
- docs/specifications/1-introduction.md
- docs/specifications/2-type-system.md
- docs/specifications/3-kernel-api.md
- docs/specifications/4-standard-compliance-suite.md
- docs/specifications/5-new-language-intake.md
- docs/typescript-restrictions.md
> docs(spec): fix typos

- packages/@jsii/python-runtime/bin/generate
- packages/@jsii/python-runtime/package.json
- packages/@jsii/python-runtime/setup.py
feat(python): improve metadata of jsii package (#1587)
Add references to the GitHub repository, etc... in order to improve the
detail page experience on https://pypi.org/project/jsii/. Interestingly,
we already produce some of these metadata entries (where relevant) in
the packages generated by `jsii-pacmak` but failed to include those in
the runtime library's package descriptor.
---
> feat(python): improve metadata of jsii package

- docs/runtime-architecture.md
docs: fixed SDTIN on docs/runtime-architecture.md (#1643)
Fixes #1642 
---
> docs: fixed SDTIN on docs/runtime-architecture.md

- packages/jsii-pacmak/lib/targets/java.ts
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJacksonStruct.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DerivedStruct.java
- packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/NullShouldBeTreatedAsUndefinedData.java
Reverts aws/jsii#1653
Reverting this change temporarily to unblock the pipeline
> Revert "feat(java): use covariant types for collection elements"

- docs/configuration.md
Just some stuff that stick into my eye while reading through :)
---
> docs: 👮 Typo police

- README.md
Add a table with all the tools in the toolchain, a short description and stability index
---
> chore: toolchain table in readme

- .gitignore
- scripts/fetch-dotnet-snk.sh
> chore: remove dependency on jq for fetch-dotnet-snk.sh

- packages/@jsii/integ-test/package.json
- packages/@jsii/kernel/package.json
- packages/codemaker/package.json
- packages/jsii-diff/package.json
- packages/jsii-pacmak/package.json
- packages/jsii-reflect/package.json
- packages/jsii-rosetta/package.json
- packages/jsii/package.json
- yarn.lock
> chore: yarn upgrade

- .github/workflows/main.yml
- .versionrc.json
- packages/@jsii/java-runtime-test/package.json
- packages/@jsii/kernel/test/kernel.test.ts
- packages/@jsii/python-runtime/package.json
- packages/codemaker/test/filebuff.test.ts
- packages/codemaker/test/source.test.ts
- packages/jsii-rosetta/lib/commands/extract.ts
- packages/jsii/lib/assembler.ts
- packages/jsii/lib/project-info.ts
This attempts to provide a build-and-validate workflow for PR
validations, so that contributors can obtain real-time feedback about
their PRs as they are being validated.
---
> chore: comprehensive build-and-validate workflow

- .github/workflows/main.yml
- .mergify/config.yml
Reproduces the script at https://github.com/aws/cdk-ops/blob/master/integration-tests/jsii/integ/test.sh
---
> chore: run integration tests as part of workflow

- .github/workflows/main.yml
- .github/workflows/superchain.yml
- superchain/Dockerfile
> chore: add workflow to validate jsii/superchain image

- packages/jsii-pacmak/lib/targets/golang/types/struct.ts
- packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
> chore: fix interface generation for datatypes

- packages/jsii-pacmak/lib/targets/golang/types/class.ts
- packages/jsii-pacmak/lib/targets/golang/types/go-type-reference.ts
- packages/jsii-pacmak/lib/targets/golang/types/go-type.ts
- packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
Also renames a few of the emit methods to be more descriptive.
---
> chore(go): generate constructors for GoClass

- packages/jsii-pacmak/lib/targets/golang/types/go-type.ts
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
> chore: fix Property#emitSetterDecl

- packages/@jsii/python-runtime/src/jsii/__meta__.py
- packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
- packages/@jsii/python-runtime/src/jsii/_kernel/providers/__init__.py
- packages/@jsii/python-runtime/src/jsii/_kernel/providers/base.py
- packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
> chore: use relative imports in the Python runtime

- packages/@jsii/go-runtime/jsii-experimental/api.go
- packages/@jsii/go-runtime/jsii-experimental/client.go
> chore: kernel API type translations

- packages/jsii-pacmak/lib/targets/go.ts
- packages/jsii-pacmak/lib/targets/python.ts
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Closes https://github.com/aws/jsii/issues/2008
---
> chore(go): generate module embedding

- packages/jsii-pacmak/lib/targets/go/package.ts
- packages/jsii-pacmak/lib/targets/go/types/class.ts
- packages/jsii-pacmak/lib/targets/go/types/go-type.ts
- packages/jsii-pacmak/lib/targets/go/types/interface.ts
- packages/jsii-pacmak/lib/targets/go/types/type-member.ts
- packages/jsii-pacmak/lib/targets/go/util.ts
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Also correctly emit method parameters
---
> chore(go): correctly generate statics

- packages/@jsii/java-runtime/pom.xml.t.js
> chore(java): mockito 3.5.13

- packages/@jsii/java-runtime/pom.xml.t.js
> chore(java): maven-surefire-plugin 3.0.0-M5

- packages/@jsii/java-runtime/pom.xml.t.js
> chore(java): use Jackson 2.11.3

- .github/workflows/main.yml
> chore(tests/dotnet): update tests to .NET 5.0.0-rc2

- .github/workflows/main.yml
> chore: attempt to increase node VM heap in integ test

- packages/jsii-calc/lib/compliance.ts
- packages/jsii-calc/lib/submodule/index.ts
- packages/jsii-calc/lib/submodule/my-class.ts
- packages/jsii-calc/lib/submodule/param/index.ts
- packages/jsii-calc/lib/submodule/returns-param/index.ts
- packages/jsii-calc/test/assembly.jsii
- packages/jsii-pacmak/lib/targets/go/package.ts
- packages/jsii-pacmak/lib/targets/go/types/class.ts
- packages/jsii-pacmak/lib/targets/go/types/enum.ts
- packages/jsii-pacmak/lib/targets/go/types/go-type.ts
- packages/jsii-pacmak/lib/targets/go/types/interface.ts
- packages/jsii-pacmak/lib/targets/go/types/struct.ts
- packages/jsii-pacmak/lib/targets/go/types/type-member.ts
- packages/jsii-pacmak/lib/targets/go/util.ts
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
- packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
- packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Fixes https://github.com/aws/jsii/issues/2042
---
> chore: add parameter dependencies

- .mergify/config.yml
> chore: enable mergify smart+fasttrack

- docs/assembly.md
- docs/configuration.md
- docs/specifications/3-kernel-api.md
- docs/whitepapers/callbacks.md
> chore(docs): fix typos

- .github/workflows/dependabot.yml
- .github/workflows/docker-images.yml
- .github/workflows/main.yml
- .mergify/config.yml
- CONTRIBUTING.md
- README.md
- docs/assembly.md
- docs/configuration.md
- docs/specifications/1-introduction.md
- packages/@jsii/kernel/README.md
- packages/@jsii/runtime/README.md
- packages/jsii-pacmak/README.md
- packages/jsii-reflect/test/independent.test.ts
- superchain/Dockerfile
> chore: rename master to main in docs

- CHANGELOG.md
- lerna.json
- packages/@jsii/python-runtime/setup.py
> chore(release): 1.14.1

- packages/@jsii/go-runtime/go.mod
- packages/@jsii/go-runtime/jsii-experimental/go.mod
- packages/@jsii/go-runtime/package.json
- packages/@jsii/spec/lib/assembly.ts
- packages/jsii-pacmak/lib/targets/go/package.ts
- packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
- packages/jsii-reflect/lib/assembly.ts
> feat(go): generate go.mod files

- packages/@jsii/go-runtime/jsii-experimental/runtime.go
Renaming some args in go runtime as suggested in https://github.com/aws/jsii/pull/2257.
---
> chore: go runtime renaming

- docs/typescript-restrictions.md
- packages/jsii/lib/reserved-words.ts
> chore: add go reserved words

- gh-pages/content/home/runtime-architecture.md
> docs: remove spurrious word

- gh-pages/content/home/features.md
> docs: fix typo in features.md

- gh-pages/content/dev-guide/index.md
> docs: correct spelling of traditional

- packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
> fix(python): ValueError: write to closed file

- packages/@jsii/runtime/test/playback.test.ts
We are seeing sporadic timeouts on Windows
---
> chore: increase test timeout to 5 minutes

- packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/AssemblyInfo.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Helpers/DiagnosticResult.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Verifiers/DiagnosticVerifier.Helper.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Verifiers/DiagnosticVerifier.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers/AssemblyInfo.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.JsonModel/AssemblyInfo.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/AssemblyInfo.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Client/ClientTests.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Deputy/Converters/FrameworkToJsiiConverterTests.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Deputy/Converters/JsiiToFrameworkConverterTests.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Deputy/DeputyBaseTests.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/AssemblyTests.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/ClassTypeTests.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/CollectionKindTests.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/CollectionTypeReferenceTests.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/DocsTests.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/EnumMemberTests.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/TestUtils.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/AssemblyInfo.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Api/Response/NamingResponse.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Converters/TypeConverter.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/FileSystem/FileSystem.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Spec/DependencyRoot.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/ValueConverter.cs
- packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs
Largely, by disabling the analyzers. Is this cheating? I guess it is.
But I'm cool with that.
---
> chore(dotnet): correct all .NET Code Analyzer Errors

- .github/ISSUE_TEMPLATE/1-bug.md
- .github/ISSUE_TEMPLATE/2-feature-request.md
- .github/ISSUE_TEMPLATE/3-guidance.md
> chore: add "go" to issue templates

- packages/jsii-rosetta/lib/markdown/xml-comment-renderer.ts
In some cases, an `xmldom` error would occur when trying to render C#
XML-style documentation blocks, where inline html within a Markdown
document is not valid as far as the `xmldom` parser is considered. This
introduces a safer fall-back strategy.
---
> fix(pacmak): xmldom error when generating packages

- packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
Seems to be related to https://github.com/aws/jsii/pull/2705
---
> chore(go): Update snapshots

- .github/workflows/auto-approve.yml
- packages/jsii-pacmak/lib/index.ts
- packages/jsii-pacmak/lib/targets/go.ts
- packages/jsii-pacmak/lib/timer.ts
- packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
- packages/jsii-pacmak/test/generated-code/target-python.test.ts
> fix(pacmak): go code generation sometimes fails on Windows

- superchain/Dockerfile
- superchain/README.md
Adds GitHub CLI to superchain.
---
> feat(superchain): add github cli

- .mergify/config.yml
> chore: add madeline-k to .mergify/config.yml

- .mergify/config.yml
> chore(mergify): add @BenChaimberg to team roster

- .github/workflows/yarn-upgrade.yml
> chore: disable the auto upgrade workflow

- packages/jsii-config/README.md
> docs: fix broken links

- .github/ISSUE_TEMPLATE/2-feature-request.md
> chore: fix typo

- .github/workflows/main.yml
> chore: test against .NET 6 (prerelease)

- .mergify/config.yml
> chore(mergify): add @comcalvi to team roster

- .mergify/config.yml
Add kaizen3031593 to `.mergify/config.yml`.
---
> chore(mergify): add kaizen3031593 to config file

- .mergify/config.yml
> chore(mergify): add Chriscbr to team members

- gh-pages/content/specification/2-type-system.md
> docs: fix typo in 2-type-system.md

- buildspec.yaml
> chore: stop installing gcc (it is already there)

- gh-pages/content/overview/runtime-architecture.md
> fix: typo in documentation

- .github/workflows/auto-approve.yml
See https://github.com/aws/aws-cdk/pull/16777#issue-748759529
---
> chore: auto approve dependabot

- .github/workflows/auto-approve.yml
- .github/workflows/pr-labeler.yml
Complementary of https://github.com/aws/aws-cdk/pull/17264
Related to https://github.com/cdklabs/cdk-ops/pull/1759
---
> chore: simplify auto approve mechanism

- CHANGELOG.md
- lerna.json
- packages/jsii/lib/transforms/deprecation-warnings.ts
- packages/jsii/test/deprecation-warnings.test.ts
> chore(release): 1.44.2

- packages/@jsii/Directory.Build.targets
This reverts commit 30281c9523e5d7de885fee1b52555457bbdadb61.
---
> revert: bump Microsoft.Extensions.Logging.Console (#3137)

- packages/jsii/lib/transforms/deprecation-warnings.ts
- packages/jsii/test/deprecation-warnings.test.ts
> fix(jsii): deprecation message is not displayed for deprecated classes

- packages/jsii/lib/assembler.ts
Unfortunately I cannot reproduce this problem locally, so I'm testing
fixes on the pipeline 😭.
---
> chore(jsii): follow-up to the previous fix

- packages/jsii-pacmak/lib/dependency-graph.ts
- packages/jsii-pacmak/lib/npm-modules.ts
- packages/jsii-pacmak/lib/util.ts
- packages/jsii-reflect/lib/type-system.ts
- packages/jsii-reflect/lib/util.ts
Still testing in the pipeline... :/
---
> chore(pacmak, reflect): punycode messes us up in more places

- packages/jsii/test/submodules.test.ts
Add more tests on importing types in various flavours and referencing
types in various positions to convince myself that it actually works.
---
> chore(jsii): more tests on importing

- packages/jsii/bin/jsii.ts
When the output is not a terminal, color codes get in the way. They
lead to unreadable logging like this:
```
monocdk: ^[[96mlib/aws-apigateway/lib/domain-name.ts^[[0m:^[[93m114^[[0m:^[[93m19^[[0m - ^[[93mwarning^[[0m^[[90m JSII5019: ^[[0mThe property name "domainName" conflicts with the declaring class "DomainName". This will result in renaming the class to "_DomainName" in C#. Consider renaming "domainName".
monocdk: [7m114[0m   public readonly domainName: string;
monocdk: [7m   [0m [93m                  ~~~~~~~~~~[0m
```
Don't output color codes if we detect the output is not a TTY.
---
> fix(jsii): color codes are logged to logfiles

- .github/workflows/auto-approve.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/yarn-upgrade.yml
See https://github.com/aws/aws-cdk/pull/18183
---
> chore: rename label for auto approvals

- packages/jsii-pacmak/lib/targets/go/types/type-member.ts
- packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
> feat(pacmak): go yaml struct tags

- CHANGELOG.md
- lerna.json
- packages/jsii-reflect/package.json
- packages/jsii/package.json
- yarn.lock
See [CHANGELOG](https://github.com/aws/jsii/blob/patch/v1.52.1/CHANGELOG.md)
---
> chore(release): 1.52.1

- gh-pages/content/user-guides/lib-user/language-specific/go.md
> docs(go): document UnsafeCast feature

- .mergify/config.yml
> chore(mergify): add TheRealAmazonKendra to mergify

- packages/jsii/lib/assembler.ts
Profiling showed that `findPackageInfo` was one of the top contributors
to compiler duration, as it was reading the same (large) files over and
over again. It also incurred additional GC churn (as those duplicated
large data blobs would need to be recclaimed).
This change adds a memoization map around this call to avoid re-reading
those files during a single compiler pass, which reduces GC overhead as
well as file IO overhead.
Additionally, replaced a few occurrences of `Record<string, T>` with
`Map<string, T>`, as those incur much less GC churn (in relation to
hidden classes).
---
> chore: cache the results of `findPackageInfo`

- packages/jsii/lib/utils.ts
> chore: fix typo in intended

- packages/jsii-calc/lib/compliance.ts
- packages/jsii-calc/test/assembly.jsii
- packages/jsii-pacmak/lib/targets/java.ts
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
- packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
- packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
> fix(jsii): `assert` not allowed as interface member

- .github/workflows/gh-pages.yml
> chore: use a venv to build github pages

- gh-pages/content/overview/features.md
- gh-pages/content/user-guides/lib-author/configuration/targets/go.md
- gh-pages/content/user-guides/lib-user/language-specific/go.md
> chore: remove Go dev preview from docs

- superchain/Dockerfile
> chore(superchain): update to Maven 3.8.6

- packages/jsii-pacmak/lib/targets/python.ts
inheritence -> inheritance
---
> chore(python): fix typo in python.ts

- .github/dependabot.yml
> chore: register missing go project with dependabot

- .mergify/config.yml
> chore: add mrgrain to mergify as core contributor

- .mergify/config.yml
> chore(mergify): add team members to contribution/core

- packages/jsii-pacmak/lib/targets/python/type-name.ts
> chore(python): fix typo in type-name.ts

- CHANGELOG.md
- lerna.json
- packages/jsii-pacmak/lib/targets/python.ts
- packages/jsii-pacmak/lib/targets/python/type-name.ts
> chore(release): v1.65.1 

- superchain/Dockerfile
> chore: update sudoers settings

- packages/jsii-reflect/lib/type-member.ts
> fix(jsii-reflect): TypeMember is not SourceLocatable

- .github/workflows/close-stale-issues.yml
Reverts aws/jsii#3867
Dependabot is really aggressive with this one 🤔
> revert(deps): Bump aws-actions/stale-issue-cleanup from 5 to 6

- .github/workflows/docker-images.yml
> chore: configure publishing container images to ECR Public

- .github/workflows/docker-images.yml
> chore: publish nightly images to ECR Public

- CONTRIBUTING.md
- README.md
- gh-pages/content/specification/5-new-language-intake.md
- gh-pages/content/user-guides/language-support/index.md
- superchain/Dockerfile
- superchain/README.md
- superchain/build-local.sh
> docs: refer to ECR Public image

- lerna.json
- package.json
- packages/jsii-rosetta/package.json
- yarn.lock
> chore: upgrade lerna to 7.0.x and migrate config

- .github/workflows/handle-stale-discussions.yml
> chore(github-actions): added stale discussion workflow

- gh-pages/content/overview/features.md
- gh-pages/content/specification/3-kernel-api.md
- gh-pages/content/user-guides/lib-author/.pages.yml
- gh-pages/content/user-guides/lib-author/hints.md
- gh-pages/content/user-guides/lib-author/typescript-restrictions.md
> chore(docs): documentation enhancements

- packages/@jsii/kernel/src/disk-cache/disk-cache.ts
- packages/@jsii/kernel/src/kernel.ts
- packages/@jsii/kernel/src/objects.ts
- packages/@jsii/kernel/src/serialization.test.ts
> chore(kernel): use ES private fields

- packages/jsii-diff/BREAKING_CHANGES.md
- packages/jsii-diff/README.md
This question comes up every other week. Let's make a single place to explain it.
---
> docs(jsii-diff): explain making properties optional

- .github/workflows/main.yml
- CONTRIBUTING.md
- gh-pages/content/user-guides/language-support/index.md
- gh-pages/content/user-guides/lib-author/configuration/targets/python.md
- gh-pages/content/user-guides/lib-author/index.md
- packages/@jsii/python-runtime/pyproject.toml
- packages/@jsii/python-runtime/setup.py
- packages/jsii-pacmak/lib/targets/python.ts
- packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
- packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
- packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
This reverts commit 087ff241bc852b49d91c79883e5faeaf5bb92f42.
---
> revert: "switch to python 3.8 (#4239)"

- superchain/README.md
> chore: update superchain README

- .mergify/config.yml
Add author paulhcs to contribution/core.
---
> chore: add author paulhcs to contribution/core

- gh-pages/content/compiler-and-rosetta-maintenance.md
After the RFC PR was merged, the branch doesn't exist.
---
> chore: updated link to rfc

- .mergify/config.yml
Remove madeline-k and MrArnoldPalmer
---
> chore: mergify config cleanup

- CHANGELOG.md
- lerna.json
- packages/@jsii/python-runtime/src/jsii/_runtime.py
- packages/@jsii/python-runtime/tests/test_python.py
See [CHANGELOG](https://github.com/aws/jsii/blob/patch/v1.103.1/CHANGELOG.md)
---
> chore(release): 1.103.1

- .mergify/config.yml
Instead of keeping this list up to data manually.
---
> chore: use team to label core team PRs

- docs/updating-go-version.md
> chore: instructions on how to update Go

- gh-pages/content/specification/2-type-system.md
> docs: describe type intersections in the jsii doc page
