aws/jsii

packages/jsii-ruby-runtime/project/.rubocop.yml
Currently, `npm run lint` fails because `rubolint` uses `2.1` as the default `TargetRubyVersion`, which does not match `s.required_ruby_version = '>= 2.2'` from `jsii_runtime.gemspec`. This changeset fixes that issue by specifying a `TargetRubyVersion` in `.rubocop.yml`.
=> Fix `npm run lint` for `jsii-ruby-runtime`.

packages/jsii-kernel/lib/kernel.ts
Use `os.tmpdir()` instead of `/tmp` when creating
the kernel installation and staging directories.
Fixes #183 
Fixes awslabs/aws-cdk#138
=> fix: kernel fails on Windows

packages/jsii-kernel/lib/kernel.ts
If `packageDir` is something like `so\neat`, then the code run by `_execute` will be `require("so\neat")`, which fails due to the escape sequence `\n`.
With this change, the code run by `_execute` will instead be ``require(String.raw`so\neat`)``.
=> Fix module loading on systems that use '\' instead of '/' as the path separator.

packages/jsii-pacmak/lib/targets/dotnet.ts
When `jsii-pacmak` looks for local dependencies, it looks in `dist/{targetname}`. But it places .NET artifacts directly in `dist/`. This change fixes that.
=> Output .NET build artifacts to dist/dotnet/ instead of just dist/.

packages/jsii/lib/compiler.ts, packages/jsii/package-lock.json, packages/jsii/test/negatives/neg.downgrade-to-readonly.ts
Fixes #199 that was discovered by @moofish32
=> Add check against downgrading proeprties to readonly

README.md, packages/jsii-dotnet-generator/src/Amazon.JSII.Generator.UnitTests/AssemblyExtensionsTests.cs, packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/AssemblyExtensions.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel.UnitTests/Spec/AssemblyTests.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Spec/AssemblyTargets.cs
The correct name for the MSBuild property containing the path to the `.snk` file is `AssemblyOriginatorKeyFile`, not `AssemblyOriginatorKey`.
=> Fix SNK property name.

packages/jsii-pacmak/lib/targets/dotnet.ts, packages/jsii-pacmak/test/expected.jsii-calc-base/sphinx/_scope_jsii-calc-base.rst, packages/jsii-pacmak/test/expected.jsii-calc-lib/sphinx/_scope_jsii-calc-lib.rst, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst
This code generates the reference documentation for dotnet (C#). It includes how to add a reference to the package, and how to import the references into your code. Expected files for diff testing have been updated.
=> Feature: Add dotnet reference docs

packages/jsii/.npmignore, packages/jsii/package.json
1. npmignore excluded all files
2. README was not copied from root
=> fix(jsii): add readme and restore missing files in jsii tarball

packages/jsii-dotnet-generator/src/Amazon.JSII.Generator.UnitTests/AssemblyGeneratorTests.cs, packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/AssemblyGenerator.cs, packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/Amazon/JSII/Tests/CalculatorNamespace/BaseNamespace/Internal/DependencyResolution/Anchor.cs, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Internal/DependencyResolution/Anchor.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Internal/DependencyResolution/Anchor.cs, packages/jsii-runtime/package-lock.json
When a NuGet package is restored, all of its listed dependencies are restored (whether or not they are actually used). But when a .NET assembly is built, if it does not reference any .NET types from the dependency, the compiled .NET assembly will not reference the dependency .NET assembly.
At runtime, `jsii-dotnet-runtime` loads JSII dependencies by looking through the .NET assembly's references. If the dependency does not appear in references, it won't be found.
This breaks the following scenario:
* A JSII assembly `my-package` depends on `my-dependency`.
* In the TypeScript source, `my-package` requires symbols from `my-dependency`. Therefore the NuGet package `MyPackage` lists `MyDependency` as a dependency.
* However, the generated .NET source for `MyPackage` does not reference any …
=> Force generated assemblies to reference jsii-only dependencies.

packages/jsii/lib/assembler.ts, packages/jsii/test/negatives/neg.deref-error.ts
In some cases, when a type could not be referenced, the diagnostic 
message doesn't indicate that (the undefined return value will still 
cause an error, but we also want to know that we couldn't deref the 
type)
=> Fix #221: improve diagnostics when dereference fails

README.md, packages/jsii-calc/README.md, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/sphinx.ts, packages/jsii-pacmak/test/expected.jsii-calc-base/sphinx/_scope_jsii-calc-base.rst, packages/jsii-pacmak/test/expected.jsii-calc-lib/sphinx/_scope_jsii-calc-lib.rst, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/_jsii-calc.README.md, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst
* Fix #228: allow readme file to define sphinx topic header
* Fix #185: move multi-language tabs after readme
* Update README
=> Sphinx improvements

packages/jsii-pacmak/lib/targets/sphinx.ts, packages/jsii-pacmak/test/expected.jsii-calc-base/sphinx/_scope_jsii-calc-base.rst, packages/jsii-pacmak/test/expected.jsii-calc-lib/sphinx/_scope_jsii-calc-lib.rst, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst
When rendering a type reference link, the trailing backtick must be followed by
a non-word character; however the code generated array and union references that
followed this backtick directly with `[` or `)` respectively. This caused a lot
of warnings to be emitted by `sphinx-build`, and resulted in incorrect output.
This adds an escaped space (`\ `) after the backticks, which `sphinx-build`
correctly interprets as a non-word character, but results in no character being
emitted to the output - thus generating the desired output.
=> fix: Sphinx generated incorrect type references for display

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DefaultedConstructorArgument.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/OptionalConstructorArgument.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/RuntimeTypeChecking.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DefaultedConstructorArgument.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/OptionalConstructorArgument.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/RuntimeTypeChecking.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii/lib/assembler.ts
Parameters with a default value were not represented as optional in the assembly
documents due to an oversight when re-writing `jsii`. There was also no coverage
in the test corpus for this use-case, so I've added some.
Fixes #233
=> fix(jsii): Defaulted parameters were not rendered as optional

packages/jsii-calc-base/test/assembly.jsii, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/Amazon/JSII/Tests/CalculatorNamespace/BaseNamespace/Base.cs, packages/jsii-pacmak/test/expected.jsii-calc-base/java/src/main/java/software/amazon/jsii/tests/calculator/base/Base.java, packages/jsii-pacmak/test/expected.jsii-calc-base/sphinx/_scope_jsii-calc-base.rst, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/AllTypes.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DerivedStruct.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DerivedStructProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IDerivedStruct.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/RuntimeTypeChecking.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/UseBundledDependency.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/AllTypes.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DerivedStruct.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/RuntimeTypeChecking.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/UseBundledDependency.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii/lib/assembler.ts
Optional parameters and properties typed `any` would be represented as
required, despite the code unambiguously suggests the opposite. This is
due to the fact that `any` implicitly covers `null` and `undefined`.
This change fixes this by adding a specific provision for the question
mark token in the declarations of those, and adds compliance test
coverage for the same.
Fixes #230
=> fix(jsii): Optional `any` represented as required

packages/jsii/lib/compiler.ts
In watch mode, users expect to be able to be a little more drafty than when doing a plain compile cycle, as
they may edit code as part of a troubleshooting loop, that may involve for example leaving out unused
imports and the like. This change makes sure the `noEmitOnError` compiler option is set to false when
operating in `watch` mode, so the `.js` files get updated unconditionally.
Fixes #235
=> fix(jsii): Don't skip emit on TS errors when in "watch" mode

packages/jsii-pacmak/bin/jsii-pacmak.ts, packages/jsii-pacmak/lib/targets/sphinx.ts, packages/jsii-pacmak/test/expected.jsii-calc-base/sphinx/_scope_jsii-calc-base.rst, packages/jsii-pacmak/test/expected.jsii-calc-lib/sphinx/_scope_jsii-calc-lib.rst, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst
Add a documentation line outlining the parent declaration of overridden
members as well as inherited members that are not overridden locally.
This should make browsing the documentation a lot nicer.
Inherited and overridden statements in the documentation always refer to
the fully qualified name of the super statement.
Fixes #196
=> feat: Document overriden/inherited members

packages/jsii-runtime/lib/sync-stdio.ts
Guidance from https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/
=> fix(jsii-runtime): Use buffer factory methods instead of constructor.

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-kernel/lib/kernel.ts, packages/jsii-kernel/test/test.kernel.ts, packages/jsii-kernel/tsconfig.json, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ClassWithMutableObjectLiteralProperty.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IMutableObjectLiteral.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/MutableObjectLiteral.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/MutableObjectLiteralProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ClassWithMutableObjectLiteralProperty.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/MutableObjectLiteral.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-runtime/package-lock.json, packages/jsii-runtime/package.json, packages/jsii-runtime/webpack.config.js
Use the javascript `Proxy` class to coalesce object literals to an
interface type, allowing them to be returned by reference instead of by
value.
Introduces a test in the `jsii-kernel` to demonstrate the feature works
as intended.
Fixes #248
Fixes awslabs/aws-cdk#774
=> fix(kernel): Return object literals as references

package-lock.json, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java, packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiEngine.java, packages/jsii-kernel/lib/kernel.ts, packages/jsii-kernel/test/test.kernel.ts, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DoNotOverridePrivates.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DoNotOverridePrivates.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst
jsii-kernel will ignore override requests for methods/properties that
resolve on the object but are not defined in the public API of the
type.
java runtime will not request overrides for methods/properties that
use "private" accessibility.
Fixes #244
=>  fix(kernel + java): skip overrides of private methods/properties

packages/jsii/lib/validator.ts, packages/jsii/test/negatives/neg.method-name.1.ts, packages/jsii/test/negatives/neg.method-name.2.ts, packages/jsii/test/negatives/neg.property-name.1.ts, packages/jsii/test/negatives/neg.property-name.2.ts, packages/jsii/test/negatives/neg.static-method-name.1.ts, packages/jsii/test/negatives/neg.static-method-name.ts, packages/jsii/test/negatives/neg.static-prop-name.1.ts, packages/jsii/test/negatives/neg.static-prop-name.2.ts
Add a 'non-const' qualifier to indicate that you probably forgot
to add 'const' on your 'public static' properties.
=> chore: make error message about statics more descriptive

packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/SymbolMap.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/UseCalcBase.cs
Use fully-qualified types in return values when there is a conflict.
Fixes #252
=> fix(jsii-dotnet-generator): Use FQ type returns in conflict.

packages/jsii/lib/compiler.ts
Revert to use default jsx compiler options as there is no
need to be opinionated about it. This is a left over from
our desire to support JSX in the CDK, which is now being
removed (awslabs/aws-cdk#830).
=> fix(jsii): use default jsx compiler options

packages/jsii-dotnet-generator/src/Amazon.JSII.Generator.UnitTests/Class/ClassGeneratorTests.cs, packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/Class/ClassGenerator.cs, packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/MethodExtensions.cs, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ClassWithPrivateConstructorAndAutomaticProperties.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ClassWithPrivateConstructorAndAutomaticProperties.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst
=> fix(jsii-dotnet-generator): Allow private constructors.

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IIInterfaceThatShouldNotBeADataType.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IIInterfaceWithMethods.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IInterfaceThatShouldNotBeADataTypeProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IInterfaceWithMethodsProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/IInterfaceThatShouldNotBeADataType.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/IInterfaceWithMethods.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii/lib/assembler.ts
If an interface inherits from a non-datatype interface, it should no
longer be classified as a datatype interface itself.
Making this change requires that information about the base classes
has already been determined, so I introduced an ordering mechanism
for 'deferred's.
Fixes #264.
=> fix(jsii): use base interfaces for 'datatype' property

fetch-dotnet-snk.sh, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Api/Request/CompleteRequest.cs, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/CallbackExtensions.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
The response for a callback completion that resulted in an error should use the `err` field
name and not the `error` field name as was initially done. Additionally, the program flow
did not propagate all errors back to the `jsii-kernel`, causing false-pass on the compliance
test suite, as expectations were incorrectly set up to expect `RuntimeException` instead
of `JsiiException`.
Fixes #285
=> fix(dotnet/runtime): Incorrect callback response format

packages/jsii-calc-lib/lib/index.ts, packages/jsii-calc-lib/test/assembly.jsii, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/CallbackExtensions.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/FrameworkToJsiiConverter.cs, packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/IDoublableProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/IIDoublable.cs, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Number.cs, packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/IDoublable.java, packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/Number.java, packages/jsii-pacmak/test/expected.jsii-calc-lib/sphinx/_scope_jsii-calc-lib.rst, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/AllTypes.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IIReturnsNumber.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IReturnsNumberProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/AllTypes.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/IReturnsNumber.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii/lib/assembler.ts, packages/jsii/lib/compiler.ts
The `jsii` compiler incorrectly mapped types homonym with a standard
type (`String`, `Number`, ...) to the primitive type on usage sites.
This commit corrects this behavior and adjusts the C# tests accordingly.
Additionally, when the return type of a callback was an interface, the
C# runtime was unable to determine the correct JSII type to use, despite
it has the information on the type of the callback method available. The
resolution behavior has also been fixes, as well as a couple of other
glitches that became apparent as a result of the `Number` type starting
to be correctly represented as the `@scope/jsii-calc-lib.Number` type.
Fixes #290
Fixes awslabs/aws-cdk#1027
=> fix(runtime/dotnet): Correct a number of type mappings

packages/jsii-calc-base/test/assembly.jsii, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-java-runtime-test/project/.gitignore, packages/jsii-java-runtime/project/.gitignore, packages/jsii-pacmak/test/.gitignore, packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/Amazon/JSII/Tests/CalculatorNamespace/BaseNamespace/Base.cs, packages/jsii-pacmak/test/expected.jsii-calc-base/java/src/main/java/software/amazon/jsii/tests/calculator/base/Base.java, packages/jsii-pacmak/test/expected.jsii-calc-base/sphinx/_scope_jsii-calc-base.rst, packages/jsii-pacmak/test/expected.jsii-calc-lib/sphinx/_scope_jsii-calc-lib.rst, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/AllTypes.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DoNotRecognizeAnyAsOptional.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/UseBundledDependency.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/AllTypes.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DoNotRecognizeAnyAsOptional.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/UseBundledDependency.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii/lib/assembler.ts
We accidentally marked every "any" and "unknown" types as optional,
regardless if the declaration had a question mark or not.
Fixes #284
=> fix(jsii): do not mark "any" or "unknown" as optional (unless "?")

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/sphinx.ts, packages/jsii-pacmak/test/expected.jsii-calc-base/sphinx/_scope_jsii-calc-base.rst, packages/jsii-pacmak/test/expected.jsii-calc-lib/sphinx/_scope_jsii-calc-lib.rst, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DefaultedConstructorArgument.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ILoadBalancedFargateServiceProps.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/LoadBalancedFargateServiceProps.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/LoadBalancedFargateServicePropsProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/RuntimeTypeChecking.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DefaultedConstructorArgument.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/LoadBalancedFargateServiceProps.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/RuntimeTypeChecking.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii/lib/assembler.ts, packages/jsii/test/negatives/neg.non-optional-after-optional-ctor.ts, packages/jsii/test/negatives/neg.non-optional-after-optional-method.ts
Fixes #301: reject non-optional arguments after optional arguments
Fixes #298: show default values for optional properties
Fixes #302: omit "abstract" from interface properties (they are by definition abstract)
Fixes #300: indicate optionals with "optional" instead of "or undefined"
Fixes #299: render multiple jsdoc lines as multiple lines in sphinx
=> fix(docs): improve docs rendering

packages/jsii/lib/assembler.ts, packages/jsii/lib/project-info.ts
1) ProjectInfo was verifying that the specified version range in
peerDependencies is exactly the same as the version range in regular
dependencies. This is not necessary, the only requirement is that
the actual concrete dependency version satisfies the peer dependency
version (which is already checked in _loadDependencies).
2) Assembler was verifying that the concrete version of a library found
in dependencies was the same as that same concrete library found in
peerDependencies. But since there's ever only one concrete copy of
any dependency, this check can never fail.
=> fix: remove overly strict checks on peer versions

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DontComplainAboutVariadicAfterOptional.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DontComplainAboutVariadicAfterOptional.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii/lib/assembler.ts
The following type signature is valid:
function(optional?: string, ...args: string[])
The function can be called with anywhere from 0-infinity arguments.
=> fix: accept variadic arguments after optional arguments

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/FrameworkToJsiiConverter.cs, packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/GreetingAugmenter.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/GreetingAugmenter.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst
Proxy types when passed as parameters were throwing an exception in the dotnet runtime. Removing the check and throw did not have an
adverse effect on the runtime, so it was removed.
Compliance test added that passes an interface as a parameter.
Fixes #316
=> fix(jsii-dotnet-runtime): Proxy parameters should not throw exception.

packages/jsii-build-tools/package-lock.json, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-java-runtime-test/package-lock.json, packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java, packages/jsii-java-runtime/pom.xml.t.js, packages/jsii-kernel/lib/kernel.ts, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ExportedBaseClass.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IIPrivatelyImplemented.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IPrivatelyImplementedProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ReturnsPrivateImplementationOfInterface.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ExportedBaseClass.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/IPrivatelyImplemented.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ReturnsPrivateImplementationOfInterface.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-ruby-runtime/package-lock.json
When an un-exported type that extends an exported type is returned with
an interface as the declared type, the JSII kernel used to return a ref
with the FQN of the exported supertype, instead of correctly wrapping
the instance in a proxy of the interface type as it should have.
Fixes #302
=> fix(kernel): Correctly return instances of un-exported types

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs, packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java, packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java, packages/jsii-kernel/test/test.kernel.ts, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/JsiiAgent_.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/JsiiAgent.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-runtime/package-lock.json
Language runtimes now set JSII_AGENT to include the runtime version
such as "DotNet/1.2.3.4" or "Java/1.8.44".
Fixes #324
=> feat: JSII_AGENT

.gitignore, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-dotnet-runtime/.gitignore, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Client/RuntimeTests.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/JsiiException.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/INodeProcess.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/Runtime.cs
* The JSII runtime for DotNet applications did not properly dispose of the IO streams in use for communication between the dotnet and jsii processes. This has been fixed, which solves the EPIPE error.
* During this investigation, it was found that the DotNet runtime did not redirect stderr, which disabled the use of JSII_DEBUG. Fixed.
* If the node process is closed unexpectedly, the application will now throw an exception with the contents of STDERR.
* Added Unit Test for node process closing unexpectedly.
* Added gitignore rule for "dist" folders, which are created by pack.
Fixes #341
=> fix(jsii-dotnet-runtime): Fix EPIPE on Windows.

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java, packages/jsii-kernel/lib/kernel.ts, packages/jsii-kernel/test/test.kernel.ts, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Constructors.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IIPublicInterface.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IPublicInterfaceProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/InbetweenClass.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/PublicClass.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Constructors.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/IPublicInterface.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/InbetweenClass.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/PublicClass.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/classes.expected.txt, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.inheritance.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/jsii-tree.test.types.expected.txt
When passing references across the JSII language boundary, the static
return type of a method is used instead of the runtime type of the
object if they are not the same, even if they are compatible. This
causes issues that make it impossible to up-cast from methods such as
`IConstruct.findChild` that return a super-class that is expected to be
up-casted to it's known dynamic type.
Fixes #345
---
TODO:
=> fix(kernel): Improve tagged type of wire values

packages/jsii/lib/compiler.ts, packages/jsii/package.json
Don't use the upstream private API function to turn a `CompilerHost` into a
`ParseConfigHost` anymore; instead, I copied the implementation, which is
simple enough.
Fixes #350.
=> fix: remove use of private API

CONTRIBUTING.md
As the title suggests this PR is mostly about adding an explanation of how to build the `superchain` docker image if you don't have access to the relevant registry/image. However, I've also made a few other tweaks to the contribution guide which I hope are correct and useful.
Ref: #354
=> Add instructions for building superchain docker image to contributing guide

packages/jsii/lib/assembler.ts, packages/jsii/test/negatives/neg.double-interface-members-deeper.ts, packages/jsii/test/negatives/neg.double-interface-members-method.ts, packages/jsii/test/negatives/neg.double-interface-members.ts, packages/jsii/test/negatives/neg.implementation-changes-types.2.ts
In C# it's prohibited to declare an interface member
that also exists in an inherited interface. Have jsii
detect this illegal pattern.
Strictly speaking, this only true if we don't overload,
but since we don't support overloading anyway we just
check on the member names, not the types.
Fixes #340.
=> fix(jsii): detect double interface member declarations

packages/jsii-java-runtime/pom.xml.t.js
Versions low than 2.9.8 have a number of CVEs filed against it.
=> fix: Bump version of Jackson because of CVEs

packages/jsii-pacmak/bin/jsii-pacmak.ts, packages/jsii-pacmak/lib/targets/dotnet.ts
Always generate to `$root/dist/TARGET`, even when only
generating one target. This behavior works better
for selectively building targets in a larger build that
expects certain naming conventions.
=> fix(jsii-pacmack): default to target directory mode

packages/jsii/lib/assembler.ts, packages/jsii/test/negatives/neg.const-enum.ts
'const enums' are inlined at the usage site by TypeScript and so the
generated type will not be in the JavaScript source code in the
assembly, even though the declaration will be there.
This leads to "symbol not found" errors upon trying to load it.
https://www.typescriptlang.org/docs/handbook/enums.html#const-enums
Fixes awslabs/aws-cdk#1969
=> fix(jsii): prohibit exported const enums

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-python-runtime/src/jsii/__init__.py, packages/jsii-python-runtime/src/jsii/_runtime.py, packages/jsii-python-runtime/tests/test_compliance.py
In the JSII, we generate a proxy class for any Abstract classes. This proxy class inherits from the abstract class, and does nothing but provide implementations of any abstract methods/properties that just call into the JSII. However, this only worked for abstract methods defined on this specific abstract class, not any parent abstract classes.
This PR resolves that issue, by building up a list of all abstract classes in an abstract class's inheritance tree, and then has the proxy depend on it. 
Because the actual name of the abstract class is not part of a module's public interface, this PR adds a ``jsii.proxy_for`` function, which takes an abstract class and returns the proxy class for it. 
```python
class Value(scope.jsii_calc_base.Base, metaclass=jsii.JSIIAbstractClass, …
```
=> Abstract proxy classes need to inherent from parent's proxies

packages/jsii/bin/jsii.ts, packages/jsii/lib/assembler.ts, packages/jsii/lib/compiler.ts, packages/jsii/lib/utils.ts
Emit jsii diagnostics error when in watch mode, and also format the errors with a
"TS9999" error code so that VSCode's $tsc problem matcher will show them as
"Problems". Prefix "JSII" in the message to distinguish that these are jsii errors.
Fixes #382
=> fix(jsii): show jsii diagnostics in watch mode and support $tsc problem matcher

packages/jsii-python-runtime/src/jsii/_kernel/__init__.py, packages/jsii-python-runtime/src/jsii/_kernel/providers/__init__.py, packages/jsii-python-runtime/src/jsii/_kernel/providers/base.py, packages/jsii-python-runtime/src/jsii/_kernel/providers/process.py
This provides distinction from just ``Kernel``, which acts as a wrapper over a ``Provider`` that implements most of the logic.
=> Rename BaseKernel/ProcessKernel to Provider to make it more distinct

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ClassThatImplementsTheInternalInterface.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ClassThatImplementsThePrivateInterface.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConsumersOfThisCrazyTypeSystem.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IAnotherPublicInterfaceProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IIAnotherPublicInterface.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IINonInternalInterface.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/INonInternalInterfaceProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ClassThatImplementsTheInternalInterface.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ClassThatImplementsThePrivateInterface.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConsumersOfThisCrazyTypeSystem.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/IAnotherPublicInterface.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/INonInternalInterface.java, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/classes.expected.txt, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.inheritance.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/jsii-tree.test.types.expected.txt, packages/jsii/lib/assembler.ts, packages/jsii/test/negatives/neg.deref-error.ts, packages/jsii/test/negatives/neg.implements-class.ts, packages/jsii/test/negatives/neg.internal-base-class.ts
When a type inherits (extends/implements) from a hidden (private/internal)
interface, and that interface extends a non-hidden interface, we need to 
copy the non-hidden interface to the consuming type so that it can be polymorphically
used.
Follow up on #390
Co-authored-by: RomainMuller <rmuller@amazon.com>
=> fix: copy non-hidden bases when erasing hidden interfaces

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-python-runtime/src/jsii/__init__.py, packages/jsii-python-runtime/src/jsii/_kernel/__init__.py, packages/jsii-python-runtime/src/jsii/_kernel/providers/base.py, packages/jsii-python-runtime/src/jsii/_kernel/providers/process.py, packages/jsii-python-runtime/src/jsii/_kernel/types.py, packages/jsii-python-runtime/src/jsii/_reference_map.py, packages/jsii-python-runtime/tests/test_compliance.py
Implements async function support, exposing it the same as a sync function in the Python language.
This is basically done, but will need to coordinate with sync callbacks to make sure we're not doing anything drastically different for the bits that are going to be shared.
=> Implement Async Function Support

packages/jsii-python-runtime/.gitignore, packages/jsii-python-runtime/LICENSE, packages/jsii-python-runtime/MANIFEST.in, packages/jsii-python-runtime/NOTICE, packages/jsii-python-runtime/bin/generate, packages/jsii-python-runtime/package.json, packages/jsii-python-runtime/setup.py
- Adds the License information for the `jsii` library.
- Add the Description/README.md information to the Python metadata, so it will show up on PyPI.
- Add some Classifiers to tag the JSII with some basic metadata about Python support, project lifecycle, target audience, etc.
=> Misc Cleanups for the Python Runtime

packages/jsii-kernel/lib/serialization.ts, packages/jsii-runtime/webpack.config.js
=> fix(kernel): Transitively consider properties when deserializing structs

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
They Python code generation was only lifting the properties of the specified data class, but it wasn't lifting the properties of all of the data classes in the inheritance tree.
We have to do that, so we'll go ahead and walk our entire interface hierarchy and build up a flat list of all of the properties, and use that list to generate our lifted properties.
---
=> fix(python): Lift the entire data class hierarchy

packages/jsii-java-runtime/pom.xml.t.js
=> chore: Stop using ancient version of Guava-IO, switch to latest Guava instead

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-kernel/lib/serialization.ts, packages/jsii-kernel/test/test.kernel.ts, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IOptionalStruct.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/OptionalStruct.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/OptionalStructConsumer.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/OptionalStructProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/OptionalStruct.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/OptionalStructConsumer.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/classes.expected.txt, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.inheritance.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/jsii-tree.test.types.expected.txt
Upon deserializing objects from a "native" front-end (Java, .NET, ...),
the kernel now interprets an empty value for a struct type (aka data
type) as `undefined`, since front-ends that perform keyword lifting such
as Python will not be able to distinguish between "no argument passed"
and "an empty argument passed".
Fixes #411
=> feat(kernel): Normalize empty structs to undefined

README.md, packages/jsii-calc-base-of-base/package.json, packages/jsii-calc-base-of-base/test/assembly.jsii, packages/jsii-calc-base/package.json, packages/jsii-calc-base/test/assembly.jsii, packages/jsii-calc-lib/package.json, packages/jsii-calc-lib/test/assembly.jsii, packages/jsii-calc/package.json, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-spec/lib/spec.ts, packages/jsii-spec/test/test.name-tree.ts, packages/jsii/generate.sh, packages/jsii/lib/assembler.ts, packages/jsii/lib/project-info.ts, packages/jsii/test/test.negatives.ts, packages/jsii/test/test.project-info.ts
By default, the fully qualified version number (including the commit SHA
prefix) is written in the new `jsiiVersion` field of the assembly,
however in order to make this friendlier to tests, there is an option to
turn over to a *short* format by setting the new `jsii.versionFormat`
key in `package.json` to `'short'`.
Also, slightly altered the generation of the fully qualified version
name to distinguish between cases where the commit SHA was provided by
the CodeBuild environment variable, versus parsed using `git rev-parse`,
denoting the later is indicative of an "unreleased" version.
Fixes #412
=> feat(jsii): Tag the jsii compiler version in the .jsii assemblies

packages/jsii-python-runtime/src/jsii/_kernel/providers/process.py
Fixes #245 for Python.
This assumes that the `JSII_RUNTIME` will point to the actual `.js` file and that the `js-runtime.js.map` and `mappings.wasm` will be in the same directory.
=> Add support for JSII_RUNTIME

packages/jsii/bin/jsii.ts, packages/jsii/lib/assembler.ts, packages/jsii/lib/compiler.ts, packages/jsii/lib/emitter.ts, packages/jsii/lib/validator.ts, packages/jsii/test/negatives/neg.compilation-error.ts, packages/jsii/test/test.negatives.ts
In #383 we modified the compiler to continue jsii validation despite
compilation errors but did not propagate the fact that there were
compilation errors.
This resulted in "jsii" exiting with a 0 exit code even in case
of errors.
Fixes #441
=> fix: exit with non-zero exit code if there are compilation errors

packages/jsii-pacmak/lib/target.ts
Stop the Maven dependency collector from recursing into directories it's
already seen. This avoids finding adding the same directories over and
over again, which Maven subsequently can't deal with.
Fixes #447, and probably the hanging build.
=> fix(pacmak): fix Maven dependency collector.

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-kernel/lib/kernel.ts, packages/jsii-kernel/test/test.kernel.ts, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/StaticContext.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/StaticContext.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/classes.expected.txt, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.inheritance.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/jsii-tree.test.types.expected.txt
Javascript allows static members to refer to other static members
through `this`, but the `jsii-kernel` passed `null` for the `this`
context in `sinvoke`, making it impossible to invoke static methods that
made use of this feature through the `jsii` runtimes.
Fixes awslabs/aws-cdk#2304
---
=> fix(kernel): Set `this` in static contexts

packages/jsii-diff/bin/jsii-diff.ts, packages/jsii-pacmak/bin/jsii-pacmak.ts, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/lib/timer.ts, packages/jsii-pacmak/lib/util.ts, packages/jsii-pacmak/test/expected.jsii-calc-base/java/pom.xml, packages/jsii-pacmak/test/expected.jsii-calc-lib/java/pom.xml, packages/jsii-pacmak/test/expected.jsii-calc/java/pom.xml, packages/jsii-reflect/lib/assembly.ts, packages/jsii-reflect/lib/index.ts, packages/jsii-reflect/lib/initializer.ts, packages/jsii-reflect/lib/method.ts, packages/jsii-reflect/lib/type-system.ts
deCDK tests were calling `loadModule()` for every package.
`loadModule()` did have some recursion avoidance INSIDE one call,
but not across multiple load calls on the same type system.
This brings down the deCDK tests from 80s to 10s.
Add an option to disable validation, which would bring the full CDK
typesystem loading down from 10s to 600ms (validation is enabled
by default).
Some more type exposure updates so that we can update awslint
and friends in the CDK repository to take advantage of the new
jsii model.
=> fix(jsii-reflect): don't load same assembly multiple times

packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DontComplainAboutVariadicAfterOptional.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/VariadicMethod.java
The previous iteration was incorrectly forwarding variadic methods'
"rest" argument to the JSII runtime, causing a runtime failure at the
deserialization site.
=> fix(java): Correctly pass variadic arguments

packages/jsii-dotnet-generator/src/Amazon.JSII.Generator.UnitTests/MethodExtensionsTests.cs, packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/CallableExtensions.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Calculator.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DefaultedConstructorArgument.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DoNotRecognizeAnyAsOptional.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DocumentedClass.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DontComplainAboutVariadicAfterOptional.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IIInterfaceWithOptionalMethodArguments.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IInterfaceWithOptionalMethodArgumentsProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/NullShouldBeTreatedAsUndefined.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/OptionalConstructorArgument.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/OptionalStructConsumer.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/RuntimeTypeChecking.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/VariadicMethod.cs
Method parameters were missing the "optional" marker due to the logic
that was initially intended to prune only documentation from the JSON
data attached to the method attribute.
=> fix(dotnet): Correctly generate "optional" markers

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/CallbackExtensions.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/ReflectionUtils.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/VoidCallback.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/VoidCallbackProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/VoidCallback.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/classes.expected.txt, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.inheritance.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/jsii-tree.test.types.expected.txt
Previously, it attempted to generate an OptionalValue instance with no
`Type`, which is illegal.
=> fix(dotnet): Correctly handle 'void' callback results

packages/jsii-pacmak/lib/markdown.ts, packages/jsii-pacmak/test/test.python.ts
=> fix(python): fix indentation for multiline bullets in RST generator

packages/jsii-diff/bin/jsii-diff.ts
Potentially assembly validation errors throw up a giant error list.
Have jsii-diff be more concise about the errors, which will be
better for cdk-build-tools.
=> fix(jsii-diff): be nicer about validation errors

packages/jsii-calc/lib/erasures.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IIJsii487External.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IJsii487ExternalProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Jsii487Derived.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/IJsii487External.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Jsii487Derived.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/classes.expected.txt, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.inheritance.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/jsii-tree.test.types.expected.txt, packages/jsii/lib/assembler.ts
When a base class is erased, we now treat it's "implementation" clauses
as if they were part of the original class (similar to how we merge declarations
for methods/properties).
Fixes #487
=> fix(jsii): consider interfaces from erased base classes

packages/jsii-calc/lib/erasures.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IIJsii487External2.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IJsii487External2Proxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Jsii487Derived.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/IJsii487External2.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Jsii487Derived.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.inheritance.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/jsii-tree.test.types.expected.txt, packages/jsii/lib/assembler.ts
When processing the merged set if "implements" declarations,
do not override the "interfaces" section when there are multiple
declaration sites (as in when a base class is erased).
Fixes #493
=> fix(jsii): merge all "implements" declarations

packages/jsii-calc/lib/erasures.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IIJsii496.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IJsii496Proxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Jsii496Derived.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/IJsii496.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Jsii496Derived.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/classes.expected.txt, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.inheritance.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/jsii-tree.test.types.expected.txt, packages/jsii/lib/assembler.ts
When processing interfaces from multiple declaration sites (e.g.
when a base class is erased), we need to make sure that only
include every interface once.
Fixes #496
=> fix(jsii): deduplicate interfaces

packages/jsii-diff/lib/type-analysis.ts, packages/jsii-diff/package.json, packages/jsii-diff/test/test.type-unions.ts
=> fix(jsii-diff): correctly handle assignability of type unions

packages/jsii/lib/assembler.ts, packages/jsii/lib/compiler.ts
After failing compilation we proceed with jsii analysis, to give as much
information as possible in one go.
However, some compilation failures lead to a lack of information that
make the jsii analyzer crash, which ultimately leads jsii to fail with
no more information than:
Error: TypeError: Cannot read property 'getJsDocTags' of undefined
Fix this in two ways:
- First, detect the situation where this occurs and produce a more
useful error message.
- Guard against this happening in general by catching exceptions
during type analysis and still printing the compilation errors.
=> fix(assembler): handle unknown types without crashing

packages/jsii-diff/bin/jsii-diff.ts, packages/jsii-diff/lib/util.ts
When a new package is created, jsii-diff will try to download the
previous package from NPM and then fail.
Remember that the package doesn't exist upstream and fail silently
in that case.
=> fix(jsii-diff): don't fail on new packages

packages/jsii-diff/lib/type-analysis.ts
Make jsii-diff not crash in the following case:
- Assembly A depends on Assembly B, and they both update simultaneously.
- Assembly A' uses a return type T' freshly introduced in Assembly B'.
When doing the supertype check, the compatibility check of A -> A',
the lookup of T' inside B would lead to an exception, which would
crash the tool.
=> fix(jsii-diff): catch exception if type disappeared from other assembly

packages/jsii/lib/assembler.ts, packages/jsii/test/negatives/neg.prohibited-member-name.ts
We are not currently rigged to handle some special methods
that have meaning in runtimes that we target (specifically,
'equals', 'hashCode' and 'GetHashCode'). Just prohibit them for now.
=> feat(jsii): protect against prohibited member names

packages/jsii-pacmak/lib/targets/dotnet.ts, packages/jsii-pacmak/lib/util.ts
Try to survive NuGet's failing due to race conditions.
=> fix(jsii-pacmak): retry .NET build a couple of times

packages/jsii-calc/package.json, packages/jsii-calc/test/assembly.jsii, packages/jsii-dotnet-generator/build.sh, packages/jsii-dotnet-jsonmodel/build.sh, packages/jsii-dotnet-runtime-test/build.sh, packages/jsii-dotnet-runtime/build.sh, packages/jsii-pacmak/bin/jsii-pacmak.ts, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-spec/lib/spec.ts, packages/jsii/lib/assembler.ts, packages/jsii/lib/project-info.ts
This can be used to track free-form maintainer data, for use in systems that
are not part of the standard JSII toolchain. For example, it can be used to
encode configuration behavior for proprietary tools that process assemblies.
=> feat(jsii-spec): Add optional metadata field

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-python-runtime/tests/test_compliance.py
Fixes #483 
Handles variadic args and adds a test of VariadicMethod to the compliance tests.
=> fix(python): support variadic arguments

packages/jsii-diff/lib/classes-ifaces.ts, packages/jsii-diff/test/test.classes.ts
Famous last words: "Trust me I know what I'm doing"
Fixes #520
=> fix(jsii-diff): crash when changing method to a property

packages/jsii-kernel/lib/serialization.ts, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/MyFirstStruct.java, packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/StructWithOnlyOptionals.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/CalculatorProps.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DerivedStruct.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/EraseUndefinedHashValuesOptions.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Greetee.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/LoadBalancedFargateServiceProps.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/NullShouldBeTreatedAsUndefinedData.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/OptionalStruct.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/UnionProperties.java
The JSON types were serialized "as-is" without touch, meaning if the
value was `null`, it would be forwarded as `null`, instead of `undefined`.
This caused some CDK usage patterns to crash at runtime. This changes
the behavior so that top-level `null`s in JSON types turn into `undefined`,
while `null`s nested in the JSON value will be preserved (they are valid
JSON after all!).
Additionally, tuned the Java code generator a little:
The serialization of structs creates a jackson ObjectNode to pass down
to the serialization layer, however those are turned to JSON without
processing and are not honoring the inclusion setting to ignore nulls.
Added some code in the Java generator to stop adding null values into
the ObjectNode.
---
By submitting this pull request, I confirm that my contribution …
=> fix(kernel): Correct null handling in JSON types

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/WithPrivatePropertyInConstructor.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/WithPrivatePropertyInConstructor.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/classes.expected.txt, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.inheritance.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/jsii-tree.test.types.expected.txt, packages/jsii/lib/assembler.ts
When declared as part of a constructor argument declaration, private
properties would not be ignored as such, which could cause spurious JSII
errors, and made private APIs visible to other languages.
---
=> fix(jsii): Correctly ignore private properties from ctor

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/SingletonInt.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/SingletonIntEnum.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/SingletonString.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/SingletonStringEnum.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SingletonInt.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SingletonIntEnum.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SingletonString.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SingletonStringEnum.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/classes.expected.txt, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.inheritance.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/jsii-tree.test.types.expected.txt, packages/jsii/lib/assembler.ts
When an enum has only one option, TypeScript handles it in a special way
and tries very hard to hide the enum declaration in favor of the sole
member. This caused incorrect type names and kinds to be emitted in the
JSII assembly, resulting in incorrect behavior.
This uses a non-public part of the TSC API (possibly an omission from
the hand-written type model), so it includes an additional guard check
to fail explicitly in case the API's behavior happens to change in a
breaking way.
Fixes #231
---
=> fix(jsii): Correctly handle singleton enums

packages/jsii-reflect/lib/assembly.ts
This enables tools that use `jsii-reflect` to consume and reason over
the values in the metadata field.
=> feat(reflect): Expose Assembly metadata field

packages/jsii-diff/bin/jsii-diff.ts, packages/jsii-diff/lib/classes-ifaces.ts, packages/jsii-diff/lib/diagnostics.ts, packages/jsii-diff/lib/enums.ts, packages/jsii-diff/lib/index.ts, packages/jsii-diff/lib/types.ts, packages/jsii-diff/test/test.classes.ts, packages/jsii-diff/test/test.diagnostics.ts, packages/jsii-diff/test/test.structs.ts, packages/jsii-diff/test/util.ts
jsii-diff now prints all changes, can report changes over experimental
packages as errors, and has the ability to load a set of ignore rules
from a file.
=> feat(jsii-diff): extend reporting options

packages/jsii/lib/validator.ts, packages/jsii/test/negatives/neg.implementing-method-changes-optionality.1.ts, packages/jsii/test/negatives/neg.implementing-method-changes-optionality.2.ts, packages/jsii/test/negatives/neg.implementing-method-changes-optionality.ts, packages/jsii/test/negatives/neg.implementing-property-changes-optionality.1.ts, packages/jsii/test/negatives/neg.implementing-property-changes-optionality.2.ts, packages/jsii/test/negatives/neg.implementing-property-changes-optionality.ts
Optionality must remain unchancged when overriding methods and
properties, such that types are pure with respects to Liskov's
substitution.
---
=> fix(jsii): Validate overriding does not affect optionality

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
=> fix(python): parameter names in docstrings should be snake_case, not camelCase

packages/jsii-kernel/lib/serialization.ts, packages/jsii-kernel/test/test.kernel.ts
The deserializer mistakingly used `objectReference` instead of `isObjRef` when trying to identify this case.
Test was added to verify this fix.
Fixes #553
Co-authored-by: Romain Muller <rmuller@amazon.com>
=> fix(kernel): properly deserialize structs passed in byref

packages/jsii-diff/lib/type-analysis.ts, packages/jsii-diff/test/test.structs.ts, packages/jsii-reflect/lib/type-system.ts
Structural type checking would recurse endlessly if a struct had a
member with the same type as itself, or the same type as a struct that
contained itself.
Add a cache to prevent infinite recursion.
Also in this commit: `tryFindFqn` no longer explodes if the referenced
assembly couldn't be found, but simply returns `undefined` as it should.
=> fix(jsii-diff): handle recursive types

packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
The generated .csproj file is currently using the same version for Package Version and the
version for Amazon.JSII.Runtime.
=> fix(pacmak): fix .NET generated .csproj files using incorrect version for Amazon.JSII.Runtime

packages/jsii-reflect/bin/jsii-tree.ts, packages/jsii-reflect/lib/class.ts, packages/jsii-reflect/lib/docs.ts, packages/jsii-reflect/lib/interface.ts, packages/jsii-reflect/lib/method.ts, packages/jsii-reflect/lib/property.ts, packages/jsii-reflect/lib/tree.ts, packages/jsii-reflect/lib/type-system.ts, packages/jsii-reflect/test/findClass.expected.txt, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt, packages/jsii-reflect/test/typesystem.test.ts, packages/jsii-reflect/test/util.ts, packages/jsii/lib/assembler.ts, packages/jsii/test/test.docs.ts
Fix the inheriting of stability tags for the initializer. It used to
inherit from the package, it now correctly inherits from the class.
Update jsii-reflect with a "load all modules" method (to save time
in a complex dependency tree) and jsii-tree with options to show
stabilities.
=> fix(jsii): correctly inherit initializer stability

packages/codemaker/lib/case-utils.ts, packages/codemaker/test/test.case-utils.ts, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
Common mixed-case abbrevations will be snake-cased as a while, instead
of being broken up into separate word parts.
=>  fix(python): respect mixed-case abbrevs while snake-casing

packages/jsii-diff/lib/classes-ifaces.ts, packages/jsii-diff/lib/enums.ts, packages/jsii-diff/lib/stability.ts, packages/jsii-diff/test/test.diagnostics.ts
Once an API element is marked @stable, it is not allowed to
retract that stability guarantee anymore by changing it back to
@experimental. This is now verified by `jsii-diff`.
This was always intended to be checked, but was missed as an oversight
in the initial implementation.
=> feat(jsii-diff): also check stability transitions

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-kernel/lib/serialization.ts, packages/jsii-kernel/test/test.kernel.ts, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/StructPassing.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/StructPassing.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-python-runtime/tests/test_compliance.py, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt
Detect when required struct properties are not supplied, so that
we can produce useful error messages to untyped jsii languages (in
particular, Python).
Also check for an array in place of a variadic argument, and throw
a hopefully helpful message to hint at a common misuse.
Fix the test to be actually variadic, which it wasn't :o.
=> fix(kernel): validate presence of required struct properties

README.md, packages/jsii/lib/compiler.ts, packages/jsii/lib/project-info.ts, packages/jsii/test/test.negatives.ts
This PR adds the possibility to configure the outDir and the rootDir for `tsc`
=> feat(jsii): configure outDir and rootDir for tsc

packages/jsii-java-runtime/pom.xml.t.js
Mitigate risks of new major versions of the JSII Java runtime causing
unexpected breakage when they release by pinning the dependencies to the
current major (`[A,B)` version spec is `A <= version < B`).
Fixes #602
---
=> deps(java): pin dependencies to current major

packages/jsii-java-runtime/package.json, packages/jsii-java-runtime/pom.xml.t.js
Based on recommendations, further restricting Java dependencies to remain on the currrent
minor revision, and model the dependencies versions as properties so as to be able to
update those with relaitve ease
---
=> chore(deps): restrict java further to current minor

packages/codemaker/package-lock.json, packages/jsii-build-tools/package-lock.json, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-diff/package-lock.json, packages/jsii-dotnet-jsonmodel/package-lock.json, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Spec/Stability.cs, packages/jsii-dotnet-runtime-test/package-lock.json, packages/jsii-dotnet-runtime/package-lock.json, packages/jsii-java-runtime/package-lock.json, packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/Stability.java, packages/jsii-kernel/package-lock.json, packages/jsii-pacmak/package-lock.json, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/StructPassing.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/StructPassing.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/package-lock.json, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-ruby-runtime/package-lock.json, packages/jsii-runtime/package-lock.json, packages/jsii-spec/package-lock.json, packages/jsii/package-lock.json, packages/oo-ascii-tree/package-lock.json
Stabilities have representations in runtimes, and the .NET
generator has an enum that also had to be updated.
=> fix: fix usage of "external" stability

.dependabot/config.yml
Updated @dependabot configuration to use new `language/<name>` labels.
---
=> chore: update dependabot default labels to new standard

.travis.yml
More explicitly skip publishing to DockerHub if this is a PR build. Display
values of `$TRAVIS_TAG` and `$TRAVIS_BRANCH` for more information
when troubleshooting builds (if that's related to publishing).
Release builds from `master` to a `:nightly` tag while (git) tagged builds
will (also) release to `:latest`.
---
=> chore: minor tweaks to travis configuration

buildspec.yaml
Modification to the check introduced in #668 
CodePipeline downloads the source as a zip from the source provider rather than doing a Git clone.
This means the .git folder won't be retained and git commands won't work in CodeBuild. 
---
=> chore(ci): remove check against source tree from CodeBuild buildspec

packages/jsii-java-runtime/pom.xml.t.js, packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiEngine.java, packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiObjectMapper.java, packages/jsii-java-runtime/project/src/test/java/software/amazon/jsii/JsiiObjectMapperTest.java
The dependency was used only for a small amount of trivial utilities
that can be replicated locally without much effort. Removed the
dependency here.
---
=> feat(java): remove dependency on google Guava

packages/jsii-java-runtime/pom.xml.t.js
Moves past certain security vulnerabilities in Jackson-databind.
---
=> chore: upgrade Java runtime dependencies

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/CallbackExtensions.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DataRenderer.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DataRenderer.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/sphinx/jsii-calc.rst, packages/jsii-reflect/test/jsii-tree.test.all.expected.txt, packages/jsii-reflect/test/jsii-tree.test.members.expected.txt
When bringding callback results into dotnet types, we used to modify the
Dictionary item within the loop, which is illegal in C#. Any mutation on
the collection will cause the iterator to abort.
Insead, create a new Dictionary and add the resolved values to that.
Fixes #690 
---
=> fix(dotnet): stop mutating Dictionary when iterating on it

packages/jsii-java-runtime-test/pom.xml.t.js, packages/jsii-java-runtime/pom.xml.t.js, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/test/expected.jsii-calc-base/java/pom.xml, packages/jsii-pacmak/test/expected.jsii-calc-lib/java/pom.xml, packages/jsii-pacmak/test/expected.jsii-calc/java/pom.xml
Java:  maven-compiler-plugin 3.8.1 (latest version)
Fixes # 
---
=> chore(deps): bump maven-compiler-plugin from 3.6.1 to 3.8.1

.travis.yml, packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiEngine.java, packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/Util.java, packages/jsii-pacmak/package-lock.json, packages/jsii-reflect/package-lock.json, packages/jsii-ruby-runtime/project/Gemfile.lock, packages/jsii-runtime/package-lock.json, packages/jsii/package-lock.json, packages/oo-ascii-tree/package-lock.json
The previous code only checked whether a methodd name was a get/setter
by checking if it's name started by `get` or `set` and was at least 4
characters long. This is insufficient, as a method called `settings`
would be misidentified.
Changed to expect getters to have zero parameters, and setters to have
exactly one parameter and to match a corresponding getter.
---
=> fix(java): improve property override detection

.mergify.yml
- Require the TravisCI has passed before auto-merging a PR. This is
required to ensure the `jsii/superchain` Docker image was correctly
built and tested before going forward.
- Drop stale "approved" reviews, but keep stale "changes requested"
reviews, so that people who requested changes can come and verify that
the changes were indeed applied.
- Remove the "Pull Request Checklist" message as it was emitted multiple
times and that god somewhat irritating. Didn't seem to find a clean
way to prevent multiple emission here.
- Tweaked message for when a PR is ready for automatic merging.
---
=> chore: tweak mergify configuration

superchain/Dockerfile
Upgrade the python `setuptools` modules to latest in order to enable support
for the `long_description_content_type` distribution option.
Tested in CDK's master build and publishing pipeline.
Fixes #708
=> fix(superchain): fix python distribution due to old setuptools

CONTRIBUTING.md, packages/jsii-pacmak/lib/logging.ts, packages/jsii-pacmak/lib/targets/python.ts, superchain/Dockerfile
Adds a `twine check` invocation at the end of building the distribution
artifacts for PyPI, in order to ensure the produced bundles will render
propertly on PyPI, and be valid artifacts.
This particularly guards against "tool old" versions of `setuptools`,
but could also catch certain other issues.
Fixes #710
---
=> feat(python): check distribution artifacts with `twine`

packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/FrameworkToJsiiConverter.cs
The runtime fails to cast properties when a Dictionary<string, object> _is actually_ a Dictionary<string, Dictionary<string, object>>
Example:
```
var launchTemplateData = new CfnLaunchTemplate.LaunchTemplateDataProperty
{
InstanceType = "t3.medium",
Monitoring = new CfnLaunchTemplate.MonitoringProperty { Enabled = true }
};
var cfnLaunchTemplate = new CfnLaunchTemplate(stack, "template", new CfnLaunchTemplateProps
{
LaunchTemplateData = launchTemplateData,
LaunchTemplateName = "template"
});
```
In this example, the LaunchTemplateData property is a Dictionary<string, object>. However, the 'Monitoring' key is also a Dictionary<string, object>. This was not supported by the runtime and would fail.
Fixes https://github.com/aws/aws-cdk/issues/2496
Cdk synth output after the fix:
``` …
```
=> fix(dotnet): Fix property set for nested Dictionaries

packages/jsii/lib/assembler.ts
Instead of tagging the entire declaration, only tag the name part of it
when emitting warnings about usage of reserved words from one of the
supported languages. This improves the actionability of the messages,
and makes for shorter log entries, too.
---
=> feat(jsii): improve locality of warnings emitted for reserved words

superchain/Dockerfile, superchain/README.md
Adds the OpenSSL CLI tools that can be used for a large number of
applications.
---
=> feat(superchain): ship with openssl CLI tools

superchain/Dockerfile
The install of dotnet in the Docker build caused the first-time
experience to trigger as the environment variable apparently must be set
to `true` and not `1`. This causes a package cache to be pre-populated
(to spee dup future builds), however as this is baked into a Docker
image, this will cause bloat & will probably result in stale cached
artifacts.
---
=> chore(superchain): stop pre-populating package cache

packages/jsii-runtime/lib/host.ts, packages/jsii-runtime/package.json, packages/jsii-runtime/test/stress-test.ts
Fixes #778. This PR eliminates the mutual recursion between `KernelHost.run()` and `KernelHost.processRequest()` by scheduling the recursive `KernelHost.run()` call to run on the next iteration of the event loop.
The code change has been tested as follows:
- by running the stress-test script with and without the change to confirm that the crash occurs without the change and does not occur with the change;
- by running the unit tests to confirm that behavior is consistent;
- by synthesizing our internal CDK stack and confirming that the crash does not occur and that resources are generated correctly.
---
=> fix: stack overflow in KernelHost.run()

packages/jsii-calc/package.json, packages/jsii-calc/test/assembly.jsii, packages/jsii-dotnet-analyzers/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj, packages/jsii-dotnet-analyzers/src/Amazon.JSII.Analyzers/Amazon.JSII.Analyzers.csproj, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Amazon.JSII.JsonModel.csproj, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj, packages/jsii-kernel/test/kernel.test.ts, packages/jsii-pacmak/lib/targets/dotnet.ts, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon.JSII.Tests.CalculatorPackageId.csproj, packages/jsii-ruby-runtime/project/Gemfile.lock, packages/jsii/test/negatives/.gitignore
Configure a `PackageIconUrl` on all the NuGet packages, so as to have a
somewhat consistent branding experience. Currently, the AWS logo is
being used; this may later be replaced by a `jsii` logo if/when we get
one.
Fixes #773 
---
=> feat: configure AWS logo for NuGet packages

docs/configuration.md
That is used to set a specific URL for use in the NuGet Gallery.
---
=> chore(doc): document `iconUrl` setting of the `dotnet` target

packages/jsii-python-runtime/src/jsii/_kernel/__init__.py, packages/jsii-python-runtime/tests/test_python.py
A common error seems to be to try to pass a function as a parameter
into a JSII call (have seen 3 occurrences of this in the last week).
Previously, this call would fail when trying to assing the
`__jsii_type__` property to the function object.
Specifically catch this case to give a helpful error message.
Fixes aws/aws-cdk#4064.
Related to #806 
---
=> fix(python): clear error message when trying to serialize function

packages/jsii-build-tools/bin/package-dotnet, packages/jsii-dotnet-analyzers/.gitignore, packages/jsii-dotnet-analyzers/NuGet.Metadata.props.t.js, packages/jsii-dotnet-analyzers/build.sh, packages/jsii-dotnet-jsonmodel/.gitignore, packages/jsii-dotnet-jsonmodel/NuGet.Metadata.props.t.js, packages/jsii-dotnet-jsonmodel/build.sh, packages/jsii-dotnet-runtime/.gitignore, packages/jsii-dotnet-runtime/NuGet.Metadata.props.t.js, packages/jsii-dotnet-runtime/build.sh, packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts, packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId.csproj, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId.csproj, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon.JSII.Tests.CalculatorPackageId.csproj
The legacy format is not supported by NuGet's own symbols server, and the
SymbolSource server is currently experiencing a certificate expiration event,
which seems to be a somewhat recurring issue (NuGet/Home#6082).
More info: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
---
=> fix(dotnet): use snupkg format for dotnet symbol packages

packages/jsii/lib/compiler.ts
This will prevent forgotten initialization errors such as the root cause
of aws/aws-cdk#4286.
---
=> feat(jsii): enable strictPropertyInitialization checks

CONTRIBUTING.md, packages/jsii-sampiler/.npmignore
Additional changes to the CONTRIBUTING.md, mainly to reflect that
the superchain image based setup as the recommended option.
---
=> fix(sampiler): Add missing .npmignore

packages/jsii-diff/package.json
Without the main property, a consuming module cannot `require` it.
---
=> fix(jsii-diff): add 'main' property to package.json

.gitattributes
PNG files may cause working tree confusion without this change.
Fixes # 
---
=> chore: update gitattributes to recognize common binary types

.travis.yml, buildspec.yaml
Per the `yarn` recommendations.
---
=> chore: add --frozen-lockfile to CI/CD 'yarn install' invocations

README.md, docs/runtime-architecture.md
=> docs: add high-level description of runtime architecture

packages/jsii-pacmak/lib/targets/java.ts
Generating the aggregate POM could result in building a cyclic POM module tree,
as the aggregate POM file would then be replacing the module's own POM. This
stops aggregate-packaging single modules.
Also addresses an issue with the builder method names being generated
inconsistently across the Struct & Class builders, resulting in invalid
call forwarding being attempted.
Finally, it correctly generates overloads for Class builder methods.
---
=> fix(pacmak): fix a couple of issues related to java generation

packages/jsii-diff/bin/jsii-diff.ts
Assembly validation is taking the majority of the time of doing the
API compatibility check, and the assemblies are almost guaranteed to
be correct.
Make it possible to skip the check for performance purposes.
Fixes # 
---
=> feat(jsii-diff): make assembly validation optional

superchain/Dockerfile, superchain/README.md
Since `jsii` now requires `netcoreapp3.0` as the target, there is no
point in bloating the `Docker` image with `2.X` support anymore for all
customers. Those interested in that runtime are still abel to install it
as part of a derived image or in their application's code.
---
=> chore: drop dotnet-sdk 2.2

packages/jsii-pacmak/lib/packaging.ts, packages/jsii-pacmak/lib/util.ts
There was a race condition in capturing the output of `npm pack`.
Ocassionally we would miss the output, not get a tarball name, combine
the empty string with a directory, and then get an EISDIR error when
trying to copy the tarball as a file (but giving it a directory name).
This race has been in there forever, but it became easier to trigger
since we started running a lot of `npm pack`s in parallel.
The solution is to wait for a different event on the `ChildProcess`
object.
---
=> fix(pacmak): occasional EISDIR failure

packages/jsii-pacmak/lib/npm-modules.ts, packages/jsii-pacmak/lib/packaging.ts, packages/jsii-pacmak/lib/toposort.ts, packages/jsii-pacmak/package.json, packages/jsii-pacmak/test/npm-modules.test.ts, yarn.lock
Fix situation where the .NET build accidentally downloads dependency
packages from NuGet, instead of using the locally built packages.
Caused by packages being built in the order given on the command line,
and if a consumer is built before a dependency, the NuGet build would
fall back to loading the package from the online repository.
Apply a topological sort to package building to prevent this from
happening.
---
=> fix(pacmak): .NET build downloading packages from NuGet

packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Api/Response/GetResponse.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Api/Response/NamingResponse.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Converters/TypeConverter.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Converters/TypeDictionaryConverter.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Converters/Util.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/JsonDictionaryBase.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Spec/ClassType.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Spec/DependencyRoot.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Spec/InterfaceType.cs, packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Spec/Method.cs, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/AnonymousObject.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/ReflectionUtils.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/Client.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/FrameworkToJsiiConverter.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/IFrameworkToJsiiConverter.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/JsiiToFrameworkConverter.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/IClient.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/IJsiiRuntimeProvider.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/ILoadedPackageSet.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/IResourceExtractor.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/IRuntime.cs, packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/JsiiRuntimeProvider.cs
Removing a host of unused `Using` statements, replacing verbose variable
typings with the `var` keyword, using more expressive syntax for certain
patterns, and resolving a couple of "potential null access" problems.
---
=> chore: resolve a large number of warnings in csharp codebase

packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java, packages/jsii-kernel/lib/serialization.ts, packages/jsii-kernel/test/kernel.test.ts, packages/jsii-python-runtime/tests/test_compliance.py
When mapping data (e.g. a Python `dict`) was passed through a JSON value,
it would not be deserialized correctly and the `$jsii.map` markers would
remain in the JS-visible map.
Fixes the cause of aws/aws-cdk#4957
---
=> fix(kernel): correctly de-serialize mappings as JSON

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-kernel/lib/serialization.ts, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/INestedStruct.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IRootStruct.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/NestedStruct.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/NestedStructProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/RootStruct.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/RootStructProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/RootStructValidator.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/NestedStruct.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/RootStruct.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/RootStructValidator.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-python-runtime/tests/test_compliance.py, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Added code to up-cast from `dict` to the relevant struct type in the generated
python code whenever the value type is some unambiguous struct. Whenever
a UNION of types is involved, the user must construct the struct type themselves,
as the runtime would then have no way to choose which type should be used on
it's own without additional information.
---
=> fix(python): correctly handle nested structs-as-dict

packages/jsii/lib/compiler.ts
Due to a TypeScript [bug], it was impossible to write a jsii module that takes a dependency on a module that has private type declarations in their d.ts file since they are untyped by definition.
This temporary fix sets `noImplicitAny` to `false` in order to disable this check and enable the dependency use case until we upgrade to the 3.7.x version-line.
Fixes #994
[bug]: https://github.com/microsoft/TypeScript/issues/33894
---
=> fix(jsii): unable to depend on modules with private declarations

scripts/package.sh
Those packages contain no artifacts that should be published, and considering them may cause leftover artifacts from tests to be part of the release artifacts, which breaks integration tests.
---
=> chore: ignore jsii-calc and @scope/* in package.sh

packages/jsii-rosetta/lib/markdown/extract-snippets.ts, packages/jsii-rosetta/lib/markdown/replace-code-renderer.ts, packages/jsii-rosetta/lib/markdown/replace-typescript-transform.ts, packages/jsii-rosetta/lib/markdown/types.ts, packages/jsii-rosetta/lib/rosetta.ts
Move imports around so that `require('commonmark')` no longer
appears in any `.d.ts` file that is reachable from `index.d.ts`.
It would break downstream TypeScript compilation because
`@types/commonmark` is in `devDependencies`.
---
=> chore(rosetta): remove 'commonmark' from public API

packages/jsii-config/package.json
Moves jsii-spec to dependencies in package.json instead of devDependencies for jsii-config. This was causing a missing dependency error at runtime.
Fixes #1030 
---
=> fix: Move jsii-spec to Dependencies in jsii-config

.dependabot/config.yml
=> chore: update dependabot config to match with new label names

packages/jsii-dotnet-analyzers/src/Amazon.JSII.Analyzers/Amazon.JSII.Analyzers.csproj
The Roslyn analyzer target framework must be set to `netstandard2.0` or
it will not successfully load up in Visual Studio.
Fixes aws/aws-cdk#5189
---
=> fix(dotnet/roslyn): analyzer target framework

packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java, packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiObjectMapper.java, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConfusingToJackson.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConfusingToJacksonStruct.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConfusingToJacksonStructProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IConfusingToJacksonStruct.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJackson.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJacksonStruct.java, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-python-runtime/tests/test_compliance.py, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
(Reintroduce #987).
Upon deserializing (`ObjectMapper#treeToValue`), Jackson will first
validate the `valueType` for whether ti can be deserialized with the
"standard" bean deserializer. This will bail out if there are multiple
ambiguous setters for a given property (they are ambiguous if they have
parameters of non-trivial types, such as `List`, some class, ...).
In order to remove the problem, this changes the deserialization path so
that instead of asking for deserialization into the needed instance type
directly, `JsiiObject` will be requested instead when the declared type
is a sub-class of that. Since such types are passed by-reference, the
custom de-serializer modifier will correctly determine the "right" class
to use (the declared type, or a subtype of it), and return this... But …
=> fix(java): remove Jackson confusion with certain patterns

tools/jsii-build-tools/bin/package-js, tools/jsii-build-tools/bin/package-python
The @jsii/spec and jsii-spec packages would generate the same build
artifact, causing only one of them (jsii-spec) to be considered. This
ensures distinct artifact names are generated for each.
---
=> fix: generate non-overlapping artifacts

.github/CODEOWNERS
=> chore: update CODEOWNERS for proper ownership

packages/jsii-reflect/lib/type-system.ts
When the `package.json` file is the result of extracting a tarball
obtained from `npm pack`, it may have been processed by `npmjs.com`
during publishing, which can cause the `bundleDependencies` property to
appear with the value `false`. The null-coalescing (`??`) operator does
not rescue this properly and this results in a `TypeError`.
This is fixed by using `||` chaining instead of a null-coalescing, which
rescues from all falsey values in this case.
---
=> fix(reflect): failure to load assembly from "npm pack"

packages/jsii-rosetta/lib/rosetta.ts
An incorrect update to optional chaining changed the criteria for the
target overlap test in Rosetta live conversions and triggered the error
in the regular case instead of only in cases where restricts have to be
enforced.
Reverted to the previous syntax with achieves the correct result.
---
=> fix(rosetta): "Rosetta configured for live conversion to undefined"

superchain/Dockerfile
`/root/.ssh/config` must have the correct permissions or otherwise certain operations such as `git clone` will fail in certain environments.
Fixes #1138
---
=> fix(superchain): bad permissions on ~/.ssh/config

packages/@jsii/runtime/lib/sync-stdio.ts, packages/@jsii/runtime/package.json
When using node >= 13.2, attempts to synchronously read from STDIN often
result in `EAGAIN` being raised. This is due to the STDIN file
descriptor being opened with `O_NONBLOCK`.
This introduces a temporary workaround that catches the EAGAIN exception
and re-attempts reading from STDIN "immediately". While this is not the
ideal solution, it can be done right away and appears to have minimal
impact on the overall performance of applications.
A longer term fix is to move away from synchronous IO operations, but
this is a significantly mroe involved fix and migth be a while before
this can be delivered. The long term solution is tracked in #1142.
Related to aws/aws-cdk#5187
---
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 …
=> fix(runtime): runtime crashes with EAGAIN trying to read from STDIN

packages/jsii-rosetta/lib/commands/extract.ts, packages/jsii-rosetta/lib/languages/csharp.ts, packages/jsii-rosetta/lib/languages/default.ts, packages/jsii-rosetta/lib/languages/java.ts, packages/jsii-rosetta/lib/languages/python.ts, packages/jsii-rosetta/lib/languages/visualize.ts, packages/jsii-rosetta/lib/renderer.ts, packages/jsii-rosetta/test/translations.test.ts, packages/jsii-rosetta/test/translations/calls/default_struct_fields.cs, packages/jsii-rosetta/test/translations/calls/shorthand_property.cs, packages/jsii-rosetta/test/translations/calls/shorthand_property.java, packages/jsii-rosetta/test/translations/calls/shorthand_property.py, packages/jsii-rosetta/test/translations/calls/shorthand_property.ts, packages/jsii-rosetta/test/translations/calls/will_type_deep_structs_directly_if_type_info_is_available.cs, packages/jsii-rosetta/test/translations/classes/class_with_props_argument.cs, packages/jsii-rosetta/test/translations/expressions/struct_assignment.cs, packages/jsii-rosetta/test/translations/interfaces/interface_with_method.cs, packages/jsii-rosetta/test/translations/interfaces/interface_with_method.java, packages/jsii-rosetta/test/translations/interfaces/interface_with_method.ts, packages/jsii-rosetta/test/translations/interfaces/interface_with_props.cs, packages/jsii-rosetta/test/translations/interfaces/interface_with_props.java, packages/jsii-rosetta/test/translations/interfaces/interface_with_props.ts
Behavioral interfaces (`ISomething`) weren't translated at all, and used
to crash the Java translator. Add translations for them.
Make the `jsii-rosetta` command-line tool more robust against errors in
the translator: catch and report the error, instead of crashing.
Add support for shorthand property assignments in object literals
(`someFunction({ foo });`) for Java as well, which wasn't covered
by any test yet.
---
=> fix(rosetta): crashes on behavioral interfaces

packages/@jsii/python-runtime/setup.py
=> fix: depend on python-3.8-supporting version of cattrs

packages/jsii-rosetta/lib/markdown/escapes.ts, packages/jsii-rosetta/lib/markdown/javadoc-renderer.ts, packages/jsii-rosetta/lib/markdown/xml-comment-renderer.ts, packages/jsii-rosetta/package.json, packages/jsii-rosetta/test/markdown/javadoc.test.ts, packages/jsii-rosetta/test/markdown/xmldoccomments.test.ts, yarn.lock
The C# compiler will completely drop comment blocks that aren't
well-formed XML; the `<img>` tag we were outputting wasn't, and
so namespace headings weren't being generated.
At the same time, pay more attention to escaping of arbitrary
HTML and the text inside attributes to minimize the chances
of things going wrong in the future.
---
=> fix(rosetta): properly escape C# comments as XML

packages/@jsii/kernel/lib/serialization.ts, packages/@jsii/kernel/package.json, packages/@jsii/kernel/test/serialization.test.ts, yarn.lock
When deserializing a scalar (string, boolean, number, ...), and receiving a value that is not
a scalar, the error message would not mention what kind of scalar value was required, making
the message less useful than it could be.
Used the description of the type reference in the error message so that the specific scalar
type is direction mentioned in the error message there. The description of the incorrect
value that was received remains unchanged (typically the JSON representation of the value),
and may be improved in a subsequent change.
Improves the situation identified in #1182, however does not fix the whole problem.
--- …
=> fix: poor error message on scalar deserialization type mismatch

superchain/Dockerfile, superchain/README.md, superchain/build-local.sh
This involves installing maven from tarball instead of installing it from
the RPM repositories provided in the AmazonLinux 2 base image. This is
somewhat unfortunate, but is (currently) the only way to get a recent build
of maven without depending on third-party repositories which would need
vetting before they can be safely used.
---
=> feat(superchain): upgrade maven to 3.6.3

packages/@jsii/spec/test/previous-assemblies/0.21.2.jsii.json, packages/@jsii/spec/test/validate-assembly.test.ts
In order to ensure backwards-compatibility against previously generated
assemblies, add a test that validates a random assembly generated by
some semi-arbitrary version of `jsii` (in this case,
`@aws-cdk/aws-ecs-patterns` about version `1.22.0`).
Fixes #1190
---
=> chore: add test loading current assembly

docs/specifications/1-introduction.md, docs/specifications/2-type-system.md, docs/specifications/3-kernel-api.md, docs/specifications/4-standard-compliance-suite.md, docs/specifications/5-new-language-intake.md
This Pull Request introduces a collection of documents under `docs/specification/` that are effectively an RFC for the *jsii* technology.
Since the specified behavior is due to evolve over time, the essential elements to nail down are the following:
1. Design Tenets (in `1-introduction.md`)
1. Updating the specification (in `1-introduction.md`)
1. Standard Compliance Suite (in `4-standard-compliance-suite.md`)
+ This is the core of the compliance & coverage plan
1. New language intake (in `5-new-language-intake.md`)
Once the foundational elements are agreed upon (at least by the core team), the rest of the specification will be open for a review period (like any other RFC), before it is finally merged.
There are presently several distinct documents, but this is merely a way to make the PR …
=> docs(spec): initial pass on a jsii specification

packages/jsii/lib/utils.ts
The context (source file with wiggly lines) was not shown for
diagnostics using the `Message` category. This removes the special
case so that context is always rendered, which ensures a better
experience overall.
Fixes #1174
---
=> fix(jsii): missing context on "Message" diagnostics

packages/@jsii/integ-test/test/build-cdk.test.ts, packages/@jsii/integ-test/utils/index.ts
Change the way we are installing local versions of jsii modules to
ensure that they are present where they are needed during cdk build. A
conflict of versions was causing packaging to stall out during dotnet
build.
---
=> chore: Fix integ test module install strategy

packages/@jsii/integ-test/test/build-cdk.test.ts
Update integ test to include new step for aligning versions. This was
breaking packaging in other languages because it was trying to build
against v0.0.0.
---
=> chore: align versions in build test

packages/@jsii/python-runtime/src/jsii/_kernel/types.py
Adds `BeginResponse` and `SetResponse` to `KernelResponse` union type in
python-runtime. This fixes python-runtime test failures.
---
=> fix(python-runtime): KernelResponse missing types

packages/@jsii/dotnet-analyzers/src/Amazon.JSII.Analyzers.UnitTests/Verifiers/DiagnosticVerifier.cs
Fixes dereference of possible null value in dotnet-analyzers unit test.
---
=> fix(dotnet-analyzers): unit test null reference

docs/specifications/2-type-system.md, packages/@jsii/kernel/lib/objects.ts, packages/@jsii/kernel/lib/serialization.ts, packages/@jsii/kernel/test/serialization.test.ts, packages/@jsii/python-runtime/src/jsii/_reference_map.py, packages/@jsii/python-runtime/tests/README.md
When a "private" type (aka a class that is not visible in the `.jsii`
assembly) is passed from JS to Host through an `any`-typed entity, the
value was serialized by-value, passing only the instance's properties,
and omitting any methods.
This changes the behavior of the `SerializationClass.Any` serializer,
so that when an anonymous object is encountered, if it has a dynamic
getter, setter or any method (including a constructor), it is passed
by-reference instead of by-value.
Fixes aws/aws-cdk#6746
---
=> fix(kernel): "any" serialization breaks private type instances

packages/@scope/jsii-calc-lib/.gitignore, packages/@scope/jsii-calc-lib/package.json, packages/@scope/jsii-calc-lib/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId.csproj, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Internal/DependencyResolution/Anchor.cs, packages/jsii-pacmak/test/expected.jsii-calc-lib/java/pom.xml, packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/$Module.java, packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py, packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/_jsii/__init__.py, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii/lib/assembler.ts, packages/jsii/lib/compiler.ts
When configuring tsc.outDir, the jsii compiler would not look for the
correct source file and captured no types from the module. This
commit fixes this problem by reversing the types attribute in order
to resolve back to the corresponding source file.
Fixes #1273
---
=> fix(jsii): out-of-source builds are broken

packages/jsii-diff/lib/classes-ifaces.ts, packages/jsii-diff/lib/type-analysis.ts, packages/jsii-diff/test/classes.test.ts, packages/jsii-reflect/lib/type.ts
Check that an updated type still extends all of its previous base types,
so that objects of the updated type can still be assigned to variables
or passed into parameters of the declared supertype.
This check would have prevented a deployment failure during a big
refactoring of the CDK.
---
=> fix(diff): check base types

.travis.yml
Change travis CI config to run on release branch in addition to master.
---
=> chore: run travis on release branch

packages/jsii-diff/test/classes.test.ts, packages/jsii-reflect/lib/class.ts
`jsii-diff` is currently throwing on CDK because it thinks interfaces
are being removed from the inheritance chain, even if they've actually
been moved to base classes.
This is because the `ClassType.getInterfaces()` method of `jsii-reflect`
was only returning its direct interfaces, even when run with
`inherited=true` (as opposed to recursively returning the interfaces
all the way up the tree).
Q: Why did you not add a unit test in `jsii-reflect`?
A: The set suite of `jsii-reflect` is quite anemic, and basically only
tests that we can mostly deduce the types that are present in an
assembly. It doesn't have good testing infrastructure for actually
asserting things about arbitrary small pieces of typescript, instead it
mostly works on the generated assemblies from the `jsii-calc` etc. …
=> fix(jsii-diff): detect interfaces inherited via interfaces

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/src/scope/jsii_calc_base_of_base/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc-base/python/src/scope/jsii_calc_base/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_includes_classes/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_only_interface/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/back_references/__init__.py, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/child/__init__.py
chore(python): cosmetic improvements on generated code (#1554)
Add an explicit `-> None` type annotation to the `__init__` function of struct constructors, to be consistent with the recommendations of [PEP-484](https://www.python.org/dev/peps/pep-0484/#the-meaning-of-annotations).
Consistently put a space before the comma in `typing.Mapping[]` arguments. Previously the space was missing in the case of Maps, but present in the case of JSON objects.
The increased consistency of generated code would facilitate future refactorings, as less special cases have to be accounted for.
---
=> chore(python): cosmetic improvements on generated code

buildspec.yaml
Clears the contents of the `dist` directory between builds in
buildspec.yaml. This prevents modules with `v0.0.0` from being
published.
---
=> chore: remove artifacts between builds in CI

buildspec.yaml, package.json, packages/@jsii/dotnet-analyzers/build.sh, packages/@jsii/dotnet-analyzers/package.json, packages/@jsii/dotnet-jsonmodel/build.sh, packages/@jsii/dotnet-jsonmodel/package.json, packages/@jsii/dotnet-runtime/build.sh, packages/@jsii/dotnet-runtime/package.json, packages/@jsii/java-runtime/package.json, packages/@jsii/python-runtime/.gitignore, packages/@jsii/python-runtime/package.json, packages/@jsii/ruby-runtime/package.json, tools/jsii-build-tools/bin/package-dotnet, tools/jsii-build-tools/bin/package-java, tools/jsii-build-tools/bin/package-python, tools/jsii-build-tools/bin/package-ruby
Makes sure no outstanding files containing version `0.0.0` are left to be
copied into the top-level `dist` folder during the packaging phase.
---
=> chore: clean up all dist folders before building release packages

packages/jsii-pacmak/lib/targets/version-utils.ts, packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId.csproj, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId.csproj, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon.JSII.Tests.CalculatorPackageId.csproj, packages/jsii-pacmak/test/targets/version-utils.test.ts
Removes version suffix from version ranges in `.csproj` files generated
by jsii-pacmak.
Dotnet doesn't allow version suffixes that start with a number. Version
ranges by default don't include prereleases so the resolved version is
as intended without the suffix in this case.
---
=> fix(jsii-pacmak): invalid dotnet version suffixes

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/setup.py, packages/jsii-pacmak/test/expected.jsii-calc-base/python/setup.py, packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py, packages/jsii-pacmak/test/expected.jsii-calc/python/setup.py
The Python runtime dependency of generated Python code was incorrectly pinning on the minor, instead of allowing the necessary semver range. Changed the dependency statement from `~=<version>` to the correctly translated caret range.
Fixes #1573
=> fix(python): incorrect dependency on jsii

packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts, packages/jsii-pacmak/lib/util.ts
Instead of having it's own range generation, use the standard
translation used to represent dependencies' ranges for the jsii runtime
version, too.
This removes an exception path, and simplifies the overall code.
---
=> chore(dotnet): standardize generation of jsii runtime dependency

packages/jsii/lib/project-info.ts
chore: improve error message when a non-jsii dependency is not bundled (#1651)
Instead of outputting a very terse 'Unable to locate module', which misleads users into believing
the module cannot be resolved by the compiler, use a longer error message that clearly states the
jsii Assembly could not be located, and that non-jsii dependencies must be bundled.
Fixes #1636
---
=> chore: improve error message when a non-jsii dependency is not bundled

packages/jsii/lib/assembler.ts
fix(jsii): dependency submodules are not tagged (#1663)
The Assembler used to ignore any export that was coined as an external
library import by the TypeScript resolver. However, when traversing
dependencies to collect their submodule structure, everything is an
external library import (which basically is a check that the import
path has a `/node_modules/` in it).
This commit changes the way external imports are skipped so that when
investigating submodules of a particular dependency, a different logic
is used to determine whether they are external (checks that the file
is under the same root; and that it is not under a `/node_modules/`
subdirectory of that root).
> **Note:**
> This is difficult to test for in the contect of a mono-repo, as it
> requires an external dependency …
=> fix(jsii): dependency submodules are not tagged

packages/@jsii/integ-test/test/build-cdk.test.ts
Instead of performing local installs, set the environment variables
needed to direct the CDK build gear to use the locally built tools from
within their location in the mono-repository.
No doing this can cause parts of the tools to be installed from the NPM
package registry, which is not desirable.
---
=> chore: make integration test use local runtimes

packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.FSharp/Amazon.JSII.Runtime.IntegrationTests.FSharp.fsproj, packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.FSharp/Tests.fs, packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.sln, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/FrameworkToJsiiConverter.cs
fix(dotnet): F# dictionaries cause NullReferenceException (#1655)
Perform reflection calls against the resolved `IDictionary` interface
instead of on the raw value type, guaranteeing the expected accessors
are returned.
Fixes #1322
---
=> fix(dotnet): F# dictionaries cause NullReferenceException

packages/@jsii/dotnet-runtime/package.json, packages/@jsii/java-runtime/package.json, packages/@jsii/python-runtime/package.json
Add `package-private` to package steps for all jsii runtime modules so
they can be installed and used during integration testing.
---
=> fix: package runtimes as private for integ test

.prettierrc.yaml, packages/jsii-pacmak/lib/targets/dotnet.ts, packages/jsii-pacmak/lib/targets/java.ts
chore(pacmak): fix local runtime detection (#1679)
Local installs of the java runtime were not properly discovered because
the opportunistic resolution used the incorrect package name (it was
using the older `jsii-java-runtime` name instead of the new
`@jsii/java-runtime` name).
This commit fixes that problem, and also adds an `info` log entry that
indicates a locally built runtime is being used instead of the standard
one from the registry.
Co-Authored-By: rix0rrr@gmail.com
---
=> chore(pacmak): fix local runtime detection

.github/PULL_REQUEST_TEMPLATE.md, .mergify.yml
Use the PR title and body as the commit message instead of using the
GitHUb-provided commit message or the one specified in a markdown
section titled "Commit Message".
This streamlines the contribution workflow while ensuring a consistent
style in commit messages.
---
=> chore: use new mergify commit_message option

packages/@jsii/dotnet-runtime/src/Amazon.JSII.JsonModel/JsonDictionaryBase.cs, packages/@scope/jsii-calc-base-of-base/package.json, packages/@scope/jsii-calc-base/package.json, packages/@scope/jsii-calc-lib/package.json, packages/jsii-calc/package.json, packages/jsii/lib/compiler.ts
Using the `IncrementalBuilder` to compiler code instead of a regular
`Builder` allows saving time when certain files are aloready up-to-date.
The incremental support is only enabled when `--project-references` is
passed to the compiler, as it relies on project references and the
composite model to work it's magic (as far as `tsc` is concerned, the
`incremental` option implies the `composite` option).
---
=> feat(jsii): use incremental builders

packages/@jsii/python-runtime/src/jsii/_kernel/types.py
Remove attempt to use a `attr.Factory` for an optional field that should
anyway have defaulted to a plain `None` value.
---
=> fix(python): no overload variant of "Factory" matches argument type "object"

packages/@jsii/python-runtime/bin/generate-calc, packages/@jsii/python-runtime/package.json, packages/@jsii/python-runtime/requirements.txt, packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py, packages/@jsii/python-runtime/tests/test_compliance.py, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Isomorphism.cs, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IsomorphismProxy.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Isomorphism.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Within the `__init__` of a class, reading `self` back from the JS
process would result in a proxy object created for the parent type,
instead of returning `self`. This is because the `JSIIMeta` metaclass
only registered the instance in the rerefence map **after** the
constructor had returned.
This adds an additional registration point right after the `create` API
returned from the kernel, making the reference available as early as it
can possibly be known.
Fixes aws/aws-cdk#8262
---
=> fix(python): reference isomorphism is broken within __init__

packages/jsii/lib/project-info.ts
As it turns out,
validating assemblies takes a non-trivial percentage of all time spent on JSII compilation.
Since the feature is not very important right now,
turn it off to speed-up builds.
---
=> feat: turn off assembly validation

packages/@jsii/kernel/lib/kernel.ts, packages/@jsii/kernel/test/kernel.test.ts, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/UmaskCheck.cs, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/UmaskCheck.java, packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt, packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
In it's wisdom, `npm install` does override the process' `umask` to
`0o022` before unpackging the tarball, to ensure the produced install
has the kind of permissions that one would expect, regardless of the
system-configured `umask`.
Because `@jsii/kernel` did not reproduce this behavior, loaded libraries
could be unpacked with unexpectedly tight permissions, leading to weird
issues when those files were used in contexts that required those
permissions. For example, this is the cause of aws/aws-cdk#8233.
Fixes #1765
---
=> fix(kernel): tarball unpacking does not behave like 'npm install'

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/lib/util.ts, packages/jsii-pacmak/package.json, packages/jsii-pacmak/test/targets/python.test.ts, superchain/Dockerfile
The failure is because of intermittent unavailability of black or one of
its packages from the PyPI index.
Instead, install back into the environment, i.e., superchain, and use
that.
---
=> fix(pacmak): python pack fails when installing 'black' via pip

packages/jsii-pacmak/lib/targets/python.ts
The root cause seems to be that the async APIs in Node's fs modules
isn't strictly single threaded.
When packed over several packages, pacmak schedules these in parallel,
creating a race condition on the local cache for Python Black.
All threads thrash to try and set up the package directory and one of
them fails.
The fix is to introduce a process wide promise that awaits until the
Python Black is fully set up.
Testing
Unit tests for such race conditions are hard to write correctly. This
has been verified manually by running against 10 CDK packages at a time.
I was able to confirm that the issue does show up consistently without
this fix and the fix works correctly.
--- …
=> fix(pacmak): race condition in python packing when run over multiple packages

packages/@jsii/dotnet-runtime/.npmignore
`.npmignore` inside of the @jsii/dotnet-runtime package excluded
everything, which broke local references to the package when it wasn't
in the local nuget cache.
This makes sure the package binaries are included and available for
referencing locally during integration tests.
---
=> chore(dotnet-runtime): exclusion of built binaries

.github/workflows/yarn-upgrade.yml
This makes sure our lockfile remains up-to-date, including for
transitive dependencies, and reduces the likelihood of receiving a
sevurity notification from GitHub for one of those.
---
=> chore: add workflow to run "yarn upgrade" periodically

packages/@scope/jsii-calc-lib/test/assembly.jsii, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/.jsii, packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii, packages/jsii/lib/assembler.ts
Those were previously not recorded, although the assembly schema supports
recording this information.
---
=> fix(jsii): document location of initializers in source

packages/jsii-pacmak/lib/targets/java.ts
It was generated from a path, but the value is not allowed to contain any of
`\`, `/`, `:`, `"`, `<`, `>`, `|`, `?`, `*`
---
=> fix(java): user.xml repository ID was not sanitized

packages/jsii/lib/assembler.ts, packages/jsii/lib/helpers.ts, packages/jsii/test/export-specifier.test.ts
When specific symbols are exported from a module using the
*ExportDeclaration* syntax:
```ts
export { Foo } from './foo';
```
Those declarations would not be processed at all, because they lack the
`ts.ModifierFlags.Export` modifier (which is to be expected from a
declaration that **is** an export statement).
Added the necessary code (and a test) to ensure these statements are
correctly detected, and the exported symbols are correctly processed
into the output assembly.
Fixes #1818
---
=> fix(jsii): selective exports declarations are ignored

packages/jsii-rosetta/lib/languages/python.ts, packages/jsii-rosetta/lib/renderer.ts, packages/jsii-rosetta/test/translations/statements/vararg_any_call.cs, packages/jsii-rosetta/test/translations/statements/vararg_any_call.java, packages/jsii-rosetta/test/translations/statements/vararg_any_call.py, packages/jsii-rosetta/test/translations/statements/vararg_any_call.ts
When processing function calls, the signature of the function was not
considered when it was available, and an object literal used as the
final argument of a variadic call would be rendered as keyword arguments
when this is actually not a correct way to render variadic values.
This change attempts to read the resolved signature of the function
beging called, in order to correctly render variadic values.
Fixes #1821
---
=> fix(rosetta): variadic arguments may use kwargs syntax in Python

.github/workflows/main.yml, packages/@jsii/dotnet-runtime-test/package.json, packages/@jsii/dotnet-runtime/package.json, packages/@jsii/java-runtime-test/package.json, packages/@jsii/java-runtime/package.json, packages/@jsii/runtime/package.json, packages/jsii-pacmak/package.json, packages/jsii-rosetta/lib/typescript/ts-compiler.ts, packages/jsii-rosetta/test/jsii/assemblies.test.ts, packages/jsii-rosetta/test/translations.test.ts
The root file was located by comparing file paths in a way that was not
adjusting path separators for Windows, and the result was inability to
match normalized paths with Unix-style ones.
This normalizes paths before attempting to match them, so that the match
can succeed.
---
=> fix(rosetta): OOpsie -- couldn't find root file back on Windows

packages/jsii-rosetta/lib/languages/python.ts, packages/jsii-rosetta/test/translations/identifiers/keyword.cs, packages/jsii-rosetta/test/translations/identifiers/keyword.java, packages/jsii-rosetta/test/translations/identifiers/keyword.py, packages/jsii-rosetta/test/translations/identifiers/keyword.ts
Replace all 'lambda' identifiers with 'awslambda'
fixes https://github.com/aws/aws-cdk/issues/9169
---
=> fix(rosetta): use of keyword 'lambda' produces invalid Python code

eslint-config.yaml, packages/jsii-rosetta/lib/jsii/assemblies.ts
Either linter rules are enforced or relaxed, nothing inbetween.
Converts existing warn rules to error or turn off.
---
=> chore: no more eslint warn rules

.mergify/config.yml
The Python test matcher was not working because Python is currently
last in the test chain, and hence the version is not followed by a
white space.
---
=> chore: fix mergify configuration

packages/jsii/lib/validator.ts, packages/jsii/test/__snapshots__/negatives.test.js.snap, packages/jsii/test/negatives/neg.override-changes-visibility.ts
Since C# does not allow changing the visibility of a member when
overriding it, added a check to ensure nobody attempts to make a
protected member public when overriding it.
This is a somewhat common pitfall for users (as seen for example in
aws/aws-cdk#9616), and the check will allow faster detection and
correction (i.e: at compilation time instead of during `jsii-pacmak`).
---
=> feat(jsii): prohibit changing visibility when overriding

docs/configuration.md, packages/@jsii/kernel/test/kernel.test.ts, packages/jsii-calc/package.json, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
Setting the `jsii.targets.python.classifiers` property in `package.json`
to an array of strings will trigger insertion of those values in the
`classifiers` of the generated python package.
Classifiers are de-duplicated and normalized in `setup.py`. Some
classifiers prefixes are considered "managed" (an appropriate value is
automatically determined for those based on the package's metadata), and
while configuring those will not cause `jsii-pacmak` to fail, a warning
will be emitted as manually specifying any of those is usually a
Bad Idea™:
- `Development Status ::`
- `License ::`
- `Operating System ::`
- `Typing ::`
Existing (i.e: valid) trove classifiers are mastered in the
[`trove-classifiers`](https://github.com/pypa/trove-classifiers) PyPA
package.
This contributes to aws/cdk-ops#393 …
=> feat(python): allow setting additional trove classifiers

superchain/Dockerfile
The version of awscli in the yum repository appears to be somewhat outdated, and lacks
support for certain recent services and features. Moving to the recommended way to
install (using pip) will ensure the most recent release is installed every time the
image is re-built.
The recommended install/upgrade instructions are hosted at:
https://docs.aws.amazon.com/cli/latest/userguide/install-linux-al2017.html#install-amazon-linux-pip
Fixes #1905
---
=> chore(superchain): install awscli from pip instead of yum

packages/jsii-pacmak/lib/targets/golang/module.ts, packages/jsii-pacmak/lib/targets/golang/types/index.ts, packages/jsii-pacmak/lib/targets/golang/types/struct.ts, packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap, packages/jsii-reflect/lib/type.ts
Implements code generation logic for datatype interfaces, with emit method generating both a Go interface and Go struct and implementation of the interface.
TODO: isDataType() in jsii-reflect seems wrong -- would be nice to
leverage this method in module.ts.
---
=> chore(golang): generate datatype interfaces

.github/workflows/main.yml, packages/jsii-rosetta/lib/tablets/tablets.ts
Since this integration test is rather slow (generating all CDK in a
2-CPU instance), focus it on running `jsii-rosetta` and `jsii-pacmak`
only on the `monocdk-experiment` package (and it's future `aws-cdk-lib`
name, for good measure).
This hopefully is going to allow the tests to return *much* faster, at
least until we can safely offload this to a self-hosted github runner.
---
=> chore: dial down integration test

packages/jsii-pacmak/lib/targets/golang/base-package.ts, packages/jsii-pacmak/lib/targets/golang/module.ts, packages/jsii-pacmak/lib/targets/golang/package.ts, packages/jsii-pacmak/lib/targets/golang/types/class.ts, packages/jsii-pacmak/lib/targets/golang/types/enum.ts, packages/jsii-pacmak/lib/targets/golang/types/go-type-reference.ts, packages/jsii-pacmak/lib/targets/golang/types/go-type.ts, packages/jsii-pacmak/lib/targets/golang/types/interface.ts, packages/jsii-pacmak/lib/targets/golang/types/struct.ts, packages/jsii-pacmak/lib/targets/golang/util.ts
Since `Module` has a somewhat special meaning in Go due to the `go mod` dependency management system, the `Module` class is being renamed to `BasePackage`, and `Submodule` to `InternalPackage`. This reserves the `Module` name for code related to dependency management.
---
=> chore: rename Module, Submodule

yarn.lock
This version is no longer susceptible to CVE-2020-8116.
---
=> chore: upgrade to dot-prop 4.2.1

packages/jsii-pacmak/lib/targets/golang/types/class.ts, packages/jsii-pacmak/lib/targets/golang/types/go-type.ts, packages/jsii-pacmak/lib/targets/golang/types/interface.ts, packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
Interfaces extended by other interfaces will be generated as embedded interfaces; for datatype interfaces, the properties will be flattened by the struct proxy. Also add code generation for setter methods on classes.
---
=> chore(go): code generation for extensions

packages/jsii-pacmak/lib/targets/golang/types/class.ts, packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
Previously, GoClass methods were only being populated by methods
directly on the parent type. Calling `getMethods` with true also
gets any inherited methods, which should cause the class to correctly
implement its corresponding interface.
---
=> chore(go): generate inherited methods on class

packages/jsii-pacmak/lib/targets/golang/types/class.ts, packages/jsii-pacmak/lib/targets/golang/types/go-type.ts, packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
Previously, datatype structs were being embedded in the struct
interface. This fix moves the logic for looking up inherited interfaces
into classes only.
---
=> fix(go): Only embed behavioral interfaces

packages/@jsii/kernel/test/kernel.test.ts, packages/@scope/jsii-calc-base-of-base/package.json, packages/@scope/jsii-calc-base-of-base/test/assembly.jsii, packages/@scope/jsii-calc-base/package.json, packages/@scope/jsii-calc-base/test/assembly.jsii, packages/@scope/jsii-calc-lib/package.json, packages/@scope/jsii-calc-lib/test/assembly.jsii, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/golang.ts, packages/jsii-pacmak/lib/targets/golang/package.ts, packages/jsii-pacmak/lib/targets/golang/runtime.ts, packages/jsii-pacmak/lib/targets/golang/types/class.ts, packages/jsii-pacmak/lib/targets/golang/types/go-type-reference.ts, packages/jsii-pacmak/lib/targets/golang/types/go-type.ts, packages/jsii-pacmak/lib/targets/golang/types/interface.ts, packages/jsii-pacmak/lib/targets/golang/util.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Fixes a number of compiler bugs and adds support for external package
dependency resolution.
Changes package file layout to prevent extraneous directory nesting.
Adds logic to `RootPackage` to be able to resolve types within external
jsii modules. Also adds a `moduleName` field to the go target jsii
config to allow imports across packages to resolve correctly.
Changes logic of embedded interfaces to correctly resolve using local
names and bubble embedded interfaces up to the package dependencies
array to make sure their imports are resolved.
Adds utility function for substituting reserved words in
variable/function argument names. Some examples within jsii-calc have
arguments named `map` which caused go compiler errors. More reserved
words should be added to a central list for this …
=> feat(pacmak): go module resolution & compiler fixes

packages/@jsii/kernel/test/kernel.test.ts, packages/jsii-calc/package.json, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/golang/package.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
When generating import statements within go code, if the package was a
child of the package currently being generated, the import statement
would not include the module name.
When a package is part of a module though this caused invalid imports.
So for all package import statements moduleNames are now included when
provided in the jsii config.
---
=> fix(pacmak): go bad local package imports

packages/jsii-pacmak/lib/targets/golang.ts, packages/jsii-pacmak/lib/targets/golang/documentation.ts, packages/jsii-pacmak/lib/targets/golang/emit-context.ts, packages/jsii-pacmak/lib/targets/golang/package.ts, packages/jsii-pacmak/lib/targets/golang/types/class.ts, packages/jsii-pacmak/lib/targets/golang/types/enum.ts, packages/jsii-pacmak/lib/targets/golang/types/go-type.ts, packages/jsii-pacmak/lib/targets/golang/types/interface.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap, packages/jsii-reflect/lib/docs.ts, packages/jsii-reflect/test/type-system.test.ts
Generates jsii docs on all target types. Does not include docs for generated exported methods (e.g. getters/setters).
TODO: Still need generate examples using the rosetta library.
---
=> chore: generate docs

superchain/Dockerfile, superchain/README.md
Adds go toolchain to superchain Dockerfile to make available for go
runtime library development.
---
=> feat: add go to superchain

packages/jsii-pacmak/lib/targets/golang/documentation.ts
Removes a `console.log` statement from the go `Documentation` class that
was logging to `Rosetta` instance fo each emit invocation. This was
added to correct a lint error that the instances was not used that
wasn't easily surpressed.
---
=> chore: remove console.log from go pacmak gen

packages/jsii-pacmak/lib/targets/golang/package.ts, packages/jsii-pacmak/lib/targets/golang/runtime.ts, packages/jsii-pacmak/lib/targets/golang/types/class.ts, packages/jsii-pacmak/lib/targets/golang/types/enum.ts, packages/jsii-pacmak/lib/targets/golang/types/go-type-reference.ts, packages/jsii-pacmak/lib/targets/golang/types/go-type.ts, packages/jsii-pacmak/lib/targets/golang/types/index.ts, packages/jsii-pacmak/lib/targets/golang/types/interface.ts, packages/jsii-pacmak/lib/targets/golang/types/type-field.ts, packages/jsii-pacmak/lib/targets/golang/types/type-member.ts, packages/jsii-pacmak/lib/targets/golang/util.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Enforces that all TypeMembers have a `returnType` getter for consistency. Also renames various properties to be more intuitive and to reduce stutter.
---
=> refactor: make Go type members have consistent returnType getters

.github/workflows/yarn-upgrade.yml
Production dependencies (i.e: dependencies that are not
`devDependencies`) can generally not be "safely" updated to the latest
(major) release without risking subtle breakage (due to behavior changes
that may not be caught by unit tests).
In order to have a safer general mode of operation, the
`yarn-upgrade.yml` workflow will now use the "minor" (instead of
"latest") target for any production dependency of any package in the
repository (a dependency is minor-pinned for the whole repository if any
of the packages in the repository declares a "production" dependency on
it).
---
=> chore: make yarn-upgrade use "minor" target for prod deps

packages/@jsii/go-runtime/jsii-calc-test/main.go, packages/@jsii/go-runtime/package.json, packages/jsii-pacmak/lib/targets/go/runtime.ts, packages/jsii-pacmak/lib/targets/go/types/class.ts, packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts, packages/jsii-pacmak/lib/targets/go/types/go-type.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Fixes go method code generation to not emit a return statement when the
return type is `void`. Adds logic to fix go compile errors on
getters/setters that refer to recursive type properties. Meaning, if a
struct contains a property that the type of the struct itself, the type
of the property in Go is a pointer to the struct. Getters and setters
now reflect this.
Update test step to include compilation of all generated jsii-calc
modules since all compile errors are fixed.
fix:  #2009
---
=> fix(go): correctly handle void return types

.github/workflows/main.yml, packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.FSharp/Amazon.JSII.Runtime.IntegrationTests.FSharp.fsproj, packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj
Since .NET 5 is due for GA later this year, start testing on the current release candidate to ensure everything works smoothly.
---
=> chore: start testing with .NET 5

.github/workflows/main.yml
It is currently broken because the latest version of `yargs` (16.0.3)
introduced an `exports` map in it's `package.json` that prevents access
to it's `package.json`. This is used by `decdk` when trying to load the
type system, and currently fails.
The breakage only occurs when using `node >= 12` (as the `exports`
map feature was introduced there), so this PR changes the node runtime
used to run integration tests from `node 12` to `node 10`.
---
=> chore: run integration test with node 10

packages/@jsii/dotnet-runtime-test/generate.sh, packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.FSharp/Amazon.JSII.Runtime.IntegrationTests.FSharp.fsproj, packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.sln, packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj, packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Client.cs, packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java, packages/@jsii/python-runtime/tests/test_compliance.py, packages/jsii-calc/lib/date.ts, packages/jsii-calc/lib/index.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
When a ISO-8601-encoded date is passed from JavaScript to the .NET app,
the JSON deserializer would interpret that as a `DateTime` instead of
passing the string un-touched. This is a problem, since the jsii kernel
protocol has a dedicated wrapper key for DateTime values (`$jsii$date`).
This PR adds a compliance test around this particular scenario, and
disabled `DateTime` handling from the standard deserializer (the wrapped
values are still processed correctly).
> This PR also changes the way the .NET test package generates the
> tested libraries (`jsii-calc` & dependencies) so that instead of
> generating NuGet packages, it only generates C# projects. This makes
> the experience of debugging the tests **much** nicer, and reduces the
> likelihood of cached build artifacts getting in the …
=> fix(dontet): iso-8601 date strings get turned into DateTime

packages/codemaker/lib/codemaker.ts, packages/jsii-pacmak/lib/targets/go.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Since `gofmt` indents using tabulations, reproduce this behvaior on
generated code so it looks more idiomatic.
---
=> chore(pacmak/go): indent using tabs instead of spaces

packages/@jsii/go-runtime/.gitignore, packages/@jsii/go-runtime/build-tools/gen.ts, packages/@jsii/go-runtime/jsii-calc-test/main.go, packages/@jsii/go-runtime/jsii-experimental/client.go, packages/@jsii/go-runtime/jsii-experimental/client_test.go, packages/@jsii/go-runtime/jsii-experimental/runtime.go, packages/@jsii/go-runtime/package.json
Bundles the `@jsii/runtime` application within the go runtime library.
This ships the necessary files as byte slices in
`embeddedruntime.generated.go`. The `client` initializer will un-pack
this into a temporary directory (cleaned up by `client.Close()`) and run
that, unless the user specified the `JSII_RUNTIME` environment variable
(in which case, that command is used instead).
The `client` also assigns `JSII_AGENT` to a string representing the `go`
stack version used during build (`runtime.Version()`), the operating
system under which the application is running and the CPU architecture.
The string is formatted as `VERSION/OS/ARCH`.
A new `runtime.go` was introduced that manages a singleton `client`
instance and exports a `Close` function that can be invoked to
gracefully clean up the …
=> feat(go): embed jsii runtime application

packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs, packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts, packages/jsii-pacmak/lib/targets/dotnet/dotnetruntimegenerator.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
The generated code had a number of quirks related to nullability
annotations (`?` and `!`) that resulted in sometimes abundant warnings
emitted during the compilation of the generated code. This makes the
necessary changes to correctly reflect that method arguments can be
`null` in the `DeptyBase` methods; and adds the necessary `?` and `!`
where they were previously missing.
This results in much fewer compilation warnings being emitted while
compiling `jsii-calc` and dependencies (the remaining warnings are
actually "legitimate" in the sense that they are the result of
us/users making questionable naming choices).
--- …
=> fix(dotnet): abundant nullability warnings in generated code

packages/@jsii/java-runtime/pom.xml.t.js
Current `2.12.0-rc1` is breaking source compatibility due to the removal of a checked
exception from `ObjectMapper#treeToValue()`.
See: FasterXML/jackson-databind#2878.
---
Took the opportunity to also tidy up other version constraints (simplifying the
right hand side of the ranges to the shorter form while making them prerelease-safe),
and upgraded `junit.version` while I was there).
The Jackson version for `core` and `databind` where unified as they ought to
always match and previously were separated only because a security patch
was released to one but not the other (and we wanted to mandate it was present).
--- …
=> chore(runtime/java): apply tighter pin on Jackson

packages/jsii-rosetta/lib/translate.ts, packages/jsii-rosetta/lib/typescript/ts-compiler.ts
Streamline the in-memory compiler host by avoiding unnecessary use of
`.bind` when using the "standard" host's functions; and focusing the
diagnostic message gathering only on the example-containing source file
instead of traversing all source files considered in the compilation
step (which would include all involved declarations files, too).
This would make the overall compilation execution faster (although this
does not miracoulously make it extremely fast - there is still some work
involved that takes a while in the compiler itself).
---
=> chore(rosetta): streamline TypeScript compiler API usage

packages/jsii-rosetta/lib/util.ts
When running with `--compile`, problem markers could end up duplicated.
This particularly affected problem markers reporting use of unsupported
language features in examples, which would have been repeated once per
target language.
This adds the necessary hook to de-duplicate diagnostics before
rendering them to the user interface.
---
=> fix(rosetta): duplicated problem markers

packages/jsii-pacmak/lib/targets/go/package.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
fix(go): Submodule File Paths
Fixes go code generation for submodules. File paths were only nesting
for immediate children and not deeply nested ones.
---
=> fix(go): Submodule File Paths

.github/workflows/main.yml
Allow 2 concurrent builds to improve execution speed without risking too much pressure on memory in the GitHub Actions workers.
---
=> chore: increase concurrency of integration test

packages/jsii-calc/lib/compliance.ts, packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts, packages/jsii-pacmak/lib/targets/go/types/class.ts, packages/jsii-pacmak/lib/targets/go/types/go-type.ts, packages/jsii-pacmak/lib/targets/go/types/type-member.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Previously, we were generating setters for readonly properties, as well as including static properties as part of a class interface and implementation. This fixes the property generation to omit the setter declarations/implementations for readonly properties. It also generates static properties as the package level.
Fixes #2093
---
=> fix(go): fix generation of readonly and static properties

.github/workflows/docker-images.yml
The head ref isn't always available from `origin` (e.g: when the PR is from a fork). Use `HEAD` instead, even though this might actually result in the occasional false positive (which is OK - false negatives would be what's problematic).
---
=> chore: tune diff-test for superchain build test

packages/jsii/lib/compiler.ts
Stop setting `stipInternal: true` in `tsconfig.json` files, as this makes it impossible
to mark intentionally unexported types as `@internal` without causing downstream
compilation failures due to missing type declarations.
Fixes #1947
Related to #1830 
---
=> fix(jsii): annotation '@internal' causes missing type declarations downstream

packages/@jsii/kernel/jest.config.ts, packages/codemaker/jest.config.ts, packages/jsii-config/jest.config.ts, packages/jsii-diff/jest.config.ts, packages/jsii-rosetta/jest.config.ts, packages/jsii/jest.config.ts, packages/oo-ascii-tree/jest.config.ts
Apparently, CodePipeline does not correctly read them out from GitHub,
and this results in text files containing the referent path. How
Windows-esque!
---
=> chore: stop using symlinks for jest config

packages/jsii/lib/assembler.ts, packages/jsii/lib/jsii-diagnostic.ts
This is used a lot in order to create the location pointer for diagnostics message,
and the typescript compiler API provides a convenient way to extract the name of a
declaration without having to escape type checking.
---
=> chore: improve code to get symbol/node names

packages/@jsii/go-runtime/jsii-experimental/api.go, packages/@jsii/go-runtime/jsii-experimental/client.go, packages/@jsii/go-runtime/jsii-experimental/runtime.go, packages/jsii-pacmak/lib/targets/go/runtime/constants.ts, packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Fixes https://github.com/aws/jsii/issues/2128
---
=> chore(go): support get/set kernel API in go runtime

packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Deputy/DeputyBaseTests.cs, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/AnonymousObject.cs, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
In order to allow converting an opaque object instance to an arbitrary
(jsii-managed) interface type, the `UnsafeCase` operation may be used to
instantiate a proxy while bypassing all type consistency checks.
This is similar to using `as any` or `as T` in TypeScript, meaning that
if the user performs a cast to an incorrect/unsupported type, undefined
behavior follows.
This would unblock certain specific use-case scenarios that static
languages render difficult to enact, such as the one described in
aws/aws-cdk#3284.
In particular, this is the only way out until aws/aws-cdk-rfcs#193
is delivered, for dealing with instances of interfaces returned through
a type union API.
--- …
=> feat(dotnet): introduce `UnsafeCast<T>()` method

.github/workflows/main.yml
The `set-env` and `add-path` commands are deprecated as a consequence of
CVE-2020-15228. The replacement operates by writing text in special
files, the path of which is exposed by special environment variables.
Deprecation notice: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
---
=> chore(actions): stop using set-env and add-path

.github/workflows/main.yml
The `set-env` and `add-path` commands are deprecated as a consequence of
CVE-2020-15228. The replacement operates by writing text in special
files, the path of which is exposed by special environment variables.
Deprecation notice: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
---
=> chore(actions): stop using set-env and add-path (#2177)

packages/@jsii/python-runtime/setup.py
`cattrs>=1.1.0` dropped support for python 3.6, and added support for
python 3.9. Consequently, declare a dependency on `cattrs~=1.0.0` when
the python runtime is `< 3.7`, and on `cattrs~=1.1.0` when the python
runtime is `>= 3.7` in order to get the correct dependency brought in.
Fixes aws/aws-cdk#11219
Caused by https://github.com/Tinche/cattrs/commit/eb454d45ee198ef008b92a490ec67e1ed154b26f
---
=> fix(python): update `cattrs` dependency specification

.github/workflows/main.yml, .mergify/config.yml, packages/@jsii/python-runtime/setup.py, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
It is apparently now supported by cattrs so we can finally start testing
against it, too.
---
=> chore: add Python 3.9 to test matrix

.github/workflows/main.yml, .mergify/config.yml
General availability was announced: https://dotnet.microsoft.com/download/dotnet/5.0
---
=> chore: update test matrix to .NET5 release

packages/@jsii/java-runtime/pom.xml.t.js, packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
Guards against the `IllegalStateException` that will be thrown upon
attempting to remove a shutdown hook during VM shut down. In such cases,
the removal is no longer possible nor necessary, so the exception can be
safely ignored.
Fixes #2303
---
=> fix(java): exception is logged when Java VM is shutting down

superchain/Dockerfile
This would posisbly cause the .NET SDK to be upgraded to a version that is significantly
more recent than it should be (i.e: take us from .NET Core 3.1 to .NET 5.0), which is
undesirable and can cause problems down the line (in particular, it currently fails to
update the fsharp distribution because this is not yet available on the mirrors).
---
=> chore: stop running yarn upgrade at end of image build

packages/jsii/lib/assembler.ts
When the source code does not compile due to type checking errors, the
TypeScript program model may include "error type" placeholders, to allow
the compiler to provide feedback on subsequent code. The placeholder
types do not have a symbol (quite intentionally!), and will hence cause
a failure in the `Assembler.validateHeritageClauses` method.
This change makes the code more defensive so it does not crash on this
symptom, and does not report an additional error either (the TypeScript
compiler will have done this for us already).
The bug is more likely to hit users operating under `--watch`, as the
type checker is more likely to be able to insert placeholder types in
this case, as a previous version of the program might be used as a
crutch to understand the error's context... This makes …
=> fix(jsii): unknown error in Assembler._validateHeritageClauses

packages/jsii/bin/jsii.ts, packages/jsii/lib/compiler.ts
There were two bugs pertaining to invoking `jsii` with a project root
argument (e.g: `jsii path/to/project`):
- The positional argument was not correctly processed by `yargs` because
it was not mentionned in the `command` description.
- The project reference resolution code did not resolve relative paths
from the correct starting point (`cwd` instead of the project root),
resulting in compiler errors.
This change fixes both.
---
=> fix(jsii): errors when invoking with a project root argument

.github/workflows/push-go-runtime.yml
Fixes working directory syntax for go runtime push action by using
context instead of env var.
---
=> fix: bad working directory in go runtime push

gh-pages/content/index.md
Fixes a typo on the main page of [aws.github.io/jsii](aws.github.io/jsii).
---
=> docs: fix typo in index.md

CHANGELOG.md, lerna.json, packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
Corrected usage of `process.terminate` to remove unexpected `timeout`
argument. Not sure how this did not surface in integration tests (will
investigate later).
Fixes #2398
---
=> fix(python): process.terminate() got an unexpected keyword argument 'timeout'

gh-pages/mkdocs.yml
Updates docs copyright year (2020 -> 2021)
---
=> docs: update copyright year

packages/@jsii/go-runtime/go.mod, packages/@jsii/go-runtime/jsii-calc-test/main_test.go, packages/@jsii/go-runtime/jsii-runtime-go/api.go, packages/@jsii/go-runtime/jsii-runtime-go/client.go, packages/@jsii/go-runtime/jsii-runtime-go/client_test.go, packages/@jsii/go-runtime/jsii-runtime-go/runtime.go, packages/@jsii/go-runtime/package.json, packages/@jsii/kernel/test/kernel.test.ts, packages/@scope/jsii-calc-base-of-base/package.json, packages/@scope/jsii-calc-base-of-base/test/assembly.jsii, packages/@scope/jsii-calc-base/package.json, packages/@scope/jsii-calc-base/test/assembly.jsii, packages/@scope/jsii-calc-lib/package.json, packages/@scope/jsii-calc-lib/test/assembly.jsii, packages/jsii-calc/package.json, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
A collection of mostly cosmetic changes aimed at making the code closer
to "release" status, reducing the risk of inadvertently creating dependencies
on implementation details, and ensuring naming is "idiomatic" looking.
- Hidden types that do not need to be exported (in particular, all the
request and response types from `api.go`)
- Renamed members to match go's naming conventions more closely. This
means acronyms are fully upper-cased (e.g `Api` became `API`, etc...)
- Avoided abbreviating struct member names in favor of a more
descriptive naming. This affects relatively few properties.
- Added minimal documentation strings on exported functions (and some
hidden functions, too). At this stage all exported symbols have "some"
documentation string on them.
- Removed the `aws-cdk` element …
=> chore(go): minor refactors in go runtime

packages/jsii-pacmak/lib/targets/go.ts, packages/jsii-pacmak/lib/targets/go/package.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
According to the [go modules spec], starting from 2.0.0, module names must include
A “major version suffix” (e.g. `/v2`).
[go modules spec]: https://golang.org/ref/mod#major-version-suffixes
Fixes https://github.com/aws/jsii/issues/2506
This commit also fixes #2509 by deleting the `local.go.sum` file from the output.
---
=> fix(go): major version suffix is missing in module names for >=v2

packages/jsii-pacmak/lib/targets/go/package.ts, packages/jsii-pacmak/lib/targets/go/version-file.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Since golang version isn't available anywhere inside the module, we embed a version file so that consumers can access the version. 
This is needed for publishing [go modules](https://github.com/aws/jsii-release/pull/23) using `jsii-release` without the user having to supply the version externally.
---
=> feat(go): version file in the generated module directory

packages/@jsii/dotnet-runtime-test/package.json, packages/@jsii/go-runtime/go.mod, packages/@jsii/go-runtime/jsii-calc-test/main_test.go, packages/@jsii/go-runtime/package.json, packages/@jsii/java-runtime-test/package.json, packages/@jsii/kernel/package.json, packages/@jsii/python-runtime/package.json, packages/@jsii/runtime/package.json, packages/@scope/jsii-calc-base-of-base/package.json, packages/@scope/jsii-calc-base-of-base/test/assembly.jsii, packages/@scope/jsii-calc-base/package.json, packages/@scope/jsii-calc-base/test/assembly.jsii, packages/@scope/jsii-calc-lib/package.json, packages/@scope/jsii-calc-lib/test/assembly.jsii, packages/jsii-calc/package.json, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/go/package.ts, packages/jsii-pacmak/package.json, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap, packages/jsii-reflect/package.json, scripts/align-version.js
The major version suffix introduced in #2507 was added at the end of the full module name, but for submodules, the suffix is needed only after the root package name.
Additionally, the `_init_` import failed to include the major version suffix as well.
In order to cover these cases in tests, change the version of `jsii-calc` to `3.20.120` and `@scope/jsii-calc-base-of-base` to `2.1.1` so that it will be a MV larger then 2.0 and we can verify this works both from top-level modules, submodules and transitive local dependencies.
Fixes #2507
---
=> fix(go): invalid major version suffix for submodules and jsii init

packages/jsii-pacmak/lib/targets/go.ts, packages/jsii-pacmak/package.json, packages/jsii-rosetta/package.json, yarn.lock
isaacs/node-graceful-fs#204 prevents `graceful-fs` (a dependency of
`fs-extra`) from loading in a worker thread when using node < 12. The
issue affects only version `4.2.5`, so pinning both `jsii-rosetta` and
`jsii-pacmak` (both of which may use worker threads when available) to
the last known good version: `4.2.4`, until a fixed release of
`graceful-fs` is released.
---
Note - this replaces the solution introduced in 5822e48 (#2550), which
turned out to not be complete enough (I mistakenly through the issue was
introduced by a recent change in our code, while it was triggered in other
places, actually due to a recent release of `graceful-fs`).
--- …
=> fix(rosetta,pacmak): TypeError in node 10 with --experimental-worker

packages/jsii-calc/lib/documented.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Since docstrings are now rendered inside single-quoted multiline strings to allow the docstring itself to include example code with double-quoted multiline string literals. Those are the ones produced by rosetta for python.
Fixes #2569
---
=> fix(pacmak): examples with multi-line strings produce invalid python docstrings

gh-pages/content/specification/2-type-system.md, packages/@jsii/go-runtime/jsii-calc-test/main_test.go, packages/@jsii/go-runtime/jsii-runtime-go/api.go, packages/@jsii/go-runtime/jsii-runtime-go/runtime.go, packages/@jsii/go-runtime/jsii-runtime-go/type-registry.go
Enum values are represented in the jsii kernel as `{ "$jsii.enum": "fqn/member" }`, so we need to marshal/unmarshall them based on this encoding.
Change the type registry to capture a mapping between FQN to enum member consts and type to enum FQNs.
Fixes #2534
Co-authored-by: Romain Marcadier <rmuller@amazon.com>
---
=> fix(go-runtime): enums are not encoded/decoded correctly

packages/@jsii/go-runtime/.gitignore, packages/@jsii/go-runtime/build-tools/gen.ts, packages/@jsii/go-runtime/jsii-runtime-go/client.go
In order to avoid wasting cycles on every application start, moved the
sanity test for embedded code being correct (checking size & SHA512 hash
matches expected values) to a new `_test.go` file, so this is run by
`go test`, but not during the actual runtime of any consuming app.
---
=> chore(go): extract embedded runtime sanity check to _test file

packages/@jsii/go-runtime/build-tools/gen-calc.ts, packages/jsii-pacmak/lib/targets/go/package.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
This helps IDEs (eg: GoLand from JetBrains, etc..) be more comfortable
with the codebase, as indirect dependencies are correctly mapped. This
generates code more in line with what `go mod` would have generated if
one had tried to manually generate those packages.
This was manually confirmed to have a fully working experience in GoLand,
where even generated code modules are completely browsable, compiling,
and IntelliSense-able in this configuration; while previously it would be
unable to build and check the generated code, resulting in an extremely
poor experience (with UIs jumping around as the IDE failed to resolve modules).
--- …
=> feat(go): emit indirect dependencies in go.mod

.github/workflows/main.yml, packages/@jsii/go-runtime/build-tools/package.sh, packages/@jsii/go-runtime/package.json
The publisher expects golang code to reside under the `go` directory in the build artifact. To that end, add a "package" script to the `@jsii/go-runtime` module which copies the go runtime code to `dist/go`. This is then collected during mono-repo packaging.
Remove the go publishing step from the github workflow as it is now handled by the delivlib pipeline.
Fixes #2579
---
=> chore: copy golang runtime to dist for publishing

.github/workflows/auto-approve.yml
We were using the `aws-cdk-automation` user credentials to automatically approve PRs, but that would fail for PRs created by that user itself.
In the CDK repository, we approve using GitHub Actions' credentials and that seems to work fine, so do the same here.
---
=> chore: use GitHub Actions to auto-approve PR

packages/jsii-pacmak/lib/targets/go.ts
Starting go 1.16, `go build` does not download modules and updates go.sum automatically. To that end, we now execute this before we execute `go build` during pacmak.
Additionally, set `GOSUMDB` to `off` in order to reduce the chance for eventual consistency issues when new modules are published.
Fixes #2615
---
=> fix(pacmak): go 1.16 requires running "go mod download" explicitly

packages/@jsii/go-runtime/jsii-calc-test/main_test.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/client.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/conversions.go, packages/@jsii/go-runtime/jsii-runtime-go/runtime.go, packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/registration.go, packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/type-registry.go, packages/jsii-pacmak/lib/targets/go/comparators.ts, packages/jsii-pacmak/lib/targets/go/documentation.ts, packages/jsii-pacmak/lib/targets/go/package.ts, packages/jsii-pacmak/lib/targets/go/runtime/class-constructor.ts, packages/jsii-pacmak/lib/targets/go/types/class.ts, packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts, packages/jsii-pacmak/lib/targets/go/types/go-type.ts, packages/jsii-pacmak/lib/targets/go/types/interface.ts, packages/jsii-pacmak/lib/targets/go/types/type-member.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap, packages/jsii-reflect/lib/docs.ts
Go struct fields used to be emitted for all properties of any type,
including for go structs merely there to act as a proxy to a JS object.
Those properties were never accessed (neither set not read), and could
have been cause for confusion. They additionally needlessly increased
the memory footprint of such data types.
This changes the code generation to no longer emit fields on go structs
that are intended as proxies to JS objects, instead embedding the base
type(s) (super-class and/or super-interfaces) to properly inherit their
methods without duplicating every declaration; and uses a `byte`
placeholder when needed to ensure no 0-width struct is ever generated
(go would have those take 0 bytes of memory, and as a consequence, any
such vlaue is deemed equal to any other, which is not …
=> refactor(go): stop emitting unused fields in go structs

packages/@jsii/go-runtime/jsii-runtime-go/kernel/begin.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/callbacks.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/client.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/client_test.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/complete.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/create.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/del.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/end.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/get.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/hello.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/invoke.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/load.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/naming.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/request-response-markers.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/set.go, packages/@jsii/go-runtime/jsii-runtime-go/kernel/stats.go, packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
Those need not be set on each site that makes a kernel call. This leads
to possible errors. Instead, the API call name is no centralized by the
`kernel` package, which sets it "behind the covers".
In order for the naming to make sense with respects to go naming
conventions, I renamed:
- `type kernelRequester struct` to `kernelRequest`
- `type kernelRequest interface` to `kernelRequester`
- `type kernelResponder struct` to `kernelResponse`
- `type kernelResponse interface` to `kernelResponder`
The `kernelRequest` struct now contains the `API` field definition, and
all the client APIs that end up calling `client.request` compose a
`kernelRequest` and their "request properties type" into a single
struct, for easy and straight-forward marshaling.
---
By submitting this pull request, I confirm …
=> refactor(go): hide API fields from the kernel API

packages/@jsii/go-runtime/build-tools/package.sh
jsii-release requires a file called "version" so it will know the go-runtime version.
---
=> chore: add "version" file to go dist directory

gh-pages/content/user-guides/lib-author/configuration/targets/go.md, packages/@jsii/go-runtime-test/project/compliance_test.go, packages/@jsii/go-runtime-test/project/go.mod, packages/@jsii/go-runtime-test/project/main_test.go, packages/@jsii/kernel/test/kernel.test.ts, packages/@scope/jsii-calc-base/package.json, packages/@scope/jsii-calc-base/test/assembly.jsii, packages/@scope/jsii-calc-lib/lib/submodule/.jsiirc.json, packages/@scope/jsii-calc-lib/package.json, packages/@scope/jsii-calc-lib/test/assembly.jsii, packages/jsii-calc/package.json, packages/jsii-calc/test/assembly.jsii, packages/jsii-calc/update-all.sh, packages/jsii-pacmak/lib/targets/go.ts, packages/jsii-pacmak/lib/targets/go/package.ts, packages/jsii-pacmak/lib/targets/go/util.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Add two features to the `go` targets config in package.json:
- `packageName` can be used to customize the name of the go package (previously this was always derived from the javascript name).
- `versionSuffix` can be used to append a suffix to the version number (e.g. `-devpreview`).
Resolves #2632
This is needed in order to control the name of the AWS CDK go bindings so they are the same between v1 and v2. Currently the v1 name would have been `monocdk` and v2 `awscdklib` and we want both to actually be `awscdk` per the decision in [this RFC](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0079-cdk-2.0.md#releasing-to-package-managers).
--- …
=> feat(go): packageName and versionSuffix

packages/jsii-calc/lib/index.ts, packages/jsii-calc/lib/module2530/index.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/go/util.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap, packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
It is common in TypeScript to use `_` as an argument name if the argument is not used. This is an invalid name in Go, so replace it with `_arg`.
Fixes #2530
---
=> fix(go): arguments named "_" result in invalid code

packages/jsii-calc/lib/index.ts, packages/jsii-calc/lib/module2700/index.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/go/types/class.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap, packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
If a class implements an interface from multiple paths (e.g. directly and via a base), then Go compilation fails with an ambiguity issue.
Simplify by always re-implementing all methods and properties in derived classes.
Fixes #2700
---
=> fix(go): missing methods for multiple inheritance of the same interface

superchain/Dockerfile, superchain/README.md
We added multiple Node versions into the Superchain image, and made it
possible to switch between them using NVM.
Doing so would require putting `nvm use 14` at the top of every script
that wanted to run against a newer Node version, and so would require
modification to scripts in our branches.
Another, more effective, way to configure the Node version is to be able
to do it without modifying the scripts themselves, but by specifying it
via the runtime environment. In this case, via environment variable that
can be set on the Docker environment.
The `$NVM_USE_VERSION` environment variable will lead to an implicit
execution of `nvm use $NVM_USE_VERSION` at container startup time, if
present.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> feat(superchain): `$NVM_USE_VERSION` selects Node.js version

packages/jsii-rosetta/lib/jsii/assemblies.ts, packages/jsii-rosetta/test/jsii/assemblies.test.ts
Reverts aws/jsii#2712
The mentioned commit breaks our cdk integ test since it depends on https://github.com/aws/aws-cdk/pull/13670, which hasn't landed on the release branch yet. 
This will be reintroduced after we release CDK.
=> revert(rosetta): 'extract' does not translate samples in submodule READMEs

superchain/Dockerfile, superchain/README.md, superchain/run.sh
This ensures node is always in the PATH at the start of a container (unless
the user replaced the entrypoint). This attempts to minimize overhead of the
overall setup by using exec in the run.sh script.
Fixes #2734
---
=> fix(superchain): use entrypoint to set up nvm

superchain/Dockerfile, superchain/README.md, superchain/run.sh
Includes the following:
- Revert "fix(superchain): use entrypoint to set up nvm (#2736)"
- This reverts commit 0e247b6d9f432512559fb4642eebce0b1a854859.
- Revert "feat(superchain): `$NVM_USE_VERSION` selects Node.js version (#2726)"
- This reverts commit fb9abf954d29fd1f1e67cdc2d917c7dbb3a8f9d9.
- Revert "feat(superchain): install both Node 10 and Node 14 (#2718)"
- This reverts commit 3ca97d9f7164ac158a253354837970177e1d2f4e.
---
=> Revert "feat(superchain): install both Node 10 and Node 14 (#2718)"

packages/@jsii/go-runtime-test/project/compliance.go, packages/@jsii/go-runtime-test/project/compliance_test.go
Use the `require` package instead of `assert` in order to fail fast.
---
=> chore(golang): require instead of assert

packages/@jsii/go-runtime/jsii-runtime-go/go.mod, packages/@jsii/go-runtime/jsii-runtime-go/go.sum, packages/@jsii/go-runtime/jsii-runtime-go/runtime.go, packages/@jsii/go-runtime/jsii-runtime-go/runtime_test.go
It is somewhat inconvenient to build slices of optional values, and
new variadic helpers can help soothe that pain in many circumstances...
Adding variadic slice helpers:
- `Bools`
- `Numbers`
- `Strings`
- `Times`
Effectively, this allows replacing:
```go
&[]*string{
jsii.String("Foo"),
jsii.String("Bar"),
jsii.String("Baz"),
}
```
With the more compact:
```go
jsii.Strings("Foo", "Bar", "Baz")
```
---
=> feat(go): variadic type helpers to build slices

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Always emit an `__all__` declaration even if the module does not export
anything.
Fixes #2750
---
=> fix(python): module import fails with: KeyError: '__all__'

packages/@jsii/java-runtime/pom.xml.t.js, packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
This allows us to reduce our dependency surface by skipping `zt-exec`,
as we only need a tiny, tiny fraction of the many features they provide.
Re-implemented the error stream sink we had previously (before swicthing
to `zt-exec`) by drawing inspiration from how `zt-exec` makes it work.
---
=> chore(java): re-implement error stream sink in Java runtime

packages/jsii-rosetta/README.md, packages/jsii-rosetta/lib/commands/extract.ts
The current behavior of rosetta (extract) is to use a number of node worker
threads equal to half the number of CPU cores. On large CI/CD build hardware,
this may mean creating a huge number of worker threads which causes more
contention than benefit.
Introduce `JSII_ROSETTA_MAX_WORKER_COUNT` to limit the maximum number of workers
(defaults to `16`).
See https://github.com/aws/aws-cdk/pull/14389 for more motivation from the AWS CDK.
---
=> feat(rosetta): JSII_ROSETTA_MAX_WORKER_COUNT limits max workers

.github/workflows/auto-approve.yml, .github/workflows/close-stale-issues.yml, .github/workflows/closed-issue-message.yml, .github/workflows/docker-images.yml, .github/workflows/gh-pages.yml, .github/workflows/main.yml, .github/workflows/yarn-upgrade.yml
By default, all Github actions have read permissions via the standard
`GITHUB_TOKEN`. For jobs that require write permission, explicitly
add the necessary permissions.
In the case of the 'Yarn Upgrade' Github action, separated the
'upgrade' step and the 'pull request' step into separate
jobs to build a better security boundary between the two.
Inspired from: https://github.com/projen/projen/blob/a4f875d07b57f8f8247b9352e34c3c83759afe82/.github/workflows/upgrade-dependencies.yml
---
=> chore: permissions for github actions

packages/jsii-rosetta/bin/jsii-rosetta.ts
This is caused due to a mismatch between the command declaration where
the argument is named 'FILE' and the positional declaration where the
parameter is named 'file'.
---
=> fix(rosetta): hangs on 'markdown' command when a file is provided

packages/jsii-pacmak/lib/targets/go.ts
Switch to using `go mod tidy` instead of `go mod download` to work
around https://github.com/golang/go/issues/44129. This caused tests to
fail due to using `go1.16.x`, which is susceptible to this bug (`go1.17`
will have the fix).
---
=> fix(pacmak/go): missing go.sum entry

packages/jsii-rosetta/lib/commands/transliterate.ts, packages/jsii-rosetta/lib/fixtures.ts, packages/jsii-rosetta/lib/translate.ts, packages/jsii-rosetta/test/commands/transliterate.test.ts, packages/jsii-rosetta/test/translate.test.ts
In cases where a literate source file was missing, the substitution
value was not valid TypeScript, which could cause the comipler to fail
on an opaque error (`Debug Failure`).
This falls back to the visible code for the snippet instead of inserting a
placeholder, and also makes sure to rescue the `Debug Failure` where
it is emitted from, that is in the call to
`program.getDeclarationDiagnostics`.
Both of this changes result in greater chances of transliteration
success.
Related to cdklabs/jsii-docgen#369
---
=> fix(rosetta): fails on "Debug Failure"

gh-pages/content/index.md
The previous link pointed to a 404 page. I updated it to point to the repository's `CONTRIBUTING.md`.
---
=> docs: Fix broken link to Contribution Guide

packages/@jsii/python-runtime/setup.py
Version `1.6.0` has been yanked.
---
=> chore: upgrade cattrs dependency to 1.7.1 (py3.7+)

packages/jsii-rosetta/package.json, yarn.lock
This uses a custom resolution to the xmldom GitHub repoisoty, as they
are currently unable to publish the fixed version to npmjs.com. See
xmldom/xmldom#271 for more information. The custom resolution can be
removed once npmjs.com has 0.7.0 or above.
---
=> chore: upgrade xmldom from 0.6.0 to 0.7.0

packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiEngine.java
When extending a "jsii well-known type", additional jsii interfaces
implemented were not registered with the kernel, because of a flaw in
how interface discovery works. The `@Jsii` annotation is `@Inherited`,
meaning that a sub-class of an annotated type is annotated (this is
desirable)... However, this means the fact the annotation is present on
a type does not imply it _is_ a "jsii well-known type"... Instead, we
must check whether the annotation is _declared_ by the current type (if
not, then the annotation is inherited from a parent class).
Fixes #2951
---
=> fix(java): implemented interface is not registered

packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py, packages/@jsii/python-runtime/src/jsii/_runtime.py, packages/@jsii/python-runtime/tests/test_compliance.py, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
When a type extends a jsii class, any additional interfaces implemented
via the `@jsii.implements` annotation were not properly registered, and
overrides were not properly discovered.
This was the combination of a code-generation bug, which caused the type
passed to the `create` kernel method to be that of the jsii class,
instead of the dynamic class (`self.__class__`); and a kernel bug, which
caused those inheritance graphs to completely skip overrides detection.
Fixes #2963
---
=> fix(python): unable to implement additional interfaces

gh-pages/content/user-guides/lib-author/.pages.yml, gh-pages/content/user-guides/lib-author/hints.md, gh-pages/content/user-guides/lib-author/typescript-restrictions.md, packages/@jsii/spec/lib/assembly.ts, packages/jsii/lib/assembler.ts, packages/jsii/lib/docs.ts, packages/jsii/lib/jsii-diagnostic.ts, packages/jsii/lib/utils.ts, packages/jsii/test/__snapshots__/negatives.test.ts.snap, packages/jsii/test/hints.test.ts, packages/jsii/test/negatives/neg.struct-hint-on-class.ts, packages/jsii/test/negatives/neg.struct-hint-on-enum.ts, packages/jsii/test/negatives/neg.struct-hint-with-methods.ts
Using the hint allows any interface to always be treated as a struct (as
long as all it's properties are readonly and it has no methods) even if
it has an `I`-prefixed name.
---
=> feat: @struct type system hint

packages/jsii-rosetta/lib/markdown/xml-comment-renderer.ts, packages/jsii-rosetta/package.json, yarn.lock
Fixes #2969
The xmldom package has moved. See https://github.com/xmldom/xmldom/issues/271
---
=> chore: use @xmldom namespace on npm instead of source

superchain/Dockerfile, superchain/dockerd-entrypoint.sh
We were missing a VOLUME declaration in the final image, which prevented
dockerd from properly starting within Docker (complaining that overlay2
is not a valid parameter).
The VOLUME is required because overlay-on-overlay is not supported (and
using a VOLUME guarantees that there is no overlay underneath it).
---
=> chore: fix docker-in-docker

packages/jsii-rosetta/lib/commands/extract.ts
Worker threads have their own memory limits, which have relatively low
defaults. In order to improve the effectiveness of rosetta, this ensures
all worker threads have the same maximum heap size as the parent process.
---
=> feat(rosetta): propagate max heap size to worker threads

superchain/Dockerfile
In order to facilitate use with GitHub Actions, explicitly set the UID and GID
of the `superchain` user to `1001`, which is the UID/GID set on the GitHub
working directory on the file system.
---
=> chore(superchain): set UID and GID of superchain user

packages/jsii-pacmak/bin/jsii-pacmak.ts, packages/jsii-pacmak/lib/index.ts, packages/jsii-pacmak/lib/packaging.ts, packages/jsii-pacmak/lib/util.ts
Assembly validation can be expensive (both in time and memory). This is
ususally not necessary, as assemblies cna generally be assumed to be
valid.
This adds a new optional option to `jsii-pacmak` to enable assembly
validation, and opts out of it when loading type systems by default.
---
=> feat(pacmak): opt out of jsii assembly validation

packages/jsii/lib/transforms/deprecation-warnings.ts, packages/jsii/test/deprecation-warnings.test.ts
It is common in the AWS CDK for non-deprecated interfaces to extend
deprecated interfaces.
Currently, when this occurs and the non-deprecated subclass is
referenced, a warning is generated notifying the deprecation of its
superclass.
Modify the implementation such that the warning is produced only when
a property of the deprecated interface is referenced.
In the case when a deprecated interface with no required properties is
used without any of its properties set, a warning will not be generated.
This should occur rarely and the trade off is acceptable.
fixes #3111
---
=> fix(jsii): unexpected deprecated warnings when a deprecated interface is extended

.mergify/config.yml
This action was left behind in the [previous PR](https://github.com/aws/jsii/pull/3079).
---
=> chore: using queue action in the 'Synchronize that PR to upstream and merge it (no-squash)' rule

packages/jsii-rosetta/lib/rosetta.ts
A package may accidentally (or on purpose) contain a `.jsii.tabl.json`
file, containing pretranslated examples.
When an assembly is added for snippet discovery, this tablet will
be loaded implicitly to save live conversion time.
However, if the tablet file is old, or not even a tablet file, this
will stop rosetta with an error. Catch that error and continue
anyway.
Fixes an issue in Construct Hub.
---
=> fix(rosetta): crashes on outdated tablet files in a package

packages/jsii-rosetta/bin/jsii-rosetta.ts, packages/jsii-rosetta/lib/commands/infuse.ts, packages/jsii-rosetta/lib/tablets/tablets.ts, packages/jsii-rosetta/test/commands/infuse.test.ts
The new `infuse` feature replicates examples from READMEs to types.
However, because of caching, example locations have become part of their
identifying key. Because an example has moved to a different location,
it now has a different key, and because that key is not in the tablet
yet the example will count as untranslated (requiring live conversion
during `pacmak` time, and increasing the pack time).
When we copy an example to a different type, also create a copy at
the new type location in the tablet, so that it will count as
pretranslated.
---
=> fix(rosetta): `infuse` creates untranslated examples

packages/jsii-rosetta/lib/jsii/assemblies.ts, packages/jsii-rosetta/test/commands/extract.test.ts
In CDK, we use the `@example` tag a lot to indicate example values
of some property, instead of code examples. For example, a `bucketArn`
property might have as annotation `@example arn:aws:s3:....`.
Rosetta would try to compile those, and fail. To get around this, we would skip
values that *looked* like they weren't source in `rosetta extract`.
This doesn't combine well with pacmak live-translation. We are either forced to
try and compile them again during pacmak (adding compile time), or fail
pacmak as soon as we encounter these. And all of this is to work around
abuse of the `@example` tag for something it's not intended for.
So stop treating these examples specially. They will just fail compilation
unless rewritten. This will force us to deal with them properly in the
CDK source code. …
=> fix(rosetta): stop skipping example values

packages/jsii-rosetta/lib/rosetta.ts, packages/jsii-rosetta/test/rosetta.test.ts
We used to only remember snippets we live-translated using the rosetta
API if we were able to find a fixture for them.
There's no good reason for this. Also remember them if we live-translate
without a fixture.
---
=> fix(rosetta): remember live-translated snippets without fixtures

packages/jsii-pacmak/lib/targets/version-utils.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap, packages/jsii-pacmak/test/targets/version-utils.test.ts
When the version of `jsii-pacmak` is `0.0.0`, it will write the following
requirement for `jsii-runtime`: `[,0.0.1)`. There is no version that satisfies
that dependency, so the build fails.
Make an exception: if the version we're trying to install is `^0.0.0`,
translate it to "any old version" instead.
Fixes #3107.
---
=> fix(pacmak): development version cannot pack java

packages/jsii-pacmak/lib/logging.ts, packages/jsii-pacmak/lib/packaging.ts, packages/jsii-pacmak/lib/util.ts
Pacmak outputs both the command-line commands as well as stdout/stderr
for those commands under the `verbose` loglevel.
That's too much at one log level: I definitely want to know about the
commands without getting spammed with all the command outputs.
Introduce a new loglevel, `silly`, and move the command output to
that level.
Also remove a log line from `npmPack` that is redundant with the
log line that prints the command that's going to be executed.
---
=> fix(pacmak): add 'silly' loglevel for command output

packages/jsii-rosetta/lib/fixtures.ts, packages/jsii-rosetta/test/commands/extract.test.ts, packages/jsii-rosetta/test/commands/infuse.test.ts, packages/jsii-rosetta/test/jsii/assemblies.test.ts, packages/jsii-rosetta/test/record-references.test.ts, packages/jsii-rosetta/test/syntax-counter.test.ts, packages/jsii-rosetta/test/testutil.ts
The `rosetta` fixtures directory is assembly-scoped. That means that in
the monocdk transform, all Rosetta fixtures from the individual
assemblies need to be tossed together into one `rosetta` directory for
all of them.
Inevitably this leads to conflicts, where the various individual
`default.ts-fixture` files compete with each other to be the one,
global `default.ts-fixture`. What ends up happening is they end up
overwriting each other and the last module to get copied in wins.
All other modules' examples fail to compile.
Ideally the `ubergen` tool that combines these fixtures would ensure
it doesn't clobber existing files, and renames the fixtures to unique
names (maybe `s3.default.ts-fixture`). But if it does that, *none* of them are
called `default.ts-fixture` and so all snippets …
=> feat(rosetta): find fixtures based on submodules

packages/jsii-pacmak/lib/targets/_utils.ts, packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/lib/targets/python.ts
The code generators in pacmak are now passing API locations to Rosetta,
to indicate the source of the snippets they're finding. This is necessary
to distinguish the same code snippet found in a different submodule, because
it might be using a different fixture.
They all had the same mistake though, in that `rosetta extract` was identifying
snippets by "defining API element", whereas pacmak was identifying snippets by
what class it was generating code for... and in the case of inheritance, those
two locations would be different.
Put in extra effort in the pacmak target generators to keep track of where
we found a method or property, so we can use the same location translating
the examples.
This was validated by running pacmak over the entire CDK repository, with the
option …
=> fix(pacmak): API locations for inherited members are incorrect

.github/workflows/pr-labeler.yml
Apparently, in order to add labels to a PR, the token must have write permissions to issues as well, otherwise it will silently fail.
See https://github.com/cli/cli/issues/4631
----
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*
=> chore: fix pr-labeler permissions

packages/jsii-rosetta/lib/commands/extract.ts
We were dividing by the total number of snippets, instead of the actually translated ones.
---
=> fix(rosetta): snippet throughput incorrect

packages/jsii-rosetta/lib/translate.ts, packages/jsii-rosetta/test/translate.test.ts
When `rosetta:extract` is run, the property `didCompile` evalutes to `true`
even when compilation was not attempted. This causes lots of confusion.
The correct way to handle this is to return `undefined` when compilation is
not attempted. Then, (I assume) `didCompile` will not show up in the tablet
file at all when compilation is not asked for (via `--compile` or `strict`.
---
=> fix(rosetta): `didCompile` evaluates to true when compilation not attempted

packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts, packages/jsii-pacmak/lib/targets/index.ts, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
We're pretty confident in our rosetta translations by now. If we
successfully compiled the example, no need to prefix it with
a disclaimer anymore: the translation is most likely correct.
---
=> fix(pacmak): remove disclaimer on compiling examples

packages/jsii/lib/node-bindings.ts, packages/jsii/lib/validator.ts, packages/jsii/test/__snapshots__/negatives.test.ts.snap, packages/jsii/test/negatives/_unexported.ts, packages/jsii/test/negatives/neg.expose-unexported-type-constructor-param.ts
The compiler incorrectly allowed un-epxorted types to be used in a
constructor parameter, resulting in invalid assemblies (where a
reference to the un-exported type exists, but the type itself does not).
Added a test that validates this is now checked against, and improved
the error experience by providing source anchors for where the
problematic type is being used.
---
=> fix(jsii): incorrectly allowed unexported type in constructor params

packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
- fix(pacmak): support more than 255 properties in interfaces for Java
- chore(tests): update snapshots
Resolves #3132
This is a naive approach to fix the problem outlined in #3132 – it should not be user facing and should not break anything (famous last words before CI fails). Happy for any feedback!
---
=> fix(pacmak): Support more than 255 properties for interfaces in Java

lerna.json, package.json, packages/jsii/lib/assembler.ts, packages/jsii/lib/compiler.ts, regression-tests/@barrelimports/consumer/.gitignore, regression-tests/@barrelimports/consumer/README.md, regression-tests/@barrelimports/consumer/lib/index.ts, regression-tests/@barrelimports/consumer/package.json, regression-tests/@barrelimports/provider/.gitignore, regression-tests/@barrelimports/provider/README.md, regression-tests/@barrelimports/provider/lib/index.ts, regression-tests/@barrelimports/provider/lib/namespaced.ts, regression-tests/@barrelimports/provider/package.json, regression-tests/README.md
When a dependency exposes submodules, and the entry point of that
dependency is never imported by the program being compiled, symbols
from the dependency were not correctly mapped to their submodule because
the entry point was not part of the compiler input (and hence the
`ts.Program` did not hold a `ts.SourceFile` for it, and the
`ts.TypeChecker` did not have symbols for exports therein).
In order to address this problem, this always explicitly references
dependencies' entry point (the `.d.ts` file referenced by the `types`
key) to the compiler input path. This guarantees the compiler binds
symbols within those, and that the submodule mapper can appropriately
discover those.
------------------------------------------------------------------------
An alternative approach was considered …
=> fix: dependency submodules may not be discovered

packages/jsii-rosetta/lib/jsii/jsii-types.ts, packages/jsii-rosetta/test/translations/structs/infer_struct_from_union.cs, packages/jsii-rosetta/test/translations/structs/infer_struct_from_union.java, packages/jsii-rosetta/test/translations/structs/infer_struct_from_union.py, packages/jsii-rosetta/test/translations/structs/infer_struct_from_union.ts
Rosetta gets confused by type unions when it's trying to derive
the type of a struct.
This bites CDK as we're generating examples for L1s, and they all have
unions with `IResolvable` in all their properties.
If we can match a struct, let's do so.
---
=> fix(rosetta): gets confused by type unions

packages/jsii/lib/transforms/deprecation-warnings.ts, packages/jsii/test/deprecation-warnings.test.ts
This happens when:
1. An interface inherits from at least two other interfaces.
2. Both super-interfaces have a property with the same name.
3. The property is deprecated in one, but not the other.
The solution here is to inline the `print` calls for properties coming from the super types, instead of calling the functions that handle those super types. If there is a conflict (i.e. item 3 above), then the warning is suppressed for that property.
In terms of implementation, this is achieved by recursively calling the function that processes the warnings for interface types. Every property that is found is added to a map and non-deprecated properties are added to an exclusion list. At the end, properties that are in the exclusion list are removed from the final statements list.
---
By …
=> fix: deprecation warnings are generated even when one property is not deprecated

CHANGELOG.md
This causes Github publish to fail since we use heading level to find
the release notes for the version.
---
=> chore: fix changelog heading level

packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
Currently code examples in dotnet lose their indentation styles because we call `trim()` on each line in the code example. We want that behavior for other types of xml docs but not for code. This PR makes code a special case that calls `trimRight()` on each line, preserving the indentation on the left.
The only change in the snapshots is translating this example: 
```ts
docs const x = 12 + 44;
const s1 = "string";
const s2 = "string \nwith new newlines"; // see https://github.com/aws/jsii/issues/2569
const s3 = `string
with
new lines`;
```
to this:
```
<code>int x = 12 + 44;
string s1 = "string";
string s2 = @"string
with new newlines"; // see https://github.com/aws/jsii/issues/2569
string s3 = @"string
with
new lines";</code>
```
---
By submitting this pull request, I confirm that my …
=> fix(pacmak): dotnet code docs loses indentation

packages/jsii-rosetta/lib/util.ts
One-liner to make sure that we slice `diags` correctly. Tested locally on my own machine to ensure that it works.
---
=> fix(rosetta): diagnostics not showing

packages/@jsii/spec/lib/assembly.ts, packages/@scope/jsii-calc-lib/lib/submodule/README.md, packages/@scope/jsii-calc-lib/test/assembly.jsii, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap, packages/jsii/lib/assembler.ts
The namespace determination for the `NamespaceDoc` class generated for
submodules was incorrect, as the `jsiiNs` passed to the type resovler
was absolute, instead of being the required assembly-relative form.
Additionally, removed the `readme` and `locationInSource` property from
submodule descriptors included in the jsii assembly under
`dependencyClosure`, as those are not necessary and needlessly bloat the
assembly document.
---
=> fix: C# NamespaceDoc emitted to wrong location

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/lib/targets/python/type-name.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
The goal of this PR is, to find a way for generated Python code to work with namespaced modules regardless of the way it is consumed. While the current implementation of submodule imports seem to work fine when distributed as packages, it's breaking apart when the generated code is imported relatively as part of a single code base. That's what we do in cdktf and the reason why we have locked jsii to `1.37.0` at the moment.
The general idea is, to generate relative imports rather than fqn imports in Python. This could be a potential way to address https://github.com/aws/jsii/issues/3078
```python
import jsii_calc.submodule
import jsii_calc.submodule.nested_submodule
import jsii_calc.submodule.nested_submodule.deeply_nested
from . import submodule
from .submodule import nested_submodule …
```
=> fix(pacmak): Generate Relative Module Imports in Python

packages/jsii-rosetta/lib/jsii/jsii-utils.ts, packages/jsii-rosetta/test/jsii-imports.test.ts
On some examples in the CDK repository, Rosetta breaks in the
`resolveEnumLiteral()` function. The error is `Cannot read property
'kind' of undefined` and occurs somewhere deep in the call stack of
TypeScript.
It occurs when an enum is being passed as a struct property.
---
=> fix(rosetta): enum resolution breaks for properties

packages/jsii-rosetta/lib/commands/extract.ts, packages/jsii-rosetta/test/commands/extract.test.ts
In a recent refactor we failed to pass on the setting of the `--compile`
flag, leading to non-exhaustive compilation checks and also resulting
in a disclaimer being added to all translated snippets.
---
=> fix(rosetta): `extract` ignores `--compile` option

packages/jsii-reflect/lib/assembly.ts, packages/jsii-reflect/test/independent.test.ts, packages/jsii-reflect/test/type-system.test.ts, packages/jsii-reflect/test/util.ts, packages/jsii/lib/helpers.ts
In the presence of submodules, `assembly.types` only returns types in
the assembly root. Add a new accessor, `allTypes`, which will return
all types in the assembly regardless of module.
---
=> feat(reflect): add `allTypes` accessor

superchain/Dockerfile
This is necessary to unbreak the Docker image builds; the old Maven
distribution has a GPG signature that no longer validates. It breaks
with the error:
```
2.502 gpg: Signature made Mon Sep 27 18:32:53 2021 UTC
2.502 gpg:                using RSA key 1A2A1C94BDE89688
2.503 gpg: BAD signature from "Michael Osipov (Java developer) <1983-01-06@gmx.net>" [unknown]
```
---
=> chore: upgrade Maven to 3.8.4

packages/jsii/lib/validator.ts, packages/jsii/test/enums.test.ts
An enum identifier like `C5A` is not possible: the `case` library we use
to assert casing will insist you change it to `C5_A`.
Bypass this rule for constant-like values: do a more lenient validation
of our own.
Fixes #3208.
---
=> fix(jsii): constants can't mix letters and digits

packages/jsii-rosetta/bin/jsii-rosetta.ts
The way we are trending, there is no good reason anymore to NOT compile
your examples. We have good support for parallelism and caching now,
so the argument that it takes too much time to do the additional
analysis no longer really holds.
Also, why should people have to remember to pass this flag for default
that should arguably be the default?
Make it the default.
---
=> fix(rosetta): use `--compile` flag by default

packages/jsii-rosetta/README.md
The Rosetta README was outdated and didn't really present information
in the best way. Update it.
Note: this rewritten README describes some changes that have yet to be
made.  It is an example of README-driven development, but I don't want
to mix the code changes with the README changes.
---
=> chore(rosetta): rewrite README

packages/jsii-pacmak/bin/jsii-pacmak.ts, packages/jsii-pacmak/lib/index.ts
Given the current state of example tooling, the existing default
was a bad choice.
It forces everyone who is publishing jsii packages everywhere to
spend CPU cycles to do example parsing and translation which is
bound to fail anyway (as the fixtures and compilation directory
will probably not be set up for success, and translation
must proceed in a single-threaded fashion).
The new default is to use translations if they exist, and otherwise
don't do translations.
* Builds that care (i.e., mostly the CDK build), will be using `rosetta
extract` already to be efficient and correct about compilation, and
the tablet files will be picked up as usual.
* Builds that don't care will get more efficient.
BREAKING CHANGES: Pacmak no longer tries to translate examples
by default: this feature is now …
=> fix(pacmak): don't automatically translate examples without asking

packages/jsii-rosetta/bin/jsii-rosetta.ts, packages/jsii-rosetta/lib/commands/extract.ts, packages/jsii-rosetta/lib/commands/infuse.ts, packages/jsii-rosetta/lib/commands/transliterate.ts, packages/jsii-rosetta/lib/commands/trim-cache.ts, packages/jsii-rosetta/lib/jsii/assemblies.ts, packages/jsii-rosetta/lib/rosetta-translator.ts, packages/jsii-rosetta/lib/snippet.ts, packages/jsii-rosetta/lib/tablets/tablets.ts, packages/jsii-rosetta/lib/typescript/types.ts, packages/jsii-rosetta/lib/util.ts, packages/jsii-rosetta/test/commands/extract.test.ts, packages/jsii-rosetta/test/commands/infuse.test.ts, packages/jsii-rosetta/test/commands/trim-cache.test.ts
Rather than write our Rosetta translations to a single tablet file which
we throw away at the end of the build, `rosetta extract` will now write
translations to individual `.jsii.tabl.json` files, located next to
the assemblies themselves.
Construct library authors can publish these to NPM, so that downstream
tools that process JSII modules for documentation have access to the
translations and don't need to redo the work (especially relevant
for large libraries with lots of examples, where otherwise a lot
of CPU time would be wasted).
The "single output tablet" can still be used, but is now intended to be
used as a cache to speed up repeated runs of `rosetta extract` (to skip
translating unchanged snippets). Add options to trim the cache files
down so they won't grow without bounds.
This …
=> feat(rosetta): generate rosetta tablets next to each assembly

packages/@scope/jsii-calc-base-of-base/test/assembly.jsii, packages/@scope/jsii-calc-lib/test/assembly.jsii, packages/jsii-pacmak/package.json, packages/jsii-rosetta/lib/jsii/jsii-utils.ts, packages/jsii-rosetta/lib/languages/record-references.ts, packages/jsii-rosetta/test/commands/extract.test.ts, packages/jsii-rosetta/test/testutil.ts, packages/jsii/lib/assembler.ts, packages/jsii/lib/helpers.ts, packages/jsii/lib/symbol-id.ts, packages/jsii/test/compiler.test.ts, packages/jsii/test/symbol-identifiers.test.ts
`rosetta extract` breaks down when a project structure includes `outDir` or `rootDir` in the `tsconfig` file. Given such a project structure, `extract` may find symbolIds that look like `outDir/index:ClassA` or `rootDir/index:ClassA`. Since the jsii assembly is created from the source files in the `rootDir`, `rootDir/index:ClassA` is the symbolId we want. So if the `outDir` is specified, we swap it with the specified `rootDir` (and if `rootDir` is not specified, we guess at it the same way node does). This ensures that `rosetta extract` is structure agnostic.
---
=> fix(rosetta): classes are not correctly identified if package uses an outDir

packages/jsii-calc/test/assembly.jsii, packages/jsii-rosetta/lib/jsii/jsii-utils.ts, packages/jsii-rosetta/lib/util.ts, packages/jsii/lib/assembler.ts, packages/jsii/lib/symbol-id.ts, packages/jsii/lib/utils.ts, packages/jsii/test/symbol-identifiers.test.ts
We used to be doing our own `symbolId` calculations, but this was silly:
TS has a perfectly cromulent function built-in to do the same.
Implement ours in terms of theirs.
This uncovered a bug in calculating symbolIds for single-valued enums, which is rectified as well.
---
=> fix(jsii): symbolid for single-valued enums is incorrect

packages/jsii/lib/compiler.ts, packages/jsii/lib/utils.ts
Fixes for some cases that were introduced in #3205, that cropped
up during a full CDK build:
- Some `@types/xxx` modules use an `exports` field, changing the
error we get when trying (and failing) to import it.
- `punycode` is both an NPM dependency and a built-in. The built-in
takes precedence and changes the return value of `require.resolve()`
to something unexpected.
---
=> chore: fix issues encountered during CDK build

packages/jsii-rosetta/bin/jsii-rosetta.ts
As part of a refactor, `rosetta infuse` no longer utilizes a single tablet file in favor of tablets at the assembly level. However the `infuse` command still takes in a positional argument `TABLET` that goes unused. This means that the first argument sent into the command gets dropped.
---
=> fix(rosetta): infuse drops first assembly

.mergify/config.yml
`commit_message` is deprecated and being replaced with `commit_message_template`.
---
=> chore: move away from mergify commit_message

packages/jsii-rosetta/lib/commands/extract.ts, packages/jsii-rosetta/lib/rosetta-translator.ts, packages/jsii-rosetta/test/commands/extract.test.ts
Picture this scenario: there is a non-compiling snippet in a README.md file.
I run `yarn rosetta:extract --compile` and it returns diagnostics as expected.
Behind the scenes, `.jsii.tabl.json` gets created as a cache, and this snippet
is inserted into that file with `didCompile = false`.
_Without making any changes_, I run `yarn rosetta:extract --compile` again.
This time, no diagnostics are returned, and it looks like my errors have
magically fixed themselves. However what is really happening is that `extract`
is finding a snippet in the cache that matches the offending snippet (since
I changed nothing). It is then filtering out that cached snippet, meaning we
do not actually try to compile the snippet again. This is bad; `extract` should
honor the `--compile` flag and return errors the …
=> fix(rosetta): non-compiling snippets not reported on subsequent extracts

packages/jsii-rosetta/lib/commands/extract.ts, packages/jsii-rosetta/lib/commands/transliterate.ts, packages/jsii-rosetta/lib/jsii/assemblies.ts, packages/jsii-rosetta/lib/rosetta-reader.ts, packages/jsii-rosetta/lib/rosetta-translator.ts, packages/jsii-rosetta/lib/snippet.ts
Make the `rosetta transliterate` command do translations in parallel.
Achieve this by effectively running `rosetta extract` beforehand, which
does to translations in parallel using worker threads, but don't save
the results anywhere. Instead, use those results as an in-memory cache
when doing the single pass.
Since there shouldn't be any untranslated snippets left between
extract and transliterate, set the `UnknownSnippetMode` to `FAIL`,
which netted me errors showing that `extract` and `transliterate`
don't look at the same fields! Specifically, initializer and parameters!
---
=> fix(rosetta): transliterate command does not translate in parallel

packages/jsii-pacmak/lib/dependency-graph.ts, packages/jsii-pacmak/test/dependency-graph.test.ts
`projen` uses a bundled dependency called `shx`, and this library does
not have an entry point. It exposes some command-line tools and nothing
else.
This conflicts with our dependency finding mechanism, which performs
a `require()` on the library to find it.
Ignore bundled dependencies in `pacmak`, it never needs to pack them
individually anyway.
Fixes #3275.
---
=> fix(pacmak): fails on bundled dependency without entry point

packages/jsii-rosetta/lib/translate.ts, packages/jsii-rosetta/test/commands/extract.test.ts
Recently we implemented the `infused` metadata that turns `strict=false`
and `loose=true` for the specific snippet. However we still output the
diagnostics along with other snippets (with `isError=true`). One thing we
could do is make these diagnostics `isError=false`, but I argue that we
want to ignore these diagnostics entirely. They aren't actually diagnostics;
we will find them in the cache and they do compile.
---
=> fix(rosetta): diagnostics from infused snippets were not ignored

.github/workflows/auto-approve.yml
The auto-approve workflow is currently [failing](https://github.com/aws/jsii/runs/4618073266?check_suite_focus=true) with:
```console
Error: Input required and not supplied: github-token
Error: Input required and not supplied: github-token
at Object.getInput (/home/runner/work/_actions/actions/github-script/0.3.0/node_modules/@actions/core/lib/core.js:73:15)
at main (/home/runner/work/_actions/actions/github-s
```
This because version `0.3.0` of the action requires a `github-token`, and we don't always provide it. 
Instead of adding it, I upgraded to version `5.0.0` of the action, which no longer requires it.
Some adjustments to the implementation were also necessary due to [breaking changes](https://github.com/actions/github-script#breaking-changes-in-v5). 
---
By submitting this pull …
=> chore: auto approve workflow broken

packages/jsii/test/deprecation-warnings.test.ts
These tests have been sporadically yet consistently timing out in CI.
https://github.com/aws/jsii/runs/4629721868?check_suite_focus=true
Increasing timeouts.
---
=> chore: deprecation warnings test are timing out

.github/workflows/auto-approve.yml, .github/workflows/pr-labeler.yml, .mergify/config.yml
Currently, we are (trying) to merge dependabot PR's by automatically approving them with a comment saying `@dependabot squash and merge`.
The problem is that the entity approving the PR, which is the default github token, doesn't have write permissions to the repo, resulting in:
This might be fixable with granting the token in this specific job with `content: write` permissions. 
However, dependabot doing the merge also has other downsides:
- No observability. Its impossible to understand if dependabot is actually doing something, or what PR's are scheduled for merge. This is as opposed to mergify, where we can always look at the merge queue.
- I've noticed that sometimes dependabot will either ignore or take a long time rebasing the PR. Since there is no observability, its hard to …
=> chore: merge dependabot with mergify

.github/dependabot.yml
`setuptools` version 60.2.0 and above require Python >= 3.7. If dependabot updates it, the build will fail, as we have jobs that run on Python 3.6.
---
=> chore: excluding setuptools from dependabot

packages/jsii-rosetta/lib/languages/python.ts, packages/jsii-rosetta/test/jsii-imports.test.ts, packages/jsii-rosetta/test/translate.test.ts, packages/jsii-rosetta/test/translations/expressions/array_index.py, packages/jsii-rosetta/test/translations/statements/declare_var.py
Currently, Python type declarations are rendered as such:
```python
get_book_integration = apigateway.LambdaIntegration(get_book_handler,
content_handling=apigateway.ContentHandling.CONVERT_TO_TEXT,  # convert to base64
credentials_passthrough=True
)
```
This PR adds information on what module the type came from (if possible), and changes the way these type declarations are shown:
```python
get_book_integration = apigateway.LambdaIntegration(get_book_handler,
content_handling=apigateway.ContentHandling.CONVERT_TO_TEXT,  # convert to base64
credentials_passthrough=True
)
```
---
=> chore(rosetta): change how python shows declared types and include module name

packages/jsii-rosetta/bin/jsii-rosetta.ts, packages/jsii-rosetta/lib/commands/coverage.ts, packages/jsii-rosetta/lib/commands/extract.ts, packages/jsii-rosetta/lib/commands/transliterate.ts, packages/jsii-rosetta/lib/rosetta-translator.ts, packages/jsii-rosetta/test/commands/transliterate.test.ts
In #3262, the performance of `transliterate` was improved by running an
`extract` before translating, because `extract` has the facilities to do
parallel translate, and can read from a cache.
However, another thing `extract` does is *discard translations from the
cache* if they are considered "dirty" for some reason. This reason
can be: the current source is different than the cached source, the
translation mechanism has changed, compilation didn't succeed last time,
or the types referenced in the example have changed.
This is actually not desirable for `transliterate`, which wants to
do a last-ditch effort to translate whatever is necessary to translate,
but should really take what it can from the cache if there's a cached
translation available.
Add a flag to allow reading dirty …
=> fix(rosetta): `transliterate` tries to recompile samples from tablets

packages/jsii-reflect/package.json, packages/jsii/package.json, yarn.lock
See https://github.com/Marak/colors.js/issues/289.
---
=> fix(jsii): breaks due to faulty version of `colors`

packages/jsii-reflect/bin/jsii-tree.ts, packages/jsii-reflect/lib/tree.ts, packages/jsii-reflect/package.json, packages/jsii/lib/assembler.ts, packages/jsii/lib/compiler.ts, packages/jsii/package.json, yarn.lock
The stability and long-term prospects of colors is unclear; remove our
dependency and start using chalk instead.
---
=> chore: transition from using colors to chalk

packages/@jsii/kernel/lib/objects.ts, packages/@jsii/kernel/test/objects.test.ts
The jsii kernel needs to attach metadata to instances that are sent
across the process boundary. While these properties use symbol names to
eliminate the risk for collisions with user-defined properties, they
were inadvertently set as `enumerable`, causing those to show in outputs
of `JSON.stringify` and to be copied over as part of spat expressions
(e.g: `{...obj}`), which resulted in the new value sharing the same
identity as the previous one when sent over the wire.
Caused: https://github.com/aws/aws-cdk/issues/17876
---
=> fix(kernel): kernel's private object annotations are enumerable

packages/jsii/lib/assembler.ts, packages/jsii/lib/literate.ts, packages/jsii/test/literate.test.ts, packages/jsii/test/submodules.test.ts
The code literally was not there to extract literate examples for
submodule READMEs.
Fixes aws/aws-cdk#18589.
---
=> fix(jsii): submodule READMEs don't have literate examples

packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/JsiiMethodAttribute.cs, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/JsiiPropertyAttribute.cs, packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts, packages/jsii-pacmak/lib/targets/dotnet/dotnetruntimegenerator.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
A mis-understanding of the jsii specification early on was carried over
in the .NET code generators until now, which caused all methods and
properties that are overrides (of other JS implementations) to result in
jsii overrides being registered by the runtime.
This behavior caused unnecessary round-trips between the .NET CLR and
the node sidekick process, which affected the performance of .NET
bindings (unnecessary round-trips with JSON encoding aren't free), and
had a tendency to hit obscure edge case bugs in the jsii kernel's Ser/De
behavior.
This PR removes all `isOverride: true` declarations from generated .NET
code and neutralizes the behavior of specifying it to be true.
User-defined overrides (.NET code overriding JS code) continue to work
as they previously did (the `isOverride` …
=> fix(dontet): excessive overrides generated

packages/jsii-pacmak/lib/targets/go/package.ts, packages/jsii-pacmak/lib/targets/go/runtime/emit-arguments.ts, packages/jsii-pacmak/lib/targets/go/types/class.ts, packages/jsii-pacmak/lib/targets/go/types/enum.ts, packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts, packages/jsii-pacmak/lib/targets/go/types/go-type.ts, packages/jsii-pacmak/lib/targets/go/types/interface.ts, packages/jsii-pacmak/lib/targets/go/types/struct.ts, packages/jsii-pacmak/lib/targets/go/types/type-member.ts
The go code generator was previously holding multiple copies of the
`RootModule` objects for dependencies (one for the generated package's
own `RootModule`, and one for each submodule that uses a type from that
dependency), including their entire type hierarchy, methods and
properties.
On large packages, especially with many submodules, this results in an
extremely large resident set size. Pathological cases have required
heaps as big as 6 GiB.
De-duplicating the `RootModule` instances, and not retaining `GoTypeRef`
instances (which are stateless, and cheap to construct), allows reducing
those pathological modules to only occupy around 300 to 400 MiB worth of
heap, which is a very significant improvement.
The reduction of duplication also has significant performance benefits
on affected …
=> fix(pacmak): greatly reduce go code-gen memory footprint

packages/@jsii/go-runtime/jsii-runtime-go/cast.go, packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go, packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/typeregistry.go, packages/@jsii/go-runtime/jsii-runtime-go/runtime/runtime.go
With this PR, the type that is instantiated as JSII Proxy is looked up from the type registry using the TypeFQDN in the ref. If that type is registered in the type registry AND that type is assignable to the targeted value type, than that type is used to instantiate the JSII proxy. 
Fixes #3353 and relates to #2819.
---
=> feat(go): Use type registry to find the correct target type for JSII Proxy

.github/workflows/main.yml, packages/@jsii/check-node/src/constants.ts
As node 17.3+ is the 'current' release, it should be tested
and ideally supported. This is an odd-major version, so it
will EOL shortly after node 18 gets released.
---
=> chore: test against node 17.3+

packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
Empty dictionaries are false-y in Python, so the test that checked for
structs via the existence of a property mapping table was incorrect, as
it only checked truthiness of the mapping, instead of checking for it
being non-`None`.
Fixes #2846
---
=> fix(python): cannot call a method that takes an empty struct

.github/workflows/main.yml, packages/@jsii/go-runtime/go.mod, packages/@jsii/go-runtime/jsii-runtime-go/cast.go, packages/@jsii/go-runtime/jsii-runtime-go/go.mod, packages/@jsii/go-runtime/jsii-runtime-go/internal/objectstore/objectstore.go
This preserves compatibility with Go 1.16, as `CanConvert` was introduced
in go 1.17 only.
---
=> fix(go): replace uses of CanConvert to Type.AssignableTo

packages/jsii/lib/assembler.ts
The compiler un-necesarily re-renders `README.md` documents from
dependencies to inline `.lit.ts` references in there. This is wasted
effort as those doucments will not be emitted to the output assembly.
Stop processing `README.md` documents for any module coming from a
dependency.
Fixes https://github.com/aws/jsii/issues/3379
---
=> fix(jsii): dependencies' README files are unnecessarily re-rendered

superchain/Dockerfile, superchain/README.md
To test the SAM CDK integration test cases
- Build the docker image by running [this script](https://github.com/aws/jsii/blob/ceb66a6d60eb3c17867f5b823efec8236ddd5505/superchain/build-local.sh)
- Run the built image using the following command:
```
docker run --net=host \
--rm -it \
-v $HOME:$HOME \
-v /var/run/docker.sock:/var/run/docker.sock \
-v $PWD:$PWD -w $PWD \
-v /tmp:/tmp \
-e HOME=$HOME \
-e NPM_CONFIG_UNSAFE_PERM=true \
jsii/superchain:local
```
- Then you can run the following command inside the container:
```
cd packages/aws-cdk
test/integ/run-against-repo test/integ/cli/test.sh
```
Expected output
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CLI Integration Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
27.5.1
Using regions: us-east-1
Using framework version: * …
```
=> chore: add sam cli to the superchain image to execute the sam cdk integration testing

packages/jsii-pacmak/lib/targets/go/documentation.ts, packages/jsii-pacmak/lib/targets/go/types/class.ts, packages/jsii-pacmak/lib/targets/go/types/enum.ts, packages/jsii-pacmak/lib/targets/go/types/go-type.ts, packages/jsii-pacmak/lib/targets/go/types/interface.ts, packages/jsii-pacmak/lib/targets/go/types/struct.ts, packages/jsii-pacmak/lib/targets/go/types/type-member.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Most of the documentation text was incorrectly emitted on implementation
functions, which are not visible in documentation (as the structs that
are implementing the interfaces are not exported).
This moves the documentation text to the interface declarations instead,
so that they are visible in user-facing documentation.
Additionally, enum member documentation was simply not emitted, which is
addressed by this PR.
Setter documentations now only carry stability markers for the property
in order to avoid causing confusion by issuing the same documentation as
for the getter (which may be inappropriate).
This PR also adds transliterated example code to the generated
documentation, as the initial version of Rosetta support for Go is now
available.
---
By submitting this pull request, I confirm …
=> fix(go): lots of documentation is missing from generated code

packages/jsii-rosetta/lib/commands/transliterate.ts, packages/jsii-rosetta/test/commands/transliterate.test.ts
Allows passing an option `outdir` option to `transliterateAssembly`
command. This allows users to generate transliterated assemblies without
polluting the package directory if so desired.
Enables fixing of https://github.com/cdklabs/jsii-docgen/issues/390
---
=> feat: specify output directory for assemblies

.all-contributorsrc, README.md, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap, packages/jsii-rosetta/lib/languages/python.ts, packages/jsii-rosetta/test/translations/expressions/map-literal.cs, packages/jsii-rosetta/test/translations/expressions/map-literal.go, packages/jsii-rosetta/test/translations/expressions/map-literal.java, packages/jsii-rosetta/test/translations/expressions/map-literal.py, packages/jsii-rosetta/test/translations/expressions/map-literal.ts
The Python transliterator failed to properly account for maps when
transliterating keys, resulting in name-mangling being applied on these
when it should not have been.
This PR adds a new `inMap` context entry to track whether a property
assignment must be interpreted as a map key-value entry, or an actual
keyword/value mapping; and in that case circumvents the mangling.
Added a new test to verify that such map literals render appropriately
using a key similar to that which caused #3448.
Fixes #3448
---
=> fix(rosetta): incorrect transliteration of map keys in python

packages/jsii/lib/transforms/deprecation-warnings.ts, packages/jsii/test/deprecation-warnings.test.ts
Not everything can be added to a WeakSet, in particular, only objects
can be added there, no `undefined`, `null`, ...
This is causing an integration test failure at the moment.
---
=> chore(jsii): revert to using Set

packages/jsii-rosetta/lib/commands/transliterate.ts
Exposes the `unknownSnippets` configuration option on
`transliterateAssembly` to allow callers to choose how to handle
snippets missing from the tablet file.
---
=> feat: expose unknownSnippets config

packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
When a struct pointer was passed in an `interface{}` position, the
converter would trip and register a new opaque instance of `Object`
instead of correctly serializing a struct.
This is because hte pointer is double-indirected (the `interface{}` is a
reference to the `&struct`, which is a reference to the `struct`). This
change adds a condition to detect such cases (`interface{}` abstracts
another pointer), and properly serialize that.
Fixes #2880
---
=> fix(go): object type not recognized

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
This bug is due to a crazy interaction between the `publication`
module, the `__all__` array, and imports we might generate to do
type checking in a package that uses submodules.
Context
-------
Here's what you need to know:
- `__all__` is normally used to define the symbols and submodules
that should be imported when a consumer does `from mymod import *`.
- `publication` is used to hide non-public symbols from library
consumers. It will move all symbols that are NOT in `__all__` to
a `_private` submodule at runtime (it's overloading `__all__` a
little here, but this seems generally okay).
- We generate `imports` at the top of the file for the modules that are
referenced in a module, so that we can use them in type annotations.
Example
-------
This is what the currently generated code for …
=> fix(jsii): some submodules are not exported from `aws-cdk-lib`

.github/workflows/docker-images.yml, .github/workflows/main.yml, .mergify/config.yml, gh-pages/content/user-guides/lib-author/index.md, gh-pages/partials/node-support-table.md, packages/@jsii/check-node/package.json, packages/@jsii/check-node/src/constants.test.ts, packages/@jsii/check-node/src/constants.ts, packages/@jsii/check-node/src/index.test.ts, packages/@jsii/check-node/src/index.ts, superchain/README.md
This changes how the node release support information is modeled so that
the end-of-life dates are configured, so that `@jsii/check-node` can
automatically start warning a month ahead of a runtime's EOL date, so we
can drop support right on EOL day if needed wihtout taking users by
surprise.
This also includes tweaks of the messages that get printed out to STDERR
when an unsupported/untested/deprecated/end-of-life version is being
used, to increase clarity of provide more information about migration
options.
Finally, this adds node 18 (initial release `2022-04-19`) to the test
matrix.
---
=> chore: automated node runtime deprecation warnings

.github/workflows/docker-images.yml, superchain/Dockerfile, superchain/README.md
Changes the version of node that ships with the `1-buster-slim` and
`1-buster-slim-snapshot` images to node 14, as node 12 is now EOL.
This change should be transparent to the vast majority of users, as
node 14 is largely backwards-compatible with node 12.
This is a prerequisite to https://github.com/cdklabs/cdk-ops/pull/2010
---
=> chore(superchain): change default node version to 14

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Nested submodules were not registered in the `__all__` list of their
parent, and so were not visible to import statement such as
`from fully.qualified.submodule.path import Name`.
This changes how submodules get loaded so that they are always declared
and loaded with the context of their immediate parent sub•module, which
guarantees they are present in the relevant `__all__` list.
Fixes #3408
---
=> fix(python): cannot import nested submodules

packages/@jsii/spec/package.json, packages/@jsii/spec/src/validate-assembly.ts, yarn.lock
Switch from jsonschema to ajv to improve assembly validation performance.
Previously, loading the type system for aws-cdk-lib and constructs (combined) took around 15-17 seconds on my local development machine, using node v16.8.0. When I ran it with the updated version of @jsii/spec, it only took 750-800ms.
Both ajv and jsonschema are popular npm libraries (we also currently leverage it in the cdk8s-cli). ajv has one downside which is that introduces has a larger bundle size (1.02 MB vs 81.8kB), but I think it's worth it for the performance improvement.
Closes cdklabs/decdk#7
---
=> fix(@jsii/spec): speed up assembly validation by 20x for large libraries

packages/jsii-rosetta/lib/index.ts
Exports the `GoVisitor` class to allow Go doc generation
programatically.
Fixes: #3552
---
=> chore(jsii-rosetta): export `GoVisitor` from index

CHANGELOG.md, lerna.json, packages/@jsii/check-node/src/constants.ts, packages/@jsii/check-node/tsconfig.json, packages/@jsii/runtime/webpack.config.js
=> chore(release): v1.60.1 

packages/@jsii/benchmarks/lib/benchmark.ts, packages/jsii/lib/symbol-id.ts, packages/jsii/lib/utils.ts
The readFileSync calls there tend to process large JSON documents, which
is time-consuming. Basic profiling showed this is called repeatedly with
similar directories, so the time spent can be greatly reduced.
---
=> chore: cache heavy elements in assemblyRelativeSourceFile

superchain/Dockerfile
The current feed points to a CDN endpoint that may not include the latest version of the SDK.
This PR changes the feed to the one used by https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script, which is the recommended way of installing the SDK in CI environments. 
---
=> chore: switch dotnet feed to avoid CDN caching

.github/workflows/docker-images.yml
Failing to do so causes layers to be re-built when the tests
are executed, which is a tremendous waste of time...
---
=> chore: update layer cache last in workflow

gh-pages/content/overview/features.md
Since Go language  is generally available, change the status icon, too.
---
=> fix: Status icon for Go language that it is generally available.

.github/workflows/main.yml, packages/@jsii/benchmarks/lib/benchmark.ts, packages/@jsii/benchmarks/lib/index.ts, packages/@jsii/benchmarks/lib/suite/aws-cdk-lib/build-with-jsii.ts, packages/@jsii/benchmarks/lib/suite/aws-cdk-lib/build-with-tsc.ts, packages/@jsii/benchmarks/lib/suite/aws-cdk-lib/index.ts, packages/@jsii/benchmarks/lib/util.ts
The idea is to try and achieve a situation where iteration
times are not tainted by different memory situations (caches
may cause memory pressure and will skew the benchmark results).
Running in node sub-processes should allow removing this unknown
from the picture.
---
=> chore: run benchmarks in separate VMs

.github/workflows/docker-images.yml
ECR Public will throttle to 1 image pull/second.
Since we start multiple workflows in parallel, make sure they don't all pull from ECR Public at the exact same time by jittering their start times.
---
=> fix: jitter Docker build startup

packages/@jsii/kernel/src/kernel.test.ts, packages/@jsii/kernel/src/kernel.ts, packages/@jsii/kernel/src/serialization.test.ts, packages/@jsii/kernel/src/serialization.ts, packages/@jsii/kernel/src/serialization.ux.test.ts
Bring attention to error messages as part of the contract of the
`@jsii/kernel` serialization component, as such messages are currently a
known pain point (not specific enough, confusing, overloaded, ...).
Introducing snapshot tests, and quick win improvements to the existing
error messages where possible.
Fixes #3636 
---
=> chore: add UX tests around @jsii/kernel serializer errors

packages/@jsii/benchmarks/lib/constants.ts, packages/@jsii/benchmarks/lib/index.ts, packages/@jsii/benchmarks/lib/suite/aws-cdk-lib/index.ts, packages/@jsii/benchmarks/scripts/snapshot-package.ts
This is necessary as the previous benchark target had multiple occurrences
of enums with several constants having the same value, which is now illegal
in jsii code (#3207).
The fix for this (https://github.com/aws/aws-cdk/commit/7f4f150b97b5f58b936e6ed221a1b9bf67dad107) was released in CDK 2.31.0.
---
=> chore: upgrade benchmark to aws-cdk-lib v2.31.0

packages/jsii-rosetta/bin/jsii-rosetta.ts, packages/jsii-rosetta/lib/commands/extract.ts, packages/jsii-rosetta/lib/tablets/tablets.ts, packages/jsii-rosetta/test/commands/extract.test.ts
Usage: `yarn rosetta extract --compress-tablet`
This should reduce the `.jsii.tabl.json` size by about 90%.
---
=> feat(rosetta): tablets can be compressed

gh-pages/content/user-guides/lib-author/configuration/index.md, packages/jsii/lib/project-info.ts
Allow user control of the `baseUrl` and `paths` compiler options in
`tsconfig.json` via the `jsii.tsc` stanza in `package.json`.
Fixes #865
---
=> feat(jsii): allow specifying baseUrl and paths in tsconfig.json

.github/workflows/main.yml, .mergify/config.yml
.NET 5 has been out of support since May 10, 2022. It no longer receives
updates, and it is hence no longer useful to continue testing against
it. It has been superceded by .NET 6.
---
=> chore: stop testing .NET 5

packages/@jsii/spec/src/assembly-utils.ts, packages/jsii-rosetta/lib/jsii/assemblies.ts, packages/jsii-rosetta/test/commands/infuse.test.ts
The behavior of `rosetta infuse` was incorrectly handled before. `infuse` would always overwrite the `.jsii` file with the uncompressed assembly. This PR fixes that behavior by detecting whether or not there is a compressed file in the directory, and compressing if that is the case.
There are two alternative solutions I considered, primarily because I'm concerned that looking up the location of the compressed assembly can be considered a leaky abstraction:
- loading and looking into the contents of `.jsii` again to determine whether or not it is a file redirect. I did not choose this option as it involves additional loading, which will slow things down.
- We can expand the `LoadedAssembly` type to include information on whether or not the assembly was originally compressed. Then pass that …
=> fix(rosetta): infuse incorrectly handles compressed assemblies

packages/jsii-rosetta/bin/jsii-rosetta.ts, packages/jsii-rosetta/lib/commands/extract.ts, packages/jsii-rosetta/lib/commands/infuse.ts, packages/jsii-rosetta/lib/commands/trim-cache.ts, packages/jsii-rosetta/lib/jsii/assemblies.ts, packages/jsii-rosetta/lib/tablets/tablets.ts, packages/jsii-rosetta/test/commands/extract.test.ts, packages/jsii-rosetta/test/commands/infuse.test.ts, packages/jsii-rosetta/test/commands/trim-cache.test.ts
Unfortunately, #3652 was half-baked and this PR serves to finish handling tablet compression. It introduces the following:
- `compress-cache` cli option so that you can use a compressed cache file
- update  to all usages of `languageTablet.save()` to explicitly pass the compress flag
- `languageTablet.compressedSource`, which is set when we load from a compressed source, so that we can remember to save as a compressed source.
- `loadAllDefaultTablets` now handles compressed default tablets.
- a far more encompassing set of unit tests for the above features
---
=> fix(rosetta): tablet compression handled incorrectly in multiple places

.github/workflows/docker-images.yml
In order to reduce throttlin events, federate into AWS using the
GitHub OpenID Connect provider, and authenticate to ECR Public.
When no `AWS_ROLE_TO_ASSUME` secret is configured, federation is
skipped and the jitter is applied instead.
Also reduces parallelism of the `buildx` OCI provider so that
we can more reliably re-use layer caches across all platforms
without choking the runner's IO.
---
=> chore: federate into AWS to authenticate to ECR Public

packages/@jsii/java-runtime/pom.xml.t.js
In particular, allow using newer versions of Jackson that are not
susceptible to CVE-2020-36518. Also update junit, mockto and jetbrains
annotations to allow most recent versions.
---
=> chore(java): extend dependency ranges to allow new versions

CHANGELOG.md, lerna.json, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/lib/targets/python/type-name.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap, packages/jsii-pacmak/test/targets/python/type-name.test.ts
Formalize the contract that it is allowed to pass a dict in places where
a struct instance is expected (this provides less type checking guarantees,
and the developer is responsible for passing the right keys in).
This should address a false-positive issue with the runtime type-checking
introduced in 1.63.0 (#3660).Formalize the contract that it is allowed to pass a dict in places where
a struct instance is expected (this provides less type checking guarantees,
and the developer is responsible for passing the right keys in).
This should address a false-positive issue with the runtime type-checking
introduced in 1.63.0 (#3660).
--- …
=> chore(release): 1.63.1

packages/@jsii/python-runtime/tests/test_runtime_type_checking.py, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/lib/targets/python/type-name.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap, packages/jsii-rosetta/jest.config.mjs
The types must be referenced from the current module's root, including
nesting class names, or the names will not be defined.
---
=> fix(pyhon): under-qualified types used by dynamic type checking

packages/jsii-pacmak/lib/targets/go/package.ts, packages/jsii-pacmak/lib/targets/go/types/interface.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
Instead of generating one file will ALL the types in a given
(sub)module, emit one file per type within the (sub)module,
so that the compiler operates on smaller compilation units.
This should reduce the memory pressure the compiler
experiences when dealing with large libraries.
---
=> chore(go): emit one file per type

packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/TypeCheckingTests.cs, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts, packages/jsii-pacmak/lib/targets/dotnet/dotnettyperesolver.ts, packages/jsii-pacmak/lib/targets/dotnet/runtime-type-checking.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
The .NET runtime type checking was not checking type unions that
are nested within a collection (list or map), although this is
necessary since the `is <type>` guard does not allow making any
assumption about the contents of the collection.
This adds the missing checks, and replaces the guard clauses
with a `switch` statement using pattern matching, resulting
in somewhat more elegant code (also with better `null` safety).
---
=> fix(.net): missing dynamic type checking for collection-nested unions

packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/TypeCheckingTests.cs, packages/@jsii/go-runtime-test/project/runtime_type_checking_test.go, packages/@jsii/python-runtime/tests/test_runtime_type_checking.py, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/dotnet/runtime-type-checking.ts, packages/jsii-pacmak/lib/targets/go/runtime/runtime-type-checking.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
The code-gen for type unions was incorrect, as the value is typically
array-typed, and the generated code hence needs to treat the value as
such.
---
=> fix: type unions in variadic position leads to invalid code-gen

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/lib/targets/python/type-name.ts
Type references in a keyword property position may not have used
the aliased import as intended, resulting in a runtime error due
to referring to an undefined symbol.
Additionally, keyword properties referencing structs did not
allow dicts to be used in lieu of a struct instance.
---
=> fix(python): reference to type does not use alias

.github/workflows/main.yml, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
Some collection validations were emitted twice, due to a bad merge
conflict resolution.
Additionally, in certain cases where overrides are being emitted for
type unions, the type checking code made unnecessary assertions, some of
which ending up being prohibited by the compiler.
---
=> fix(java): type generation code-gen issues

packages/jsii-pacmak/lib/targets/go/package.ts
This improved the performance of cdktf get on our go/azure example by two minutes
---
=> perf(jsii-pacmak): cache type lookups for go

packages/jsii/lib/assembler.ts, packages/jsii/test/__snapshots__/negatives.test.js.snap, packages/jsii/test/promise.test.ts
The void-check only accounted for the literal `void` type, but failed to account for the `Promise<void>` case. This is now fixed.
Fixes #51
---
=> fix(jsii): unable to return Promise<void>

packages/@jsii/kernel/src/kernel.ts, packages/@jsii/kernel/src/tar-cache/index.ts
Windows does not allow renaming files that are currently open, or directories that contain open files. When antivirus software is used, files are open for analysis by the A/V software, making it impossible to rename files too quickly after they've been created.
This was already reported in #992 and addressed, however the issue was re-introduced in #3724, in which tarballs were extracted into temporary directories that were then renamed.
Changed the code back to a form taht extracts files directly into their final place instead of staging via a temporary space, and added comments warning maintainers about the specific issue being solved here, so that hopefully the problem does not get re-introduced again in the future.
Fixes #3751
---
By submitting this pull request, I confirm that my …
=> fix(kernel): EPERM on rename operation on Windows

superchain/Dockerfile
Adds the `acl` package to the superchain image.
A recent [projen PR](https://github.com/projen/projen/issues/2103) added a build-time dependency on the `getfacl` and `setfacl` tools in this package to workaround a bug in GitHub Actions. The package is included in the GHA `ubuntu-latest` image, but not superchain.
Should address: https://github.com/projen/projen/issues/2134
---
=> feat(superchain): add 'acl' package to support projen GHA

packages/@jsii/spec/src/assembly-utils.test.ts, packages/@jsii/spec/src/assembly-utils.ts, packages/@jsii/spec/src/redirect.ts, packages/@jsii/spec/src/validate-assembly.test.ts, packages/@jsii/spec/src/validate-assembly.ts
use the ajv error message formatter instead of only outputting the `e.message` as the later fails to include useful information to determine where the actual error is.
Turn the validation test into a snapshot test to draw attention on the error message format.
---
=> chore(spec): improve assembly validation error messages

packages/@jsii/python-runtime/src/jsii/_runtime.py, packages/@jsii/python-runtime/tests/test_runtime_type_checking.py, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/lib/targets/python/type-name.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
When methods are decorated by users (e.g: replaced with an alternate function that delegates back to the original one), type annotations are not carried over to the new function.
Since type checking code relied on dynamically accessing the checked function for the purpose of getting type hints,this resulted in unexpected errors when executing type checking code.
In order to address this, the type checking code now declares a stub function locally with the relevant type information in order to have a reliable/stable source of type annotations (these cannot be constructed dynamically as Python does not expose the necessary constructors).
--- …
=> fix(python): KeyError in type checks when decorating methods

packages/@jsii/python-runtime/tests/test_runtime_type_checking.py, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/lib/targets/python/type-name.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap, packages/jsii-pacmak/test/targets/python/type-name.test.ts, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap, yarn.lock
In certain cases, a function parameter may shadow an imported module name, resultin in run-time errors either during type-checking or during the type-cast that is performed before returning a kernel call's result.
This change adds a test case that covers this particular scenario in Python, and changes how foreign modules are imported so that an alias is always generated for those, removing the risk for collisions. It also moves the type-checking stubs out to the root of the module to remove the risk of more "runtime context" polluting the type evaluation.
Fixes https://github.com/aws/aws-cdk/issues/22975
---
=> fix(python): parameter names shadow imported modules

.github/workflows/close-stale-issues.yml
Reverts aws/jsii#3844
v6 is broken and was not ready for prod. It must have been accidentally released.
https://github.com/aws-actions/stale-issue-cleanup/tree/v6
=> fix: revert "chore(deps): Bump aws-actions/stale-issue-cleanup from 5 to 6"

superchain/Dockerfile
We recently ran into a situation where we ended up with with a Python distribution where the following failed:
```shell
$ python3
>>> import OpenSSL
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
from OpenSSL import crypto, SSL
File "/usr/local/lib/python3.7/dist-packages/OpenSSL/crypto.py", line 3268, in <module>
_lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```
Because we had `cryptography==39.0.0` but `PyOpenSSL==22.0.0`, which should have been `22.1.0`.
The reason `PyOpenSSL` was held back looks to be because SAM CLI had a hardcoded dependency on the old version.
To prevent this from happening in the future, use …
=> chore(superchain): use `pipx` instead of `pip` to install CLIs

superchain/Dockerfile
=> chore: revert "chore(superchain): use `pipx` instead of `pip` to install CLIs"

.github/workflows/yarn-upgrade.yml, package.json, packages/jsii-config/package.json, yarn.lock
There are a couple of issues with some version updates
- Only do minor version updates for `@types/fs-extra` This is the last major version that is compatible with typescript@3.9
- `@types/yargs` is on longer compatible with typescript@3.9 so we need to pin it
- Other deps have a transient dependency on `@types/yargs` so add a resolution to keep the version
- `eslint-plugin-import@27` breaks something. For some reason when this is upgraded the build for `@scope/jsii-calc-base-of-base` fails with this error and I have no idea why
```
packages/jsii-rosetta/lib/languages/record-references.js:11
class RecordReferencesVisitor extends default_1.DefaultVisitor {
^
TypeError: Class extends value undefined is not a constructor or null
at Object.<anonymous> …
```
=> chore: fix version updates

packages/@jsii/check-node/src/constants.ts, packages/@jsii/check-node/src/index.ts
This can be useful, for example in projen templates, to automatically test fo all "supported" Node releases without having ot modify every single repository. This can serve as a central point of truth for what releases of node are supported by the Constructs ecosystem via jsii.
---
=> feat(check-node): export NodeRelease class

packages/jsii-rosetta/lib/languages/go.ts
The go transliteration uses a heuristic to determine if a property access expression is possibly a type name reference, however it failed to check whether the lead contains a call expression, which would make it impossible that the overall expression is a type reference.
This fixes the regular expression to address this.
Backports a fix from [4.9](https://github.com/aws/jsii-rosetta/pull/7).
---
=> fix(rosetta): go may incorrectly emit _ instead of .

packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/TypeCache.cs, packages/jsii-pacmak/lib/targets/dotnet.ts, packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
Issues where encountered with SDK compatibility when the target
was set to `net6.0` even when the .NET SDK 6.0 or newer was in
use. I suspect this is because of conflicting framework dependency
requirements across various packages.
Re-target `netcoreapp3.1` while setting a roll-forward policy allowing
use of newer major-releases of the SDK when no exact match is found (this
is tested to work correctly for all supported .NET SDK releases by our
automated test suite).
---
=> fix(dotnet): target netcoreapp3.1 with RollForward

packages/@jsii/kernel/src/serialization.ts
The JSON serialization class is a quasi-synonym for `Map<string, any>`, except it is meant to accept any valid JSON object, including one with `null` values. The serializer was however interpreting these as `Map<string, JSON>` when wired as a `$jsii.map` envelope, and this serialization class does NOT allow for null values.
Addresses the "easy" part of aws/aws-cdk#14639 (more complicated is that it would need to preserve `null` across the process boundary, which is currently not possible).
---
=> fix(kernel): json deserialization fails on `null` value

packages/jsii-rosetta/package.json, packages/jsii/package.json
Preparing for the upcoming release of jsii@v4.9 and jsii-rosetta@v4.9, set up `publishConfig` for both `v1` packages so they no longer get released against the `latest` dist-tag, and instead get released against the `v1` dist-tag (`latest` will promptly point to `4.9.0`).
---
=> chore: configure default tag for jsii & jsii-rosetta

packages/@jsii/python-runtime/tests/test_invoke_bin.py, packages/jsii/lib/symbol-id.ts, packages/jsii/lib/types-versions.ts, packages/jsii/test/types-versions.test.ts
When using types sourced from redirected declarations files (using `typesVersions`), the `symbolId` generated for type lookups incorrectly refers to the redirected path instead of the canonical one. This adds code to reverse the `typesVersions` mapping to get back to the original and canonical path.
---
=> fix(jsii): incorrect symbol-id generated with typesVersions

packages/jsii-rosetta/lib/json.ts, packages/jsii-rosetta/lib/tablets/tablets.ts
It appears the trim-cache test using tablet compression occasionally fails in CI/CD. I suspect this is due to the `save` function returning before the GZip stream has bene closed, resulting in the subsequent read attempting to consume an incomplete GZip object.
This adds the necessary provisions to ensure the GZip stream is closed (or failed) before `save` returns.
---
=> fix(rosetta): flakey trim-cache test

packages/jsii-rosetta/lib/json.ts
https://github.com/aws/jsii/commit/d2ecb6d2a6a460e309e4985dc001a6b749b3aac7 inadvertently introduced `node:` pseudo-protocol imports, which require use of more modern nodes than what is advertised. Massage them back into the old-school un-qualified name.
---
=> chore: remove node: pseudo-protocol

README.md, gh-pages/content/compiler-and-rosetta-maintenance.md, gh-pages/content/overview/toolchain.md, gh-pages/mkdocs.yml
Since we have released `jsii@5.0.x` and `jsii-rosetta@5.0.x` and have been using it for a while to build & release the AWS CDK, without any significant surprise so far, we are moving forward with announcing the placement of `jsii@1.x` and `jsii-rosetta@1.x` into maintenance, and are actively encouraging customers to migrate to the new release lines.
---
=> docs: publish jsii@1.x and jsii-rosetta@1.x maintenance announcement

packages/jsii-rosetta/lib/index.ts, packages/jsii-rosetta/lib/upgrade-prompt.ts, packages/jsii/lib/index.ts, packages/jsii/lib/upgrade-prompt.ts
This is to strongly incitate customers upgrade their dependencies, while trying to avoid alarming (there is 18 months left before the End-of-Support is scheduled, which is PLENTY of time).
---
=> chore: add upgrade prompt at load of jsii and jsii-rosetta 1.x

packages/@jsii/check-node/src/index.ts, packages/@jsii/python-runtime/tests/test_invoke_bin.py
Currently tests are failing with end of life warning messages. This PR is adding env variable for tests to silence these errors.
---
=> chore: silence node end of life warning in tests

packages/codemaker/src/codemaker.ts, packages/jsii-pacmak/lib/targets/go/package.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
Our `go docs` have been broken since jsii `v1.65.0`. This was due to moving to emitting one file per type and headers being added to all those files: [Impacting PR](https://github.com/aws/jsii/pull/3698/files#diff-0a99c713a1282d6efe349c932d74dbfbdf1d926834c46ebfb5d65daeb27073f3R263)
The first occurrence was in [docs for cdk v2.39.0](https://pkg.go.dev/github.com/aws/aws-cdk-go/awscdk/v2@v2.39.0) and is still present in the [latest version](https://pkg.go.dev/github.com/aws/aws-cdk-go/awscdk/v2).
The header being added is `Version 2 of the AWS Cloud Development Kit library` to multiple files. It's determining this value from the [package.json](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/package.json#L4) file of `aws-cdk-lib`. I see adding this is most relevant for …
=> fix(pacmak): go docs overview displays repeating description

packages/jsii-diff/README.md, packages/jsii-diff/bin/jsii-diff.ts, packages/jsii-diff/lib/diagnostics.ts, packages/jsii-diff/test/diagnostics.test.ts
In certain situations one might want to treat changes to `external` APIs as errors.
This could be to check the external APIs for any breaking changes and have an opportunity to selectively reject, heal or soften an upstream change.
This change introduces a new cli option `--error-on` which can be one of three classes:
| `--error-on`       | Stabilities that cause an ERROR                    |
| ------------------ | -------------------------------------------------- |
| `prod` (default)   | `stable`, `deprecated`                             |
| `non-experimental` | `stable`, `deprecated`, `external`                 |
| `all`              | `stable`, `deprecated`, `experimental`, `external` |
**Fixes `deprecated` APIs not being treated as `stable`.**
In jsii, deprecations are treated as a …
=> feat(jsii-diff): allow external stability to be treated as error

packages/jsii-pacmak/lib/index.ts, packages/jsii-pacmak/lib/suppress-jsii-upgrade-prompts.ts, packages/jsii-rosetta/lib/index.ts, packages/jsii-rosetta/lib/upgrade-prompt.ts
`jsii-pacmak` has a dependency on `jsii-rosetta`, which has a dependency on `jsii`. An upgrade prompt will be printed for `jsii` and then `jsii-rosetta`, despite customers have no way to influence the version that is installed as a transitive dependency from `jsii-pacmak`.
This adds suppressions such that:
- `jsii-pacmak` suppresses the warning before loading `jsii-rosetta`
- `jsii-rosetta` suppresses further warnings after having emitted its own, and now emits the warning first thing when it loads (instead of last before)
---
=> chore: suppress extraneous upgrade prompts

packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
We are currently emitting `@returns`, but:
```
error: unknown tag: returns
* @returns a newly built instance of {@link software.amazon.awscdk.services.codedeploy.EcsDeploymentConfig}.
```
It should be `@return`.
---
=> fix(jsii-pacmak): emit correct `@return` tag for JavaDocs

packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
Our generated javadocs have some problems (PRs are out to fix them). We need to disable `doclint` otherwise proper error messages and doc failures get lost between the linting errors.
---
=> fix(jsii-pacmak): disable `doclint`

packages/@jsii/go-runtime-test/project/callbacks_test.go, packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/callbacks.go, packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/manage-object.go, packages/jsii-calc/lib/compliance.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
When passing arbitrary structs through an `interface{}` type, the JS value had no properties or methods, leading to it having an empty object JSON representation.
In order to improve the situation, discover exported properties of such structs, and register them as property callbacks, more closely matching the behavior of JS in the same configuration.
The callbacks use the same naming transformation as the standard JSON serialization mechanism in go: using the `json` tag if present with the same semantics as `encoding/json`, and fall back to the raw field name otherwise (with no case conversion applied).
Related: cdk8s-team/cdk8s#1326
--- …
=> feat(go): register exported properties as callbacks

CHANGELOG.md
These were generated incorrectly during the release because the previous release PR was accidentally squashed.
---
=> chore: fix 1.83.0 release notes

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii/lib/project-info.ts
Previously, `jsii` required the package's stability to be `deprecated` if there cas a `deprecated` message configured. This is however problematic when a `stable` package reaches End-of-Support and the maintainer wants to signal this in npmjs.com.
Instead of failing, only log a warning to possibly raise awareness on an unintended configuration.
Additionally - emit the `Development Status :: 7 - Inactive` trove classifier on packages with a `deprecated` message, even if their stability is not `deprecated`.
---
=> feat(jsii): allow specifying a deprecation message regardless of stability

packages/@jsii/runtime/bin/jsii-runtime.ts
This was leftover from a time when we tried using non-duplex streams, but since we are using a single duplex stream there's only 4 FDs (0 through 3), and not 5.
Thanks to @TimothyJones for finding it.
---
=> chore: fix confusing comment about FD number 4 that does not exist

packages/jsii-rosetta/bin/jsii-rosetta.ts, packages/jsii-rosetta/lib/index.ts
Backport of https://github.com/aws/jsii-rosetta/pull/121
---
=> fix: export transliterateAssembly and fix bug with transliterate cli (backport)

.github/workflows/pr-labeler.yml
The pr labeler workflow must run as the automation user and not the github-actions bot in order to trigger other workflows. This is an intentional limitation by GitHub.
---
=> chore: fix pr labeler workflow does not trigger auto-approval

CONTRIBUTING.md, superchain/Dockerfile
This PR resolves Issue #4080 and bumps version of the maven from `3.9.2` to `3.9.3`.
---
=> chore(superchain): maven version, docs: CONTRIBUTING.md

.github/workflows/yarn-upgrade.yml
Our dependencies are starting to [reject](https://github.com/aws/jsii/actions/runs/5532321392/jobs/10105940432) node 14.
```console
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error @typescript-eslint/eslint-plugin@[6](https://github.com/aws/jsii/actions/runs/5532321392/jobs/10105940432#step:8:7).0.0: The engine "node" is incompatible with this module. Expected version "^16.0.0 || >=18.0.0". Got "14.21.3"
```
---
=> chore: use node 16 in upgrade workflows

packages/@jsii/python-runtime/src/jsii/__init__.py, packages/@jsii/python-runtime/tests/test_invoke_bin.py
As Python 3.7 has reached end-of-life on 2023-06-27, we will now be warning customers using it, and prompting them to upgrade to Python 3.8 or newer at their earliest convenience.
---
=> feat(python): deprecation message when using Python <= 3.7

packages/jsii-calc/bin/run.ts, packages/jsii-calc/lib/documented.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
When a comment contains `*/` (for any reason, in our case because the escaped version is unescaped within JSII) it should be escaped to not make the file invalid
=> fix(jsii-pacmak): comment lines should not contain comment ending

packages/@jsii/kernel/src/objects.test.ts, packages/@jsii/kernel/src/objects.ts
The registration was done on the object's prototype, and the value from the constructor was always used, even if that was inherited, such that if a parent type had already been resolved previously, all child types would use the parent's FQN instead of their own.
Addressed this by instead storing the associations in an external WeakMap, and added a test case to validate correct behavior.
Fixes aws/aws-cdk#26604
Fixes #4202
Fixes #4203
---
=> fix(kernel): incorrectly scoped FQN resolutions

superchain/Dockerfile, superchain/build-local.sh
The packages were installed in a virtual environment, which is not subsequently re-activated in the image's ENTRYPOINT. Instead, install the packages 'globally'
---
=> fix: pip, black, setuptools, twine, wheel, and aws-sam-cli incorrectly installed in superchain

packages/@jsii/python-runtime/src/jsii/_reference_map.py
In the odd case where an opaque reference is returned (FQN is `Object`) and no interfaces are registered, the `InterfaceDynamicProxy` instance created to represent the value in Python did not have any delegate, resulting it in not having any visible properties; including a `__jsii_type__` value on the `__class__`, or the `__jsii_ref__` property, both of which are required for the vlaue to be able to correctly make it back to JavaScript.
---
=> fix(python): type object 'InterfaceDynamicProxy' has no attribute '__jsii_type__'

packages/@jsii/kernel/src/link.ts
In https://github.com/aws/jsii/pull/4181, a faster method to load modules was introduced: symlinking instead of recursing through the directory tree, mostly affecting the load times of large modules.
Since Windows Vista, non-Administrator users on Windows aren't allowed to create symlinks anymore, so this new loading method fails for users working in corporate Windows environments.
Catch the error and fall back to the slower copying method if that happens.
Fixes #4208.
---
=> fix(kernel): fast module loading fails on Windows (EPERM)

superchain/Dockerfile, superchain/build-local.sh
In #4201, we introduced a Python distribution built with `pyenv` in order to safely install some Python packages globally.
However, using pyenv drives the build time of the images up from 30m to 3 hours.
This PR switches back to the distro Python and installs `pipx` to do global installs of Python packages. `pipx` will give each tool its own venv (similar to how `npm install -g` would work).
---
=> chore(superchain): replace pyenv with pipx

superchain/Dockerfile
This was erroneously deleted and is necessary because we want the `ssh-keyscan` command.
Added: https://github.com/aws/jsii/commit/f95f88c861fb2336a88339a4cf45cb5671b79fe4
Deleted: https://github.com/aws/jsii/pull/4219/files 
```
/codebuild/output/tmp/script.sh: ssh-keyscan: not found
```
At least I think this is the solution because stack overflow tells me that `openssh-client` has `ssh-keyscan`: https://stackoverflow.com/questions/32665746/ssh-keyscan-not-found-in-dockerfile
---
=> fix(superchain): add openssh-client back

gh-pages/mkdocs.yml
Fixes the following error in the pages build workflow ([example](https://github.com/aws/jsii/actions/runs/6720427611)):
```
INFO    -  DeprecationWarning: 'materialx.emoji.twemoji' is deprecated.
Material emoji logic has been officially moved into mkdocs-material
version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
as mkdocs_material_extensions is deprecated and will no longer be
supported moving forward. This is the last release.
```
---
=> chore: fix pages build

packages/jsii-reflect/lib/_memoized.ts, packages/jsii-reflect/lib/class.ts, packages/jsii-reflect/lib/method.ts, packages/jsii-reflect/lib/type-system.ts, packages/jsii-reflect/lib/type.ts, packages/jsii-reflect/test/_memoized.test.ts
Memoizes additional calls that rely on the typesystem to retrieve type instances.
These calls can (theoretically) change when the typesystem is changed.
Therefore we cannot assume it's okay to always memoize the first call.
To workaround this limitation, we introduce a new mechanism to manually `lock` the typesystem once all assemblies are loaded.
We then can start memoizing the additional calls.
For example in `awslint` this reduces the runtime against `aws-cdk-lib` by ~20s.
---
=> feat(jsii-reflect): TypeSystem can be locked to improve reflection performance

.github/workflows/docker-images.yml, .github/workflows/main.yml, packages/@jsii/check-node/src/constants.ts, packages/@jsii/check-node/src/index.test.ts, packages/@jsii/check-node/src/index.ts, packages/@jsii/python-runtime/tests/test_invoke_bin.py, superchain/Dockerfile, superchain/README.md
Removes testing and superchain releases for EOL Node 16
Deprecation and EOL messages of node versions are automated, so no need to announce or wait.
We are well past the promised 30 days support after Node 16 went EOL.
---
=> feat: make node 18 the default

packages/@jsii/kernel/src/kernel.ts, packages/@jsii/kernel/src/tar-cache/index.ts, packages/jsii-calc/bin/run.ts
Invoking bin scripts from jsii packages would fail if the symlinked cache was enabled and the invoked script depended on an other package. The reason for this was that scripts were only invoked with `--preserve-symlinks`, however for "main scripts" (like standalone binaries), we also need to call `--preserve-symlinks-main` on the node process.
Note this cannot be tested in the kernel package itself, as it's not possible to invoke the test process with the correct options. 
---
=> fix(kernel): invokeBinScript fails when using symlinked cache

.github/workflows/main.yml, CONTRIBUTING.md, gh-pages/content/user-guides/language-support/index.md, gh-pages/content/user-guides/lib-author/configuration/targets/python.md, gh-pages/content/user-guides/lib-author/index.md, packages/@jsii/python-runtime/pyproject.toml, packages/@jsii/python-runtime/setup.py, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Python 3.7 has been end-of-life since 2023-06-27, and an increasing amount of our dependencies are dropping support for it as a consequence.
We introduced a warning to users that are still using Python 3.7 with release v1.86.0 around August 1, 2023.
We are now effectively dropping support for Python 3.7.
Related: https://github.com/aws/jsii/commit/0ef7acef765690f99075888d6c3e6f03d7cc2d59
Re-roll of #4239, which was reverted because the build & release pipeline failed. After some investigation this was because the job used a superchain image with python3.7. However after this change a minimum version of python 3.8 is required.
BREAKING CHANGE: jsii-pacmak and the libraries it generates for Python targets now require a minimum Python version of 3.8, instead of 3.7 previously. We recommend …
=> feat: switch to python 3.8 (#4239)

packages/jsii-pacmak/test/build-test.sh, packages/jsii-pacmak/test/generated-code/python-pyright.test.ts, superchain/Dockerfile
Running the jsii-pacmak build tests inside a `jsii/superchain:1-bullseye-slim-nightly` container would fail with "invalid command 'bdist_wheel'".
This was due to an outdated & unsupported (by jsii) version of `setuptools` being present in the image.
In https://github.com/aws/jsii/pull/4219 we inadvertently removed installing a newer version of `setuptools`.
---
=> fix(superchain): installed setuptools is an unsupported version

.github/workflows/yarn-upgrade.yml
Workflow currently fails due to the Node version being incompatible with used packages.
---
=> chore: use Node 18 in yarn upgrade workflow

.github/workflows/docker-images.yml
Add a GitHub action to update the DockerHub README of the superchain image every day.
Needed to to refactor the steps a little bit to get the credentials out in a way the Action needs them.
(Of course, no way to test this except in production :/ )
---
=> chore: update DockerHub README daily

.github/workflows/docker-images.yml, superchain/README.md
jsii now requires Python 3.8
Debian Buster only ships with Python 3.7 and we recommend users to upgrade to Bullseye based images.
Let's stop building Buster images.
Also clarifies our build permutations in the README.
---
=> feat: deprecate `jsii/superchain:buster-slim-*` images

packages/@jsii/check-node/src/constants.ts
Any downstream packages that use `NodeRelease.supported` to compute a list of active Node versions currently believe they should test again Node 21, which we don't actually want.
---
=> fix(check-node): unstable node 21 is incorrectly listed as supported

gh-pages/content/overview/runtime-architecture.md, packages/@jsii/kernel/src/kernel.ts, packages/@jsii/python-runtime/tests/test_invoke_bin.py, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
This was previously attempted to fix in https://github.com/aws/jsii/pull/4324 While the above fix resolves issues with dependencies, it causes failures when the binary is shelling out to other node processes. This is due to the intrusive and indiscriminate overloading of NODE_OPTIONS, which will forcibly apply to any child processes as well. While in theory adding the symlink flags should not be an issue, this seems to trigger a bug in node: https://github.com/nodejs/node/issues/41000
tl;dr this all sucks very much and we are now just disabling the runtime cache for binaries.
---
=> fix(pacmak): invokeBinScript fails when using symlinked cache

superchain/Dockerfile
These are now downloaded from https://downloads.apache.org/
---
=> chore(superchain): fix maven downloads failing due to outdated urls

packages/jsii-pacmak/lib/index.ts
Currently 'npm pack' is shown in the logs regardless of the custom command.  Like in:
```log
[jsii-pacmak] [INFO] Packaged. npm pack (42.4s) | cleanup (3.8s) | load jsii (0.0s) | js (0.0s)
```
This behaviour is confusing because it leaves doubt about which command was actually applied. This PR passes the value of the pack-command option to the timer label.
---
=> fix(jsii-pacmak): show custom pack-command in timer label

packages/@jsii/go-runtime/jsii-runtime-go/helpers.go, packages/@jsii/go-runtime/jsii-runtime-go/jsii.go
=> chore(docs): fix typo in go helper function Doc Comment

.github/workflows/close-stale-issues.yml, .github/workflows/closed-issue-message.yml
Based on customer feedback, AWS SDKs are making minor changes to our GitHub workflows:
* The close issue message is too mean and too full of emoji.
* The stale issue timings are too tight, especially on holidays and weekends.
---
=> chore: minor github workflow changes

packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
In Bazel, every package is extracted into a separate directory that are all put into the `$PYTHONPATH` individually. However when searching, Python will latch onto the directory that has an `__init__.py` in it and only import from that directory.
Example:
```
eco_package1/
└── site-packages/
└── eco/
   └── package1/
└── __init__.py
eco/
└── site-packages/
└── eco/
   └── __init__.py
```
In this case, the following command will fail:
```py
import eco.package1
```
Because `eco/package1/__init__.py` is not in the same directory as `eco/__init__.py`.
We can fix this by generating a command into every `__init__.py` that uses `pkgutil` to extend the search path for a package; it will put all directories in `$PYTHONPATH` that contain the same package onto the search path for submodules. The …
=> fix(jsii-pacmak): different packages sharing a namespace fail in Bazel

packages/@jsii/python-runtime/requirements.txt
Reverts aws/jsii#4439
Apparently version 8.1.0 has been [yanked](https://pypi.org/project/pytest/8.1.0/) and is now causing builds to [fail](https://github.com/aws/jsii/actions/runs/8153733563/job/22285706848?pr=4443):
```console
@jsii/python-runtime: ERROR: No matching distribution found for pytest~=8.1
```
=> revert(deps): Update pytest requirement from ~=8.1 to ~=8.0 in /packages/@jsii/python-runtime

packages/jsii-pacmak/lib/targets/version-utils.ts, packages/jsii-pacmak/test/targets/version-utils.test.ts, superchain/Dockerfile
`jsii-pacmak`'s current version logic does not fully implement/adhere to PEP440 in two respects:
* There is no support for "[local version identifiers](https://packaging.python.org/en/latest/specifications/version-specifiers/#local-version-identifiers)", which are basically the same as SemVer's build metadata (e.g. `1.2.3+foobar`), when used in conjunction with a pre-release label.
* The current pre-release logic doesn't reflect the ability for python pre-releases to include [post-release](https://packaging.python.org/en/latest/specifications/version-specifiers/#post-releases) and [developmental release](https://packaging.python.org/en/latest/specifications/version-specifiers/#developmental-releases) labels in conjunction with the pre-release itself (e.g. `1.2.3.rc1.post2.dev3`)
This PR …
=> fix(jsii-pacmak): fully support the Python Version Identification part of PEP440

gh-pages/requirements-dev.txt
The most recent Dependabot update updated `mkdocs` in such a way that our dependencies are now incompatible.
Bumping `mkdocs-material` as well seems to solve it.
---
=> chore: bump mkdocs-material

.github/workflows/main.yml, gh-pages/content/overview/toolchain.md, gh-pages/content/user-guides/language-support/index.md, packages/jsii-pacmak/.eslintrc.yaml, packages/jsii-pacmak/bin/jsii-pacmak.ts, packages/jsii-pacmak/lib/builder.ts, packages/jsii-pacmak/lib/index.ts, packages/jsii-pacmak/lib/suppress-jsii-upgrade-prompts.ts, packages/jsii-pacmak/lib/target.ts, packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts, packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts, packages/jsii-pacmak/lib/targets/go.ts, packages/jsii-pacmak/lib/targets/go/documentation.ts, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/package.json, packages/jsii-pacmak/test/targets/go.test.ts, packages/jsii-reflect/lib/class.ts, scripts/align-version.js
Fixes #4098 
Previously jsii-pacmak depended on jsii-rosetta 1.x. This is problematic if a different version of the jsii compiler was used, because it introduced different versions of TypeScript into the project.
With this PR, the dependency is changed to a peer dependency. Thus allowing any compatible version jsii-rosetta to be used. 
BREAKING CHANGE: jsii-pacmak now has a peer dependency on jsii-rosetta. Please ensure a version of jsii-rosetta matching your version of jsii is available. Most package managers install peer dependencies automatically and no change is required. However users of yarn v1 or npm v3 to v6 must install jsii-rosetta manually.
---
[Apache 2.0 …
=> fix(pacmak): jsii-pacmak uses incompatible version of jsii-rosetta

packages/jsii-reflect/lib/enum.ts, packages/jsii-reflect/lib/interface.ts
This helps downstream consumers to not have to add type annotations themselves when using these methods.
Before:
```ts
function needsInterface(type: reflect.InterfaceType) {}
if (type.isInterfaceType()) {
needsInterface(type as reflect.InterfaceType);
}
```
After:
```ts
function needsInterface(type: reflect.InterfaceType) {}
if (type.isInterfaceType()) {
needsInterface(type);
}
```
---
=> fix(reflect): additional type predicates for `isXyzType` methods

.github/workflows/docker-images.yml, superchain/README.md
There are a lot of image tags in the jsii/superchain image repo. Only a few of which are actively supported.
Previously we attempted to explain the rules and list supported versions of the subcomponents, but that was complicated and missed a few cases.
With this change we are just listing them explicitly.
---
=> chore(superchain): explicitly list supported images

gh-pages/content/specification/2-type-system.md, gh-pages/content/specification/3-kernel-api.md, jest.config.mjs, packages/jsii-rosetta/lib/languages/go.ts, packages/jsii-rosetta/lib/submodule-reference.ts, packages/jsii/lib/assembler.ts, packages/jsii/lib/jsii-diagnostic.ts, packages/jsii/lib/validator.ts, packages/jsii/test/__snapshots__/negatives.test.js.snap
Observed the error below: `The implemented delcaration is here.`
`delcaration` - I kept looking at this because it hurt my eyes until I finally realized it was a typo.
At the very least, this can be closed as won't fix so that at least there will be a record for the next person that searches for an issue or fix for it.
```
[2024-05-15T12:22:12.636] [ERROR] jsii/compiler - Type model errors prevented the JSII assembly from being created
src/myconstruct.ts:191:31 - error JSII5004: "cdkConstruct.MyConstruct#dynamoDBTable" changes the property type to "aws-cdk-lib.aws_dynamodb.Table" when implementing cdkConstruct.IMyConstruct. Change it to "aws-cdk-lib.aws_dynamodb.ITable"
191   public get dynamoDBTable(): dynamodb.Table | undefined {
~~~~~~~~~~~~~~~~~~~~~~~~~~
src/myconstruct.ts:174:28
174 …
```
=> chore: fix typo in error message - `delcaration`

packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
Twine 5.1.0 has been yanked (removed) due to the issue described in https://github.com/pypa/twine/issues/1125
This PR reverts the `requirements-dev.txt` file used by `jsii-pacmak` back to `twine~=5.0.0`.
=> fix(pacmak): Twine 5.1.0 not found

package.json, yarn.lock
See https://github.com/advisories/GHSA-f5x3-32g6-xq36
The affected version of `tar` is only used in build tooling, i.e. no risk to published packages.
---
=> chore: upgrade lerna to fix CVE with tar dependency

superchain/README.md
Also adds a numeric version number because codenames make it hard to know what versions are newer.
---
=> chore: fix incorrect debian codenames in superchain support table

.github/workflows/main.yml, CONTRIBUTING.md, gh-pages/content/overview/toolchain.md, gh-pages/content/user-guides/language-support/index.md, packages/@jsii/go-runtime/build-tools/package.sh, packages/jsii-pacmak/package.json
Declare support in peerDependencies and add integration test.
Updated some docs while I'm at it.
---
=> fix(pacmak): support jsii-rosetta 5.5

packages/@jsii/python-runtime/src/jsii/_runtime.py, packages/@jsii/python-runtime/tests/test_python.py
In https://github.com/aws/jsii/pull/4611, we added the `_jsii_proxy_class__` attributes to the `@jsii.interface` implementations. This was required in order to comply with `typeguard` protocol checking. We didn't implement it correctly, accidentally overriding user defined proxy classes.
I have been wrecking my brain trying to understand if this bug has any runtime implications, and I couldn't find any.
At runtime, from what I could gather, the `__jsii_proxy_class__` attribute is only used when we try to instantiate a subclass of an abstract class:
https://github.com/aws/jsii/blob/dc77d6c7016bcb7531f6e374243410f969ea1fbf/packages/%40jsii/python-runtime/src/jsii/_reference_map.py#L65-L70
However, for abstract classes, we assign an explicit value to `__jsii_proxy_class__`: …
=> fix(python): user defined `__jsii_proxy_class` attributes are not preserved 

.github/ISSUE_TEMPLATE/bug-report.yml, .github/workflows/issue-regression-labeler.yml
- Modified bug issue template to add checkbox to report potential regression.
- Added GitHub action to add/remove label `potential-regression` when issue is created/edited.
Label `potential-regression` would make issue standout in the list and help engineers to handle high severity issues effectively.
**NOTE:**
- The GitHub action code was ported from CDK repo.
- The label `potential-regression` would need to be created manually (we could use color `#FF6700` and description `Marking this issue as a potential regression to be checked by team member` to make it consistent across SDK repos)
---
=> chore: modified bug issue template to add checkbox to report potential regression

.mergify/config.yml
We are using deprecated parameters that are about to be removed (October 21st, 2024).
Ideally we should move away from Mergify and use GitHub merge queues. But the config for this repository is more complex, with many pull request rules. Let's avoid breaking the PRs for now and then we can come back and migrate to merge queues.
---
=> chore(mergify): move deprecated parameters from `pull_request_rules` to `queue_rules`

.github/workflows/docker-images.yml
Need this for testing.
Also fixed a deprecated input parameter name in the workflow.
---
=> ci: allow manual dispatch of superchain build

.github/workflows/gh-pages.yml, .github/workflows/main.yml, .github/workflows/yarn-upgrade.yml
Version 3 is now [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
---
=> chore: upgrade `actions/upload-artifact` to v4

.github/workflows/gh-pages.yml, .github/workflows/main.yml, .github/workflows/yarn-upgrade.yml
LOL. Version 3 is now [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
---
=> chore(deps): upgrade actions/download-artifact to v4

packages/jsii-calc/lib/calculator.ts
Required by a new ESLint rule.
---
=> chore: use nullish coalescing instead of the ternary operator

packages/@jsii/java-runtime/pom.xml.t.js
2.13 has issues, so we should support newer versions as well.
---
=> fix(java-runtime): raise Jackson version bound to 2.19.0

packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
Our recent `jsii-pacmak` release contained an update to `twine` which exhibits a failure when combined with specific versions of `packaging`.
When reading the [bug thread](https://github.com/pypa/twine/issues/1216) the root cause seems to be `setuptools`, but the workaround seems to depend on the installed version of `packaging`.
`twine` declares a dependency on `packaging>=24.0.0` and the bug doesn't appear if `24.2` is installed. As a result, the problem shows on Python distributions that come with `packaging@24.0` or `packaging@24.1` preinstalled.
If an older version or no version of `packaging` is preinstalled then `pip` will install a fresh copy and it will pick `24.2`, but older versions match the declared version range and the pre-existing version will be used, which leads to the …
=> fix: Python publishing fails on some Python distributions

packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers/Amazon.JSII.Analyzers.csproj, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj, packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
Fixes errors preventing Windows environment test from succeeding.
```
@jsii/dotnet-runtime:   Failed to restore D:\a\jsii\jsii\packages\@jsii\dotnet-runtime\src\Amazon.JSII.Analyzers.UnitTests\Amazon.JSII.Analyzers.UnitTests.csproj (in 41.02 sec).
@jsii/dotnet-runtime:   Failed to restore D:\a\jsii\jsii\packages\@jsii\dotnet-runtime\src\Amazon.JSII.Runtime.UnitTests\Amazon.JSII.Runtime.UnitTests.csproj (in 41.02 sec).
```
```
@jsii/dotnet-runtime-test:   Failed to restore D:\a\jsii\jsii\packages\@jsii\dotnet-runtime-test\test\Amazon.JSII.Runtime.IntegrationTests\Amazon.JSII.Runtime.IntegrationTests.csproj (in 18.44 sec).
```
Several instances of NU1604 `Warning as Error`:  
```
@jsii/dotnet-runtime-test: D:\a\jsii\jsii\packages\@jsii\dotnet-runtime-test\test\Amazon.JSII.Runtime.Integration …
```
=> fix(dotnet-windows): specify versions for dotnet packages to prevent errors in Windows

CONTRIBUTING.md
The [jsii-superchain](https://github.com/aws/jsii-superchain) repo does not give a step-by-step for actually running the container for development. I have added a sample instruction that will work for most development use-cases.
---
=> docs(contributing): provide example instruction for using jsii-superchain docker image

.github/workflows/main.yml, packages/@scope/jsii-calc-base-of-base/package.json, packages/@scope/jsii-calc-base-of-base/test/assembly.jsii, packages/@scope/jsii-calc-base/package.json, packages/@scope/jsii-calc-base/test/assembly.jsii, packages/@scope/jsii-calc-lib/package.json, packages/@scope/jsii-calc-lib/test/assembly.jsii, packages/jsii-calc/package.json, packages/jsii-calc/test/assembly.jsii, packages/jsii-diff/package.json, packages/jsii-pacmak/package.json, packages/jsii-reflect/package.json, yarn.lock
Adds support for jsii-rosetta 5.8 to jsii-pacmak.
---
=> feat(pacmak): support jsii-rosetta 5.8

packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java, packages/@jsii/java-runtime/project/src/test/java/software/amazon/jsii/JsiiRuntimeTest.java
All credit for the detection and fix goes to @TimothyJones and his [PR](https://github.com/aws/jsii/pull/4802). This just adds a unit test on top of it.
Thanks @TimothyJones ! 
Fixes https://github.com/aws/jsii/issues/4801
---
=> fix(java-runtime): `ErrorStreamSink` crashes with `NullPointerException`

packages/@jsii/python-runtime/pyproject.toml, packages/@jsii/python-runtime/requirements.txt
Since the removal of a class in Python 3.12, we need a more modern version of `setuptools` to work on newer Python versions.
This gets rid of the error:
```
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```
---
=> chore: fix the Python build for Python >= 3.12

packages/@jsii/kernel/src/kernel.test.ts, packages/@jsii/kernel/src/kernel.ts, packages/@jsii/kernel/src/serialization.ts, packages/@jsii/spec/src/assembly-utils.ts, packages/@jsii/spec/src/assembly.ts, packages/jsii-pacmak/lib/index.ts, packages/jsii-pacmak/lib/rosetta-assembly.ts, packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts, packages/jsii-pacmak/lib/targets/dotnet/dotnettyperesolver.ts, packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-reflect/lib/type-ref.ts
This is a preparatory PR for adding support for intersection types (`A & B`) to jsii.
That feature might land or might not, but to figure it out we first need to update `@jsii/spec` to allow modeling intersection types to begin with, as other jsii packages live outside this repo so we can't do an atomic commit adding the feature everywhere; we have to release an updated version of the spec first.
To this end, we're doing the following:
- Add the necessary fields to the spec to express the new feature.
- Add a `usedFeatures` field to assemblies to indicate whether or not a "new feature" is being used, so that tools can reject an assembly if it's using a feature they don't support.
- Wherever we call Rosetta directly from `jsii-pacmak`, we have to do runtime type assertions to make sure the …
=> feat: prepare support for intersection types

packages/@jsii/kernel/package.json, packages/@jsii/runtime/package.json, packages/jsii-config/package.json, packages/jsii-diff/package.json, packages/jsii-pacmak/package.json, packages/jsii-reflect/package.json
The build in the main pipeline fails. I don't quite understand the reason, but it has to do with the `align-version` script:
* After the versions have been "aligned", all package versions in this repo have a dependency on `1.113.0` (which is an actually existing package)
* All of a sudden, the TypeScript compilation of `jsii-pacmak` starts picking up the types from the `1.113.0` version of `@jsii/spec`, rather than the local workspace version. 
* This might sound logical, but mind you that no files on disk have changed and no symlinks have been created. The Node.js place that `@jsii/spec` resolves to is still the local working copy, but TypeScript picks another version, from somewhere, for some reason.
Solve this by bumping to an unreleased version before doing the pipeline build. That …
=> chore: fix build problems

packages/jsii-pacmak/lib/npm-modules.ts, packages/jsii-pacmak/lib/packaging.ts, packages/jsii-pacmak/test/npm-modules.test.ts
If there are jsii targets in `package.json` that are not in the `.jsii` file (if the package hasn't been recompiled since targets were added) then pacmak explodes with a `reading properties from undefined` error.
Make pacmak consistently read targets from `.jsii` instead of sometimes from `package.json` and sometimes from `.jsii`.
Closes https://github.com/aws/jsii/issues/4913
---
=> fix: jsii-pacmak errors if new targets in package.json

CHANGELOG.md
It should be 1.114.1, since we skipped 1.114.0 due to a release glitch.
---
=> chore: changelog entry points to non existing release

packages/jsii-pacmak/lib/targets/java.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
In some places union types are rendered to overloaded setters, and in other places the type is collapsed to `Object`. Whenever the type is collapsed to `Object`, any other type information is lost for the user.
In this PR, emit the union type information to JavaDocs so users can find it again.
---
=> feat(jsii-pacmak): document union types in JavaDoc

packages/jsii-calc/lib/index.ts, packages/jsii-calc/lib/pascal-case-name/index.ts, packages/jsii-calc/test/assembly.jsii, packages/jsii-pacmak/lib/targets/python.ts, packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap, packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap, packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/tree.test.js.snap, packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Fixes #4426
This issue only occurred in submodule using a `pascalCased` name. The reason was that the dependency resolution did not the the same snake_case transformation of the submodule name: When the bases and interfaces of such a type where looked up, an untransformed fqn was used. Consequently the base or interface wasn't found and the type was considered dependency-less. This ultimately led to types being (incorrectly) emitted alphabetically.
The fix was to update the `TypeResolver` to use the same `toPythonFqn()` implementation as elsewhere in the code.
---
=> fix(pacmak): python classes are generated out of order

packages/@jsii/spec/src/assembly.ts
This adds support for the new `class-covariant-overrides` feature into `@jsii/spec`.
`class-covariant-overrides` relaxes the existing restriction on covariant overrides [^1]. With the feature it is now allowed to override the `type of readonly class properties` and the `return type of class methods` when extending other classes, as long as the changes are covariant [^2] [^3] to the superclass. Importantly, covariant overrides are still not allowed when implementing interfaces.
Compilers that are producing assemblies with covariant class overrides MUST include `class-covariant-overrides` in the `usedFeatures` set.
This feature does not require any changes to the kernels, runtimes or packmak. All generated code already is already correct when given an appropriate assembly. We can now add …
=> feat: declare support for new feature `class-covariant-overrides`

.github/dependabot.yml
We manage this one manually.
---
=> chore: prevent dependabot from updating the golang version
